### PR TITLE
[Merged by Bors] - new CI tuning

### PR DESCRIPTION
**Pull request by AmitShaul**
## Motivation
after setting the new CI out in the wild we get some errs who needs attention.
this PR is for fixing new issues with the new CI.

added more retries when creating\deleting a node pool (80 -> 800) # this is temporary until a more robust solution
fixed a bug:
when retrieving ES namespaced services sometimes we would get an empty result, added retry mechanism for this specific func.

### CODE REVIEW

**Comment by AmitShaul** [comment]
bors try

**Review by antonlerner — APPROVED** [review]

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try-

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors merge

**Comment by AmitShaul** [comment]
bors merge

**Comment by AmitShaul** [comment]
bors merge

**Comment by AmitShaul** [comment]
bors merge

**Pull request closed without merging**
