### PR TITLE
[Merged by Bors] - Discard stale state instead of failing migration

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

If during migration of `nipost_builder_state.bin` a stale challenge is encountered it will not be migrated to `local.sql`.

## Description

- extended the migration 0003 by checking if the challenge hash in `nipost_builder_state.bin` matches the hash in the `challenge` table in the DB
  - if not (or no challenge in DB) the state is considered stale and will not be migrated
- added new test to check for new behavior
- updated existing tests to be in a valid state (i.e. have a challenge in DB when migrating `nipost_builder_state.bin`).

## Test Plan

- existing tests were updated
- new test was added

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
I added `t.Skip` to the failing tests, those should be removed when merging https://github.com/spacemeshos/go-spacemesh/pull/5680/ and https://github.com/spacemeshos/go-spacemesh/pull/5683/

bors merge

**Pull request closed without merging**
