### PR TITLE
tests: speed up unit tests

### PR DESCRIPTION
**Pull request by dshulyak**
- remove `-p` limit so that tests from different modules can run in parallel
- and parallelized some of the tests

the bottleneck seems to be tests in activation module, but they don't want to work in parallel so leaving it for future

### CODE REVIEW

**Comment by dshulyak** [comment]
from ubuntu job

```
566:2023-04-18T06:29:20.5484770Z ok  	github.com/spacemeshos/go-spacemesh/activation	84.469s
849:2023-04-18T06:29:29.0528101Z ok  	github.com/spacemeshos/go-spacemesh/api/grpcserver	4.846s
1196:2023-04-18T06:30:35.7036192Z ok  	github.com/spacemeshos/go-spacemesh/beacon	63.428s
1200:2023-04-18T06:30:36.9075696Z ok  	github.com/spacemeshos/go-spacemesh/beacon/metrics	0.034s
1240:2023-04-18T06:30:39.2794133Z ok  	github.com/spacemeshos/go-spacemesh/beacon/weakcoin	0.693s
1388:2023-04-18T06:30:49.3837782Z ok  	github.com/spacemeshos/go-spacemesh/blocks	7.176s
1436:2023-04-18T06:30:50.4492055Z ok  	github.com/spacemeshos/go-spacemesh/bootstrap	0.194s
1459:2023-04-18T06:31:06.3999566Z ok  	github.com/spacemeshos/go-spacemesh/cmd/bootstrapper	3.223s
1473:2023-04-18T06:31:06.7805155Z ok  	github.com/spacemeshos/go-spacemesh/cmd/flags	0.024s
1564:2023-04-18T06:31:13.9513384Z ok  	github.com/spacemeshos/go-spacemesh/cmd/node	3.402s
1892:2023-04-18T06:31:16.1296377Z ok  	github.com/spacemeshos/go-spacemesh/common/types	0.075s
1900:2023-04-18T06:31:16.9106990Z ok  	github.com/spacemeshos/go-spacemesh/common/util	0.034s
1910:2023-04-18T06:31:19.0901148Z ok  	github.com/spacemeshos/go-spacemesh/config	0.088s
1918:2023-04-18T06:31:28.6242970Z ok  	github.com/spacemeshos/go-spacemesh/config/presets	7.465s
1942:2023-04-18T06:31:30.7594213Z ok  	github.com/spacemeshos/go-spacemesh/datastore	0.118s
1958:2023-04-18T06:31:31.5331567Z ok  	github.com/spacemeshos/go-spacemesh/eligibility	0.045s
1964:2023-04-18T06:31:32.5003045Z ok  	github.com/spacemeshos/go-spacemesh/events	0.045s
2166:2023-04-18T06:31:37.7604879Z ok  	github.com/spacemeshos/go-spacemesh/fetch	2.396s
3607:2023-04-18T06:31:45.0632165Z ok  	github.com/spacemeshos/go-spacemesh/genvm	4.602s
3651:2023-04-18T06:31:46.2460152Z ok  	github.com/spacemeshos/go-spacemesh/genvm/core	0.075s
3729:2023-04-18T06:31:47.2599712Z ok  	github.com/spacemeshos/go-spacemesh/genvm/templates/multisig	0.055s
3759:2023-04-18T06:31:48.1935906Z ok  	github.com/spacemeshos/go-spacemesh/genvm/templates/vault	0.040s
3822:2023-04-18T06:31:49.2116379Z ok  	github.com/spacemeshos/go-spacemesh/genvm/templates/wallet	0.044s
4229:2023-04-18T06:33:28.8781560Z ok  	github.com/spacemeshos/go-spacemesh/hare	95.173s
4288:2023-04-18T06:33:34.1117571Z ok  	github.com/spacemeshos/go-spacemesh/hare/eligibility	2.965s
4295:2023-04-18T06:33:34.8018849Z ok  	github.com/spacemeshos/go-spacemesh/layerpatrol	0.024s
4304:2023-04-18T06:33:35.3641310Z ok  	github.com/spacemeshos/go-spacemesh/log	0.024s
4366:2023-04-18T06:33:37.6244421Z ok  	github.com/spacemeshos/go-spacemesh/malfeasance	0.149s
4458:2023-04-18T06:33:42.2189066Z ok  	github.com/spacemeshos/go-spacemesh/mesh	1.910s
4464:2023-04-18T06:33:42.9319569Z ok  	github.com/spacemeshos/go-spacemesh/metrics	0.034s
4507:2023-04-18T06:33:45.8074200Z ok  	github.com/spacemeshos/go-spacemesh/miner	0.483s
4521:2023-04-18T06:33:47.8088974Z ok  	github.com/spacemeshos/go-spacemesh/p2p	0.129s
4583:2023-04-18T06:33:48.3891270Z ok  	github.com/spacemeshos/go-spacemesh/p2p/book	0.044s
4595:2023-04-18T06:33:49.6710659Z ok  	github.com/spacemeshos/go-spacemesh/p2p/handshake	0.058s
4606:2023-04-18T06:33:52.7869457Z ok  	github.com/spacemeshos/go-spacemesh/p2p/peerexchange	1.852s
4611:2023-04-18T06:33:54.2659952Z ok  	github.com/spacemeshos/go-spacemesh/p2p/pubsub	0.273s
4628:2023-04-18T06:33:55.4480368Z ok  	github.com/spacemeshos/go-spacemesh/p2p/server	0.070s
4771:2023-04-18T06:33:58.9563713Z ok  	github.com/spacemeshos/go-spacemesh/proposals	0.577s
4809:2023-04-18T06:34:02.2052343Z ok  	github.com/spacemeshos/go-spacemesh/signing	2.372s
4815:2023-04-18T06:34:03.0124346Z ok  	github.com/spacemeshos/go-spacemesh/sql	0.034s
4825:2023-04-18T06:34:03.9637675Z ok  	github.com/spacemeshos/go-spacemesh/sql/accounts	0.055s
4855:2023-04-18T06:34:06.1474865Z ok  	github.com/spacemeshos/go-spacemesh/sql/atxs	0.148s
4873:2023-04-18T06:34:07.2221255Z ok  	github.com/spacemeshos/go-spacemesh/sql/ballots	0.075s
4881:2023-04-18T06:34:08.1541940Z ok  	github.com/spacemeshos/go-spacemesh/sql/beacons	0.054s
4899:2023-04-18T06:34:09.1562266Z ok  	github.com/spacemeshos/go-spacemesh/sql/blocks	0.075s
4907:2023-04-18T06:34:10.1347285Z ok  	github.com/spacemeshos/go-spacemesh/sql/certificates	0.056s
4913:2023-04-18T06:34:11.0595161Z ok  	github.com/spacemeshos/go-spacemesh/sql/identities	0.046s
4927:2023-04-18T06:34:12.0173068Z ok  	github.com/spacemeshos/go-spacemesh/sql/kvstore	0.066s
4943:2023-04-18T06:34:12.9956810Z ok  	github.com/spacemeshos/go-spacemesh/sql/layers	0.076s
4954:2023-04-18T06:34:13.9230358Z ok  	github.com/spacemeshos/go-spacemesh/sql/poets	0.054s
4962:2023-04-18T06:34:14.8997188Z ok  	github.com/spacemeshos/go-spacemesh/sql/proposals	0.056s
4966:2023-04-18T06:34:15.8025564Z ok  	github.com/spacemeshos/go-spacemesh/sql/rewards	0.036s
5014:2023-04-18T06:34:17.1666786Z ok  	github.com/spacemeshos/go-spacemesh/sql/transactions	0.203s
11572:2023-04-18T06:34:33.9793976Z ok  	github.com/spacemeshos/go-spacemesh/syncer	13.646s
11608:2023-04-18T06:36:13.9198759Z ok  	github.com/spacemeshos/go-spacemesh/systest/validation	0.076s
11642:2023-04-18T06:36:16.0825432Z ok  	github.com/spacemeshos/go-spacemesh/timesync	1.295s
11679:2023-04-18T06:36:18.2418169Z ok  	github.com/spacemeshos/go-spacemesh/timesync/peersync	0.231s
12032:2023-04-18T06:36:30.3082482Z ok  	github.com/spacemeshos/go-spacemesh/tortoise	8.536s
12037:2023-04-18T06:36:41.0852182Z ok  	github.com/spacemeshos/go-spacemesh/tortoise/model	8.749s
12077:2023-04-18T06:36:41.8478655Z ok  	github.com/spacemeshos/go-spacemesh/tortoise/opinionhash	0.044s
12298:2023-04-18T06:37:09.6220954Z ok  	github.com/spacemeshos/go-spacemesh/txs	25.045s

```

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
> Error from server (BadRequest): Unable to find "/v1, Resource=configmaps" that match label selector "testid=systest-", field selector "": unable to parse requirement: values[0][testid]: Invalid value: "systest-": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
> golangci/golangci-lint info checking GitHub for tag 'v1.52.0'
golangci/golangci-lint info found version: 1.52.0 for v1.52.0/linux/amd64
make: *** [Makefile:63: install] Error 1
Error: Process completed with exit code 2.

**Comment by dshulyak** [comment]
bors merge

**Review by fasmat — APPROVED** [review]

**Review by poszu — APPROVED** [review]

**Pull request closed without merging**
