### PR TITLE
[Merged by Bors] - tortoise: misleading log if base ballot votes abstain and it matches local opinion

### LINKED ISSUE #4065: tortoise: validate code for encoding not terminated layers within zdist
image

this indicates that in that in some cases tortoise doesn't encode abstain votes correctly.

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/go-spacemesh/issues/4065

there was no bug, just added a test to double-check that it works correctly, and don't print misleading log

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
