### PR TITLE
[Merged by Bors] - docs: remove repetitive words

### PR DESCRIPTION
**Pull request by RiceChuan**
remove repetitive words

### CODE REVIEW

**Review by fasmat — APPROVED** [review]
Thank you for your contribution @RiceChuan 🙂

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by RiceChuan** [comment]
I don't know why the merge failed

**Comment by fasmat** [comment]
The first time was because of flaky system tests, the second time because of the merge from develop 🙂. We have a merge queue that does this automatically - the merge just takes ~ 50 minutes to run all tests.

bors merge

**Pull request closed without merging**
