### PR TITLE
[Merged by Bors] - p2p: Response change with io.ReadFull in go-scale

### PR DESCRIPTION
**Pull request by dshulyak**
requires: https://github.com/spacemeshos/go-scale/pull/21

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by evt — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
