### PR TITLE
Add sha256 sums in release job

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Adds sha256 sums for all created files during a release

## Changes
Update `release.yml` to add a step for sha256 calculation, upload file to GCP and add link to release description.

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by pigmej** [comment]
We definitely can't do it only like that. We need to publish sha sums separately out of the bucket also :)

**Comment by fasmat** [comment]
> We definitely can't do it only like that. We need to publish sha sums separately out of the bucket also :)

wdym? The shas in the bucket are the same as out of the bucket?

**Comment by fasmat** [comment]
@dsmello @andres-spacemesh can you help here?

**Comment by fasmat** [comment]
Closed in favour of https://github.com/spacemeshos/go-spacemesh/pull/5235

**Pull request closed without merging**
