### PR TITLE
[Merged by Bors] - sql: add hist for metering query duration

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Review by countvonzero — COMMENTED** [review]
i just realized that there is a sql/metrics package already. combine?

**Comment by dshulyak** [comment]
> i just realized that there is a sql/metrics package already. combine?

i plan to add a couple more changes for monitoring. will move that later

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
