### PR TITLE
[Merged by Bors] - Add nodepool lifecycle for systemtests

### PR DESCRIPTION
**Pull request by andres-spacemesh**
## Motivation

This PR automates the creation and cleanup of GKE node pools specifically for system tests in the CI pipeline. The goal is to provide dynamic, on-demand node pools that can be created before system tests and cleaned up afterward, improving resource utilization and reducing costs.

## Description

- **Node Pool Creation:** A new step has been added to the GitHub Actions pipeline to create a preemptible GKE node pool with a custom name based on the pipeline run ID.
- Node pool labels are added to track the pipeline ID for easier identification.
- **Node Pool Deletion:** A subsequent cleanup step has been added to delete the node pool after system tests are completed, ensuring that no unnecessary resources are left running.

This helps maintain stability in the infrastructure during system tests.

### CODE REVIEW

**Review by dsmello — APPROVED** [review]

**Comment by fasmat** [comment]
bors try

**Comment by dsmello** [comment]
bors try

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
bors try

**Comment by andres-spacemesh** [comment]
bors cancel

**Comment by andres-spacemesh** [comment]
bors try

**Comment by andres-spacemesh** [comment]
bors cancel

**Comment by andres-spacemesh** [comment]
Wroked as expected:
https://github.com/spacemeshos/go-spacemesh/actions/runs/11902954963

**Comment by fasmat** [comment]
bors merge

**Review by fasmat — APPROVED** [review]

**Pull request closed without merging**
