### PR TITLE
[Merged by Bors] - Migrate from github.com/pyroscope-io/pyroscope to github.com/grafana/pyroscope-go

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
`github.com/pyroscope-io/pyroscope` was renamed to `github.com/grafana/pyroscope` with their `v1.0.0` release. Additionally some parts of the repository were moved to other repositories.

We are only using the profiler, which is now located in the new repository `github.com/grafana/pyroscope-go`

## Changes
- Update dependency `github.com/pyroscope-io/pyroscope` to `github.com/grafana/pyroscope-go`

## Test Plan
existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
