### PR TITLE
[Merged by Bors] - Add priority queue to hare broker

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
See #2386 

## Changes
Change hare broker to use a priority queue, rather than a simple channel, for its inbox.

## Test Plan
Adds a test that makes sure self-generated, outbound Hare messages are prioritized over, and processed before, inbound messages

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by y0sher** [comment]
looks good to me so far, I'm assuming next steps are to pass `ownMessage` as `true` on `gossip.go` when calling `Broadcast`?

**Comment by lrettig** [comment]
> looks good to me so far, I'm assuming next steps are to pass `ownMessage` as `true` on `gossip.go` when calling `Broadcast`?

already done, here:

https://github.com/spacemeshos/go-spacemesh/pull/2391/files#diff-c764cdaa9d5b41a2a95b04e9f12f540d4ab1884b2f2cfa88c6dfb50906689292R83

**Review by y0sher — APPROVED** [review]
Looks good!

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
