### PR TITLE
[Merged by Bors] - Add ivan4th to CODEOWNERS

### PR DESCRIPTION
**Pull request by ivan4th**
## Changes
Add myself (@ivan4th) to CODEOWNERS, also remove an old entry

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
test failed by saying that one of the node has a different state in layer 21. in fact zero hash means that nothing was executed there.

image

looking futher both nodes executed _same_ blocks at 21 layer

image

so i suspect that we have a bug in the api, that somehow misses an update

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
