### PR TITLE
increase wakeup delta to deflake tests

### PR DESCRIPTION
**Pull request by dshulyak**
it seems there was a regression that makes proposal processing slower.

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
unrelated 
image

**Comment by dshulyak** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
another problem
image

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
hopefully won't be needed after disk updates

**Pull request closed without merging**
