### PR TITLE
[Merged by Bors] - Fix handling of module log levels (take two)

### LINKED ISSUE #2090: log.addDynamicLevel does not work as expected
## Description

`log.addDynamicLevel` (and the functions that rely on it, e.g., `Log.SetLevel`) use the [WrapCore](https://godoc.org/go.uber.org/zap#WrapCore) functionality of the underlying zap library to instantiate a new `coreWithLevel` struct that stores a logger core along with a dynamic level. When a log entry arrives, it runs a custom `Check` method that checks the log entry level against this dynamic level. However, rather than wrapping the `Check` method of the underlying logger, it replaces it entirely. This breaks some logging functionality, and some types of loggers: e.g., the [hooked core](https://godoc.org/go.uber.org/zap/zapcore#RegisterHooks) in turn wraps another core and passes each checked entry to the `Check` method of the wrapped core.

I think trying to wrap a log core in this way is not a good idea. It's using the log core in a way it isn't intended to be used. The right way to change a log level is with [IncreaseLevel](https://godoc.org/go.uber.org/zap#IncreaseLevel) but, as the name implies, this can only be used to _increase_ the log level (since it applies a filter).

## Steps To Reproduce

- Instantiate a logger with hooks. Logged entries will not be printed, regardless of log level.

## Expected Behavior

- All log entries should be passed down to all wrapped cores.

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
See #2090 

## Changes
- add a cleaner way to instantiate a new Log object, with an input level and an optional set of hook functions
- also add a way to instantiate a fully custom Log object (for testing)
- simplify the wrapped Log struct and remove the stored level and sugar objects
- set the level of a derived logger correctly, and warn if we try to set a lower level than the parent logger
- make sure the base loggers set up in the App are all debug level so messages coming from derived loggers won't get lost
- updating the log level of an existing logger just updates the atomic loglevel, nothing more
- remove functionality to log to a file, which is unused
- remove `InitSpacemeshLoggingSystem`, which did nothing
- make a few more config params inside log configurable for test purposes, such as encoder and logwriter
- upgrade to latest version of zap module (there's some missing functionality in the older version)
- fix a couple of unrelated, misc log statements

## Notes
- With the level object removed from the custom Log struct, there's not much need to have our own Log type in the first place. There's still some added niceties around field logging, but I think we could remove a ton of the Log logic and just use the underlying types for most, if not all, of this functionality. In order to minimize the size of this PR I've left this as a task for later (#2130).

## Test Plan
- Adds a new test module, log_test, that tests underlying log functionality, levels, etc.
- Updates existing app log test

## To do
- [x] add a test
- [x] check if cmd/node.go functionality to change a module log level still works
- [x] remove `InitSpacemeshLoggingSystem` and reinitialization of singleton logger, which is already initialized in `init()`

Closes #2090

### CODE REVIEW

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Review by antonlerner — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
