### PR TITLE
[Merged by Bors] - Added UT to early buffer in Hare

### PR DESCRIPTION
**Pull request by gavraz**

### CODE REVIEW

**Comment by gavraz** [comment]
bors merge

**Review by barakshani — APPROVED** [review]

**Comment by gavraz** [comment]
bors merge

**Comment by gavraz** [comment]
bors merge

**Comment by gavraz** [comment]
bors merge

**Comment by gavraz** [comment]
bors merge

**Comment by gavraz** [comment]
bors merge

**Pull request closed without merging**
