### PR TITLE
libp2p: disable asn db lookup

### PR DESCRIPTION
**Pull request by dshulyak**
libp2p compiled with asn database that uses about ~150MB. as far as i know we are using it, and can disable until we do.

related: https://github.com/spacemeshos/go-spacemesh/issues/4296

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by pigmej — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by fasmat** [comment]
Is this still necessary? `v0.3.0` has been released that loads the asn db lazily. If we are not using it, it won't be loaded.

See: https://github.com/libp2p/go-libp2p-asn-util/releases/tag/v0.3.0

EDIT: I'm also not sure the replacement is effective, since we are using `v0.3.0` already and the replacement targets `v0.2.0`

**Comment by dshulyak** [comment]
i probably didn't update this replacement after 0.3.0 was introduced, i was using this for older version, that is compatible with testnet5
but as you noticed it is not necessary anymore

**Pull request closed without merging**
