### PR TITLE
[Merged by Bors] - Add a `Makefile` target for running tests with the race detector

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

WIP on #2226 

## Changes

- Add a `test-race` `Makefile` target for running tests with the race detector

## Test Plan

- Run `make test-race`

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by antonlerner — APPROVED** [review]

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
borg merge

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
