### PR TITLE
[Merged by Bors] - Bump poet to v0.6.0 (increased hash difficulty)

### PR DESCRIPTION
**Pull request by poszu**
## Changes
Bumps poet to the latest v0.6.0. 

## Warning
Poet 0.6.0 changed hashing difficulty for calculating labels for the POSW (the Merkle tree leaves). Proofs generated with poet v0.6.x will not be valid for previous go-spacemesh nodes.

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
