### PR TITLE
[Merged by Bors] - Experimental: [WIP] Test a new enviroment to run the systest

### PR DESCRIPTION
**Pull request by dsmello**
Add the new test  cluster and optimaze the systest pipeline.

## Motivation

This refactor aims to streamline the CI/CD pipeline and enhance the reliability of system tests.

## Description

Refactor GitHub Actions workflow for system tests:
- Now the systest will run in two clusters at the same time
- The Node pool creation and the docker image build had their own step to optimize the pipeline time.

## Test Plan

Run the pipeline and check if the systest pass.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by andres-spacemesh — APPROVED** [review]

**Comment by dsmello** [comment]
bors try

**Comment by dsmello** [comment]
bors try

**Comment by dsmello** [comment]
bors try

**Comment by dsmello** [comment]
bors try

**Comment by dsmello** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Comment by dsmello** [comment]
@fasmat how do u want to proceed with this pr? Do we merge or wait and test against other PRs?

**Comment by fasmat** [comment]
lets merge it 🙂 

bors merge

**Pull request closed without merging**
