### PR TITLE
[Merged by Bors] - Implement `Rewind` in SVM package

### LINKED ISSUE #2832: Implement `Rewind` in SVM package
```go
func (s *SVM) Rewind(layer types.LayerID)
```
Called when a layer is rolled back, from self-healing.

### Called From
- `mesh/mesh.go` -> `Mesh.NewRecoveredMesh` - when loading state from the DB on node startup (SVM may not require this step - if that's the case we can clean this up later)
- `mesh/mesh.go` -> `Mesh.revertState` - triggered by self healing

### Existing Functions
- `TransactionProcessor.LoadState`
- `TransactionProcessor.GetStateRoot`

### SVM Functions
- `Rewind`

### PR DESCRIPTION
**Pull request by neysofu**
As per title. This PR is a follow-up to https://github.com/spacemeshos/go-spacemesh/pull/2864 and closes https://github.com/spacemeshos/go-spacemesh/issues/2832.

## Changes
The `LoadState` function is fully replaced with `Rewind`, which in the future will wrap a call to its equivalent `go-svm` `Rewind` counterpart. State root hash is also returned, which will be free information once SVM integration happens and can simplify ergonomics (avoid a call to `GetStateRoot`).

## Test Plan
Covered by existing testing.

## DevOps Notes
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]
:shipit:

**Comment by neysofu** [comment]
bors merge

**Comment by neysofu** [comment]
bors try

**Comment by neysofu** [comment]
bors try

**Comment by neysofu** [comment]
bors try

**Comment by neysofu** [comment]
bors merge

**Pull request closed without merging**
