### PR TITLE
[Merged by Bors] - chore(txs): cleanup logging and error handling

### PR DESCRIPTION
**Pull request by acud**
## Motivation

Cleans up the `txs` package from excessive logging and antipattern occurrences of `log an error then return it`.

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by acud** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
git checkout errors on windows

bors merge

**Comment by acud** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
