### PR TITLE
[Merged by Bors] - Only run protobuf for one remaining folder

### LINKED ISSUE #1942: ./merkle/pb/*.proto: No such file or directory
## Description

Cannot build go-spacemesh on OS X from a fresh clone of the develop branch

## Steps To Reproduce

```
> git clone git@github.com:spacemeshos/go-spacemesh.git
> make install
> make build
./scripts/genproto.sh
Generating protobuf for ./merkle/pb
./merkle/pb/*.proto: No such file or directory
make: *** [genproto] Error 1
```

## Environment
Please complete the following information:
 - OS: OS X
 - Node Version: commit c2d52d462ceaad0c587a3333c290d1db031d67aa

### PR DESCRIPTION
**Pull request by lrettig**
Don't attempt to look for other folders as we only care about one now, per @noamnelke.

## Motivation
Closes #1942

## Changes
These scripts should not attempt to find other dirs containing protobuf files. We just hardcode a single directory.

## Test Plan
N/A

Requires #1954

### CODE REVIEW

**Comment by lrettig** [comment]
I'm having trouble testing the Windows code due to #1954, will test when I can.

**Review by y0sher — APPROVED** [review]

**Comment by lrettig** [comment]
I still want to test this on Windows, blocking on #1954, will try again

**Review by noamnelke — APPROVED** [review]
LMK if you need me to review again after testing on Windows (if there are any changes).

**Comment by noamnelke** [comment]
@lrettig what's up with this? it's starting to rot...

**Comment by lrettig** [comment]
Rebased on the latest code. Unfortunately this is still blocking on #1954, which still has outstanding issues. Will keep working on it.

@noamnelke if you like we could split this PR into two, and merge the changes to `scripts/genproto.sh` while I keep working on the Windows issues.

**Comment by lrettig** [comment]
#1954 is resolved, all looks good, time to merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Pull request closed without merging**
