### PR TITLE
[Merged by Bors] - fetch: make request timeout configurable

### PR DESCRIPTION
**Pull request by ivan4th**
## Motivation
After merging #5462, it might make sense to try and reduce request timeout, as the deadlines will no longer be hit due to long transfers

## Changes
Add `request-timeout` key to the `fetch` config. Also, fix a typo

### CODE REVIEW

**Review by poszu — COMMENTED** [review]
The `RequestTimeout` is already configurable. Specifying the tag is optional: https://pkg.go.dev/github.com/mitchellh/mapstructure#hdr-Field_Tags

>When decoding to a struct, mapstructure will use the field name by default to perform the mapping.
>(...)
>You can change the behavior of mapstructure by using struct tags. The default struct tag that mapstructure looks for is "mapstructure"  (...)

The "default tag" for this field is `requestTimeout`.

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
@poszu I think we should use `IgnoreUntaggedFields` just because it is unintuitive that non-tagged fields are already exported 🙂  see also #5466

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
bors merge

**Pull request closed without merging**
