### PR TITLE
make systests on ci faster

### PR DESCRIPTION
**Pull request by dshulyak**
- decrease cluster size from 50 to 30
- increase parallelism by two, to 8

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Comment by dshulyak** [comment]
@countvonzero do you have any concerns wrt reducing size to 30? i remember you had opinion in the past

**Comment by dshulyak** [comment]
bors try

**Comment by countvonzero** [comment]
> @countvonzero do you have any concerns wrt reducing size to 30? i remember you had opinion in the past

no. i dont recall any concerns. ive been using 30 w manual testing

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Pull request closed without merging**
