### PR TITLE
[Merged by Bors] - Bump post-rs to v0.7.8

### PR DESCRIPTION
**Pull request by poszu**
## Description

Bump post-rs to the latest released version.

## Test Plan

n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by fasmat** [comment]
rpc error

bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
