### PR TITLE
[Merged by Bors] - disable beacon protocol in epoch 7

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation
disable beacon protocol until #4989 and #4583 are fixed

## Changes
set RoundsNumber == 0 to disable beacon protocol and not listen to beacon gossip

## TODO
- [x] Update [changelog](../CHANGELOG.md) as needed
- [x] test on devnet-406-short

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
the main reason why we disable it is this https://github.com/spacemeshos/go-spacemesh/issues/4989 . we need to find a way to run it. i am not even sure that idea with simple jitter will be sufficient

https://github.com/spacemeshos/go-spacemesh/issues/4583 is a follow to make that change succeed

**Review by fasmat — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
