### PR TITLE
[Merged by Bors] - Fix stale peer eviction

### LINKED ISSUE #3397: p2p: eventually evict disconnected peer from address book
## Description

during longevity testing, p2p would emit error logs for nodes that we replaced during tests. an error log is printed for each disconnected peer every X seconds where X ranges from 10-90 seconds.
and this is for every peer the node lost connection ever. this produced ~500 error logs every 10 min and lasted till the end of the test.

it would appear that disconnected peers are not removed from the address book.

log snippet
```
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.955-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWHfVBhsnXsCEXEA8CjU1Pn8vWVDbppiKzuxRMem1s3cdu","errmsg":"no good addresses","name":"p2p"}
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.957-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWSofbFHnoyNkmgVMTQ5bjmuNsEuaHwesFU3q2D8MqvUGp","errmsg":"failed to dial 12D3KooWSofbFHnoyNkmgVMTQ5bjmuNsEuaHwesFU3q2D8MqvUGp:\n  * [/ip4/10.0.1.20/tcp/7513] dial backoff","name":"p2p"}
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.957-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWMK8uyp8dJjXNn8mpEN3fvjoLwQSJtmv3c7xpfHfm1qWa","errmsg":"no good addresses","name":"p2p"}
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.959-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWBtKW2hD2T2MdviXJ5qWqaX4ZbnVfLcbrJrZoF2Twm6cL","errmsg":"failed to dial 12D3KooWBtKW2hD2T2MdviXJ5qWqaX4ZbnVfLcbrJrZoF2Twm6cL:\n  * [/ip4/10.0.1.11/tcp/7513] dial backoff","name":"p2p"}
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.960-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWGXxqnC1kxzk6LSXo8KkWkM2bUUwFMETcHQBbavvqj6AY","errmsg":"failed to dial 12D3KooWGXxqnC1kxzk6LSXo8KkWkM2bUUwFMETcHQBbavvqj6AY:\n  * [/ip4/10.0.1.7/tcp/7513] dial backoff","name":"p2p"}
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.960-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWCdmeu4GwP36L9dgx15rADhANX6uR9ek8TemKXFLXY9Dw","errmsg":"failed to dial 12D3KooWCdmeu4GwP36L9dgx15rADhANX6uR9ek8TemKXFLXY9Dw:\n  * [/ip4/10.0.2.23/tcp/7513] dial backoff","name":"p2p"}
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.960-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWCThvyPGHe5mUTPWanCNRCX12ieRZiEPKF6uLYgZJYS3t","errmsg":"failed to dial 12D3KooWCThvyPGHe5mUTPWanCNRCX12ieRZiEPKF6uLYgZJYS3t:\n  * [/ip4/10.0.2.9/tcp/7513] dial backoff","name":"p2p"}
2022-08-01 12:40:05	
{"L":"ERROR","T":"2022-08-01T15:40:05.965-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWEXqEv6UoU2edY6gKz7ugpSy5SKXohaCeGC1FXkAXjSKW","errmsg":"failed to dial 12D3KooWEXqEv6UoU2edY6gKz7ugpSy5SKXohaCeGC1FXkAXjSKW:\n  * [/ip4/10.0.2.12/tcp/7513] dial backoff","name":"p2p"}
2022-08-01 12:40:10	
{"L":"ERROR","T":"2022-08-01T15:40:10.966-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWGMaAHMoVB6NjymmZnT5Sny1AF5dyqd1TYMrX8tLYZhzk","errmsg":"failed to dial 12D3KooWGMaAHMoVB6NjymmZnT5Sny1AF5dyqd1TYMrX8tLYZhzk:\n  * [/ip4/10.0.1.24/tcp/7513] dial tcp4 0.0.0.0:7513->10.0.1.24:7513: i/o timeout","name":"p2p"}
2022-08-01 12:40:10	
{"L":"ERROR","T":"2022-08-01T15:40:10.967-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWPXBnzFxVtRh1PfQTiisw8t7teGoTkq9Nogf9qi8Vb9F2","errmsg":"failed to dial 12D3KooWPXBnzFxVtRh1PfQTiisw8t7teGoTkq9Nogf9qi8Vb9F2:\n  * [/ip4/10.0.2.19/tcp/7513] dial backoff","name":"p2p"}
2022-08-01 12:40:15	
{"L":"ERROR","T":"2022-08-01T15:40:15.957-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWHfVBhsnXsCEXEA8CjU1Pn8vWVDbppiKzuxRMem1s3cdu","errmsg":"no good addresses","name":"p2p"}
2022-08-01 12:40:15	
{"L":"ERROR","T":"2022-08-01T15:40:15.957-0400","N":"b4141.p2p          ","M":"failed to connect to peer","node_id":"b414165507ca0823b2fd71c9bad03a15732b8c1b9db47c0a93a40f020bc53ed0","module":"p2p","peer":"12D3KooWMK8uyp8dJjXNn8mpEN3fvjoLwQSJtmv3c7xpfHfm1qWa","errmsg":"no good addresses","name":"p2p"}
```

screenshot at the beginning of the TestStepReplaceNodes.

Screenshot from 2022-08-01 22-34-18

screenshot at the end of the test.
Screenshot from 2022-08-01 22-34-44

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
See #3397 for the bug root cause analysis and motivation for this change.

Closes #3397

## Changes
There are three critical changes in this PR
1. Book check algorithm now selects peers for eviction by looking at the `LastSuccess` timestamp instead of `LastSeen`. `LastSeen` can be updated frequently in crawling the network (`crawler::query()`). It is updated whenever another peer sends us an address. However, `LastSeen` doesn't actually tell us if the peer is alive. `LastSuccess`, on the other hand, marks the last time when we successfully connected to that peer.

2. Stale peers are not broadcasted in the `peer exchange` protocol. Now, only peers that satisfy one of the conditions:
    - have been successfully connected to within `stalePeerTimeout`,
    - they are new peers and have not been tried yet (`LastAttempt` ~= "never")

    are shared with the other peer. 
    The optimistic sharing of peers which we haven't tried yet is meant to speed up the propagation of new peers. Otherwise, a new peer would have to be first tried on each "hop", which can take a few moments (depending on the configuration). It is not harmful because even if this peer eventually turns out to be "dead", it will be soon evicted.

3. Address Book keeps an LRU cache of recently removed peers. Before adding an address back to the address book, one can now check if and when that peer was removed. It lets the discovery logic skip adding evicted peers back.

## Test Plan
unit tests, manual on-cluster longevity tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
> > Address Book keeps an LRU cache of recently removed peers. Before adding an address back to the address book, one can now check if and when that peer was removed. It lets the discovery logic skip adding evicted peers back.

i think this is redundant, but up to you. we can keep peer that is not responsive in the addressbook until we need space, so technically addressbook serves the same purpose as lru

**Comment by poszu** [comment]
@dshulyak 
> > Address Book keeps an LRU cache of recently removed peers. Before adding an address back to the address book, one can now check if and when that peer was removed. It lets the discovery logic skip adding evicted peers back.
> 
> i think this is redundant, but up to you. we can keep peer that is not responsive in the addressbook until we need space, so technically addressbook serves the same purpose as lru

It became required after I added the optimistic sharing of peers that have not been tried yet. The unresponsive peers were bouncing from node to node.

I don't understand your statement that it is OK to keep unresponsive peers in the address book until it is full and they are evicted. If it is OK, then why implement the eviction logic in the first place?

**Comment by dshulyak** [comment]
> I don't understand your statement that it is OK to keep unresponsive peers in the address book until it is full and they are evicted. If it is OK, then why implement the eviction logic in the first place?

sorry i think i was going to write: we can keep peer that is not responsive in the addressbook until we need space or it is time to evict that peer. but nvm, lets just merge this change

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
