### PR TITLE
[Merged by Bors] - Make testnet join instructions generic

### PR DESCRIPTION
**Pull request by lrettig**
Update link and instructions for joining the latest testnet

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]
Good enough for now, let's merge it.

**Comment by lrettig** [comment]
bors merge

**Comment by avive** [comment]
It is good we are updating but you want to add how to get a CLIWallet that works with go-sm - something like what I wrote at the bottom of this: https://github.com/spacemeshos/go-spacemesh/releases/tag/v0.1.22 . There is a specific CLIWallet release that is kind of verified to work with the TN.

**Comment by lrettig** [comment]
This is blocking on #2272

**Comment by avive** [comment]
Why not just edit readme on github in place in develop branch for now?

**Comment by avive** [comment]
Sorry, looks like this is blocked as well because develop is a protected branch.

**Comment by web3rover** [comment]
If there is no specific reason to show the latest tweedledee version then I would prefer to change the link to https://github.com/spacemeshos/go-spacemesh/releases/latest and explicitly mention that follow the steps in the latest release to join the network. This way we don't need to keep updating the readme.

**Comment by lrettig** [comment]
Exactly. Unfortunately there's no way around bors, even for simple
documentation changes. That's why documentation like this that's updated
frequently should be moved out of go-spacemesh into another repo where we
can change it more easily.

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
