### PR TITLE
Add tests for all local file system functions

### PR DESCRIPTION
**Pull request by jreyeshdez**
Add tests for all local file system functions:
- Initial work for #65 → adding unit test for functions defined in [dirs.go](https://github.com/spacemeshos/go-spacemesh/blob/79c25e8a7612a8852908f067c661d2c38839a093/filesystem/dirs.go#L2)

### CODE REVIEW

**Comment by avive** [comment]
@jreyeshdez - thanks for the PR! Can you please pull from branch `develop` and ask to merge back to `develop` and not to `master` ? Also, for temp folder - can you please have a look at GetSpacemeshTempDirectoryPath() - the basic idea is that we create temp file in a consistent place in the spacemesh master directory so one doesn't have to go hunt down the temp folder when using it to write files. It will be great if you can add tests to all the methods currently at dirs.go - including the ones that got recently added.

**Comment by jreyeshdez** [comment]
@avive , will do, sorry.
- `GetSpacemeshTempDirectoryPath` , do you mean using this function for `TestPathExists` instead of using `CreateTmpDir` and `RemoveTmpDir` ?
- Yes, I am working on adding new tests for all the functions.

**Comment by avive** [comment]
No need to be sorry - your effort is good. Yes - using our own notion of a temp dir and not just a temp dir on the local file system. Another note - I believe that in some systems configs there might not be a defined user home directory and we should address that in the tests.

**Comment by avive** [comment]
#80

**Pull request closed without merging**
