### PR TITLE
[Merged by Bors] - Reset CHANGELOG and update GH release info

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Prepares `develop` for next release

## Changes
- Add `UNRELEASED` section to `CHANGELOG.md`
- Update Info about release with link to changelog

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by piersy — APPROVED** [review]
Looking good !

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
