### PR TITLE
[Merged by Bors] - Fix fatal error in multi_node_sim

### LINKED ISSUE #2253: Concurrent map read and map write when multi_node_sim is running
## Description

Under very rare conditions, `multi_node_sim` throws a fatal error because of concurrent map read and map write. Then, the PoET server becomes unavailable. However, `multi_node_sim` continues running.

## Steps To Reproduce
1. Go to `./cmd/multi_node_sim`
2. Run `go build`
3. Run `ulimit -n 10000; ./multi_node_sim -n 10 -l 100 -b 10 2>&1 | tee multi_node_sim.log`
4. If a lot of logs like `failed to broadcast via gateway node at "127.0.0.1:9092"` appear in logs, this means the fatal error is above in logs

## Expected Behavior

Lack of fatal error.

## Environment
Please complete the following information:
 - OS: 
 
 MacOS
 - Node Version: 
 
 Not applicable, commit `e0c08c459b12edbfba126a2a2453962a5076e7f9`
 - App Version (if applicable): 
 
 Not applicable

## Additional Resources 

```
fatal error: concurrent map read and map write

goroutine 1 [running]:
runtime.throw(0x1d2d7f6, 0x21)
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/panic.go:1116 +0x72 fp=0xc026cb8ec8 sp=0xc026cb8e98 pc=0x1038fb2
runtime.mapaccess2_faststr(0x1b8f6c0, 0xc018d7cc00, 0xc029e4a490, 0xa, 0x1, 0x1)
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/map_faststr.go:116 +0x4a5 fp=0xc026cb8f38 sp=0xc026cb8ec8 pc=0x10165a5
github.com/spacemeshos/go-spacemesh/cmd/node.StartMultiNode(0xa, 0xa, 0xc000000064, 0x1d1059a, 0x8)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/cmd/node/multi_node.go:347 +0x1652 fp=0xc026cb9d50 sp=0xc026cb8f38 pc=0x1a79712
main.glob..func1(0x25bb060, 0xc000092a80, 0x0, 0x6)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/cmd/multi_node_sim/multi_node_sim.go:41 +0x5b fp=0xc026cb9d88 sp=0xc026cb9d50 pc=0x1a8a5db
github.com/spf13/cobra.(*Command).execute(0x25bb060, 0xc0001b0010, 0x6, 0x6, 0x25bb060, 0xc0001b0010)
	/Users/nkryuchkov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2 fp=0xc026cb9e60 sp=0xc026cb9d88 pc=0x183e4a2
github.com/spf13/cobra.(*Command).ExecuteC(0x25bb060, 0x1008345, 0xc000180058, 0x0)
	/Users/nkryuchkov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375 fp=0xc026cb9f38 sp=0xc026cb9e60 pc=0x183f1d5
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/nkryuchkov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/nkryuchkov/GolandProjects/go-spacemesh/cmd/multi_node_sim/multi_node_sim.go:50 +0x31 fp=0xc026cb9f88 sp=0xc026cb9f38 pc=0x1a8a4f1
runtime.main()
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/proc.go:204 +0x209 fp=0xc026cb9fe0 sp=0xc026cb9f88 pc=0x103b769
runtime.goexit()
	/usr/local/Cellar/go/1.15.5/libexec/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc026cb9fe8 sp=0xc026cb9fe0 pc=0x10718a1

<...>
```

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

Closes #2253 

## Changes

- Fix fatal error in `multi_node_sim`

## Test Plan

1. Attempt to reproduce #2253 following steps from the PR description
2. There should be no fatal error

### CODE REVIEW

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try

**Comment by noamnelke** [comment]
bors try-

**Comment by noamnelke** [comment]
bors try

**Review by antonlerner — APPROVED** [review]

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try-

**Comment by nkryuchkov** [comment]
bors try

**Comment by noamnelke** [comment]
bors try-

**Comment by noamnelke** [comment]
bors ping

**Comment by noamnelke** [comment]
bors try-

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
