### PR TITLE
[Merged by Bors] - block logs

### PR DESCRIPTION
**Pull request by almogdepaz**
## Motivation
print block shortid in logs

### CODE REVIEW

**Review by barakshani — APPROVED** [review]

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by barakshani** [comment]
Another log need: is it possible to add to the (validation queue) log `start handle block %v` the `sender_id`, like we have for blocks that we receive by gossip?

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Pull request closed without merging**
