### PR TITLE
[Merged by Bors] - scale: limit the depth of decoded messages

### LINKED ISSUE #4094: hare: limit the depth of decoded messages
in the implementation hare certificate encoded as the set of commit message, using this type

```go
type Certificate struct {
	Values  []types.ProposalID // the committed set S
	AggMsgs *AggregatedMessages
}
```

this bloats the notify message to approximately ~480KB, however most of the information there is redundant. there are two approaches how this can be improved:

## use set_hash in commit message

```rust
pub struct BloatedCommitMessage {
    layer: Layer,
    iteration: Iteration,
    eligibility: VrfProof,
    set: Pblocks,
    signature: Signature,
}

pub struct CompactCommitMessage {
    layer: Layer,
    iteration: Iteration,
    eligibility: VrfProof,
    set_hash: Hash256,
    signature: Signature,
}
``` 

this reduces both commit message in size and notify message (to about ~70KB).
hare needs to check that commit message votes for the best proposal using hash of the proposal. and same validation when commit message is modified

## encode only signature and vrf output in certificate

```rust
pub struct CommitSignature {
    eligibility: VrfProof, // 82
    signature: Signature // 64
}

pub struct Certificate {
    set: Pblocks,
    commits: Vec<CommitSignature>,
}
```
 
second alternative extracts non-duplicate information from commit messages and encodes it into certificate. receiver reconstructs full message and validates certificate. with this approach notify message is around 58KB.

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Closes #4094. Merge after https://github.com/spacemeshos/go-scale/pull/60 has been merged and released.

## Changes
- Integrates go-scale with limit on nesting in types
- Default max. nesting depth is 4, can be configured if more or less is better

## Test Plan
- Tests added to go-scale for new functionallity.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by countvonzero** [comment]
i'd change the PR title to remove "hare", as this is not a hare specific change.

**Review by dshulyak — APPROVED** [review]
would be good to adjust title

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
