### PR TITLE
[Merged by Bors] - Remove types.AtxTortoiseData

### PR DESCRIPTION
**Pull request by poszu**
## Description

Use `atxsdata.ATX` in place of `types.AtxTortoiseData` for `Tortoise::OnAtx()` to avoid type conversions and have 1 less type for the same thing.

## Test Plan

Existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Retrying as `TestPartition_50_50` failed.

bors merge

**Pull request closed without merging**
