### PR TITLE
[Merged by Bors] - Amortize post cost

### LINKED ISSUE #175: Amortize the cost of finding a nonce for POPS-VRF
## The task

Amortize the computation cost of finding a nonce to support the [POPS-VRF](https://github.com/spacemeshos/pm/issues/172) scheme through the cost of PoST initialization. Then apply it to the initial ATX.

## Background

https://github.com/spacemeshos/gpu-post supports the amortization via the `COMPUTE_POW` flag (which was added in addition to the `COMPUTE_LEAFS` flag, needed for the actual initialization). For more info, see [here](https://github.com/spacemeshos/SMIPS/issues/45).

## Breakdown 

https://github.com/spacemeshos/post & https://github.com/spacemeshos/go-spacemesh

* Enable the activation of the `COMPUTE_POW` flag, and use it in order to find a nonce which satisfies `H( nonce ++ VRFpk ++ PositioningATX ) < d`. 
* Create a calculation function for the difficulty threshold `d`. It should define a probability of finding one single nonce for the entire PoST initialization, meaning one for every (number of units) *  (number of labels per unit), when applied to the total range of values space in 32 bytes.
* If no successful nonce was found during the entire initialization phase, continue to compute labels for nonce-finding, PoW purposes only (`COMPUTE_LEAFS` off, `COMPUTE_POW` on), until succeeding.
* Upon finding a successful nonce
   * Add it to the initial ATX
   * Add it to the PoST metadata file
 * Verify incoming initial-ATXs' nonce to satisfy `H( nonce ++ VRFpk ++ PositioningATX ) < d`. The hash function is the work oracle function from PoST initialization, also used in PoST verification to compute a given label.

### LINKED ISSUE #3831: Refactor PoST initialization to be more resiliant and fix known bugs
## Description

The PoST initialization code is buggy and needs refactoring. I suggest to move from a session based architecture to a worker / cancelation based one. This means:

- Instead of `StartSession` and `StopSession` functions for `PostSetupManager` just have a cancelable `Init` method
- `StopSession` is replaced by canceling the context passed to `Init` and a new `Reset()` method that deletes PoST data when called
- Update tests to not share state between them and fix data races
- Use `WaitGroup` and/or `errGroup` to synchronize long running processes.
- The `Status` method of the `PostSetupManager` incorrectly reports the state of PoST initialization when `dataDir` is changed (see also https://github.com/spacemeshos/smapp/issues/1027)
  - This probably changes to the `Initializer`; [this check / calculation](https://github.com/spacemeshos/post/blob/37b841e69cfffd8774b8a7eeccfe6f7c3a87ac60/initialization/initialization.go#L196-L212) to set `NumLabelsWritten` should probably already happen in `NewInitializer`.
  - Investigate if https://github.com/spacemeshos/smapp/issues/1034 is also fixed by this.
- Investigate if the initial delay reported in https://github.com/spacemeshos/go-spacemesh/issues/3795 is also fixed by updating the `Status` method.

## Affected code

`Initializer` in `post` repository and `PostSetupManager` in `go-spacemesh` repository + code and tests using these components.

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
This PR adds the VRF Nonce to the initial ATX of a node and verifies incoming (initial) ATXs for the validity of their nonces.

Do not merge before https://github.com/spacemeshos/api/pull/200

Closes https://github.com/spacemeshos/pm/issues/175 and https://github.com/spacemeshos/go-spacemesh/issues/3831

## Changes
This integrates the following changes from post into go-spacemesh:
- https://github.com/spacemeshos/post/pull/67
- https://github.com/spacemeshos/post/pull/91
- https://github.com/spacemeshos/post/pull/92
- https://github.com/spacemeshos/post/pull/93

`PostSetupManager` was updated, `StartSession` is now synchronous and cancelable (via `context`). Other methods on `PostSetupManager` are still save to be called while `StartSession` is running.

Additionally tests were refactored to fix data races that only occurred in test code.

@maparr: this should fix most of the issues that recently popped up regarding PoST initialization. There are now 5 states the PostSetup can be in:

- 1: PostSetupStateNotStarted (no data available)
- 2: PostSetupStateInProgress (PoST is initializing)
- 3: PostSetupStateStopped (**new** : returned when PoST setup was stopped before it was complete)
- 4: PostSetupStateComplete (PoST is ready)
- 5: PostSetupStateError (some error occurred; check logs)

Open TODOs for future PRs:
- https://github.com/spacemeshos/pm/issues/201
- https://github.com/spacemeshos/go-spacemesh/issues/3759
- https://github.com/spacemeshos/go-spacemesh/issues/3843 (post genesis)

## Test Plan
Additional tests were added that check if incoming initial ATXs are verified to have a valid VRFNonce and that initial ATXs published by the node are published with a Nonce 

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Review by moshababo — APPROVED** [review]
LGTM

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
