### PR TITLE
[Merged by Bors] - mesh: report event outside a db tx

### LINKED ISSUE #3537: TestFailedNodes failure due to emitting event before db tx is committed
https://github.com/spacemeshos/go-spacemesh/pull/3530

https://github.com/spacemeshos/go-spacemesh/runs/8223508481?check_suite_focus=true

see that every node in the cluster updated hash correctly `{namespace="test-ngug"} |= "3b8e1"`
but one of the nodes received zeroes from the stream.

this event https://github.com/spacemeshos/go-spacemesh/blob/55bd715f626f6b0397ffe16337544965fc9ebb07/mesh/mesh.go#L421-L424 needs to be emitted after db tx commits.

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3537

## Changes

report applied event after a db transaction committed

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Review by fasmat — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by dshulyak** [comment]
i think one of the nodes was preempted during the test. that sort of expected wit them
```
gke-ci-infra-gha-62896c99-61b7            Ready    <none>   27m     v1.21.14-gke.700
```

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
> i think one of the nodes was preempted during the test. that sort of expected wit them
> 
> ```
> gke-ci-infra-gha-62896c99-61b7            Ready    <none>   27m     v1.21.14-gke.700
> ```

yeah, i saw that with the longevity cluster yesterday too.

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
