### PR TITLE
[Merged by Bors] - activate sync genesis test

### PR DESCRIPTION
**Pull request by almogdepaz**
## Motivation
test was commented out due to failures

### CODE REVIEW

**Comment by almogdepaz** [comment]
bors try

**Comment by almogdepaz** [comment]
bora merge

**Comment by almogdepaz** [comment]
bors merge

**Review by AmitShaul — APPROVED** [review]

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors cancel

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Pull request closed without merging**
