### PR TITLE
[Merged by Bors] - 3284 revert old hare certification implementation

### LINKED ISSUE #3284: hare: Revert old "hare certification" implementation
Wasn't implemented properly:
https://github.com/spacemeshos/go-spacemesh/issues/1966
https://github.com/spacemeshos/go-spacemesh/pull/2390

must revert.

Will be re-implemented by: https://github.com/spacemeshos/go-spacemesh/issues/3283

### PR DESCRIPTION
**Pull request by jonZlotnik**
## Motivation
Check the issue over there ------->

## Changes
undid all of the old hare certification code

## Test Plan
Tested using existing unit tests. (just don't break anything new)

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by jonZlotnik** [comment]
bors try

**Comment by jonZlotnik** [comment]
bors merge

**Comment by jonZlotnik** [comment]
bors try

**Comment by jonZlotnik** [comment]
bors try

**Comment by jonZlotnik** [comment]
bors try

**Comment by jonZlotnik** [comment]
bors try

**Comment by jonZlotnik** [comment]
bors merge

**Comment by dshulyak** [comment]
last failure is a bug in ci job

```
Run SUCCESS='null'
Error: Process completed with exit code 1.
```

**Comment by jonZlotnik** [comment]
> last failure is a bug in ci job
> 
> ```
> Run SUCCESS='null'
> Error: Process completed with exit code 1.
> ```

Systests passed though. Weird.
must be an issue with this:
https://github.com/spacemeshos/go-spacemesh/blob/3613b9f5069c1daf7a32a47b71d0f7c1d49bc0c7/.github/workflows/ci.yml#L214

One more time?
If it fails again, I'll ping the devops crew

**Comment by jonZlotnik** [comment]
bors merge

**Pull request closed without merging**
