### PR TITLE
[Merged by Bors] - Update go-scale to v1.1.1

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Integrates the newest version of go-scale to go-spacemesh

## Changes
go-scale was updated

## Test Plan
Existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Review by poszu — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by fasmat** [comment]
borse merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
