### PR TITLE
[Merged by Bors] - Fix wrongly wrapped error in hare flows test

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

An error was wrongly wrapped in https://github.com/spacemeshos/go-spacemesh/pull/2855. Fixed by this PR

## Changes

- Fix wrongly wrapped error in hare flows test

## Test Plan

- Unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by nkryuchkov** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
right, i thought that this was weird while changing tests in hare

**Comment by nkryuchkov** [comment]
bors try-

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
