### PR TITLE
WIP: Add tests for all local file system functions

### PR DESCRIPTION
**Pull request by jreyeshdez**
- Add tests to [dirs.go](https://github.com/spacemeshos/go-spacemesh/blob/f411299685256b80f140ba017de03692a29749cf/filesystem/dirs_test.go#L1)
- Changed how `currentUser` was retrieved in `GetUserHomeDirectory` to allow mocking in tests
- Added helpers to `dirs_test_helpers.go`

### CODE REVIEW

**Comment by jreyeshdez** [comment]
@avive please, check it and let me know your thoughts if we are following correct path here..

**Comment by avive** [comment]
Looking good overall, but the build fail due to a golint issue. https://travis-ci.org/spacemeshos/go-spacemesh/jobs/335224638 . You can run `make lint` to see what golint is complaining about. I'll merge as soon as the build passes.

**Comment by jreyeshdez** [comment]
It also fails as I was expecting when trying to create folders. It didn't fail on Windows

**Comment by avive** [comment]
I think you just pushed the golint fixes to the other pr...

**Pull request merged**
