### PR TITLE
issue-374: Add unit tests to Hare's implementation

### PR DESCRIPTION
**Pull request by wliyongfeng**

### CODE REVIEW

**Comment by antonlerner** [comment]
Hey @wliyongfeng , we are still reviewing your PR, if the current contributor won't submit any work in the upcoming days we'll assign this task to you and be happy to review and accept your code

**Comment by wliyongfeng** [comment]
@antonlerner Okay.

**Comment by wliyongfeng** [comment]
@antonlerner Currently `algorithm_test.go` reache 85% coverage. Please review the PR.

**Comment by antonlerner** [comment]
@gavraz Please review whenever you are ready

**Comment by gavraz** [comment]
Hi,
Thank you for the tests.
There have been many changes since we introduced the issue. We may cherry-pick some of the tests later on.

**Comment by wliyongfeng** [comment]
@gavraz 👌

**Pull request closed without merging**
