### PR TITLE
[Merged by Bors] - add debug log temporarily for flaky test

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

debugging #3781

## Changes

turn on debug log for TestForkFinder_FindFork_Permutation

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
