### PR TITLE
ci: reduce bootstrap time

### PR DESCRIPTION
**Pull request by dshulyak**
i changed deployment method in the recent change to systest. in my tests that change allows to expect shorter bootstrap time

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Review by abergasov — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
