### PR TITLE
[Merged by Bors] - Upgrade go-libp2p to v0.37.2

### PR DESCRIPTION
**Pull request by ivan4th**
## Motivation

Need to switch to a more up-do-date go-libp2p version.

## Description

Also, upgrade go-libp2p-kad-dht to v0.28.1 and quic-go to v0.48.2.
There's a bug in go-libp2p related to reuse of the slices retured by `AddrsFactory`, fix: libp2p/go-libp2p#3068
For now, the problem is mitigated by cloning the slice returned from `AddrsFactory` (`cfg.AdvertiseAddress`).
Deprecated `max-reservations-per-peer` field in the relay server config, as now it is always 1 (and other values didn't make too much sense).

## Test Plan

Verify on mainnet / testnet nodes

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan

### CODE REVIEW

**Comment by ivan4th** [comment]
Marking it as a draft to give it a bit more testing before we merge it.

**Comment by ivan4th** [comment]
bors try

**Comment by ivan4th** [comment]
P2P appears to work fine

**Review by fasmat — APPROVED** [review]

**Comment by ivan4th** [comment]
bors merge

**Pull request closed without merging**
