### PR TITLE
[Merged by Bors] - add duplicate TX check and some cleanup

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

adding duplicate TX check and some cleanup before making more changes

## Changes

- remove mesh from proposal db
- move db to conservative state (to prepare for removing tx_pool all together
- add duplicate TX check

## Test Plan

unittest

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
