### PR TITLE
fixed all linting errors in the `eligibility` package. added comments.

### PR DESCRIPTION
**Pull request by y0sher**
## Motivation
clean code

## Changes
fixed all lint errors and added comments

### CODE REVIEW

**Review by almogdepaz — APPROVED** [review]

**Comment by y0sher** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Comment by noamnelke** [comment]
Merged as part of **Consolidated linting (#1958)**

**Pull request closed without merging**
