### PR TITLE
Run systests in CI with Go's race detector

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Go supports running binaries with a race detector. As we approach genesis, we could leverage this to see if there are any race conditions in "live" conditions.

## Changes
Build go-spacemesh docker image for system tests with `-race` flag.

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Comment by dshulyak** [comment]
i am not sure about merging it right now, enabling race detector is not free. lets make sure that tests are completely stable first

**Comment by poszu** [comment]
> i am not sure about merging it right now, enabling race detector is not free. lets make sure that tests are completely stable first

I totally agree, I don't want to degrade CI stability any further.

**Comment by countvonzero** [comment]
in any case, if we choose to do it, we probably should build two binaries, one with race detector and one without for release.

**Comment by poszu** [comment]
Closing as postponed until we have a truly stable CI

**Pull request closed without merging**
