### PR TITLE
[Merged by Bors] - Fixing the CI workflows concurrency after file split

### PR DESCRIPTION
**Pull request by pigmej**
After merging https://github.com/spacemeshos/go-spacemesh/pull/3914 we broke the concurrency checks f.or GH.

This should fix it

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by pigmej** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by piersy** [comment]
@pigmej What's happening with this?

**Comment by pigmej** [comment]
Bors try

**Comment by pigmej** [comment]
> @pigmej What's happening with this?

Should be merged :) thx for rechecking:)

**Comment by fasmat** [comment]
bors try

**Comment by pigmej** [comment]
bors try

**Comment by pigmej** [comment]
bors try

**Comment by pigmej** [comment]
bors try

**Comment by pigmej** [comment]
bors try

**Comment by pigmej** [comment]
bors merge

**Pull request closed without merging**
