### PR TITLE
[Merged by Bors] - mesh: remove dependency on verified layer

### LINKED ISSUE #3744: mesh: block validity updater is not robust
### current approach:
- mesh will apply the hare output `A` for layer `N` to the mesh optimistically when hare terminates
- tortoise verifies layer `N` (earliest at layer `N+1`) and voted against A, supported B, it triggers mesh to set `minUpdatedLayer` to `N`
- when mesh is processing layer `N+2`, it sees the `minUpdatedLayer` is `N`, it discovers that it applied the wrong block, reverts the state to layer `N-1`, and applies `B` for layer `N`.

### problem

1.  updating `minUpdatedLayer` and saving validity to db aren't atomic. if the node is checking for revert between this window, it'll be incorrect. (`UpdateBlockValidity` doesn't hold a lock)
2. if the node exits right after the block validity updated in db, upon restart, mesh will not re-examined if the applied block is correct
3. if tortoise changed its opinion about the same layer within a narrow window of resetting `minUpdatedLayer`, then that 2nd opinion will be ignored

a memory-only solution will not work for 2.

### proposed fix
- add a boolean field `dirty` to blocks table.
- when tortoise verifies layer `N`, it immediately saves block validity for `A` and `B` into database and mark their `dirty` field to true
- when mesh process layer `N+2`
  1. query all the dirty blocks from db and found `A` is invalid and `B` is valid
  2. re-examines the applied block in `N`, reverts to layer `N-1`, and applies `B`
  3. sets `A`'s `dirty` to false iff `A`'s `valid` is still false, and sets `B`'s `dirty` to false iff `B`'s `valid` is still true

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3744

## Changes

- mesh can determine which block to apply without knowing the latest verified layer with the following heuristic:
1. use validity from tortoise updates
2. if 1 fails, get block validity from database
3. if there are no valid blocks, apply empty block for the layer
4. if the block validity is not determined, use the hare output

- remove layer hash that captured all valid blocks in the layer. this field is unused. removing it so we don't need to add code to update layer hash when block validity changes.

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
