### PR TITLE
[Merged by Bors] - Autoscale post verifying workers

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Verifying POST proofs is CPU-intensive. By default, it uses 3/4 CPU cores. It is a problem during the cycle gap for the nodes that take longer to generate the POST proof than the others - new ATXs start to drop in and verifying them fights for CPU with the proving process. In such a situation, proving is more important so sacrificing ATX verification speed is an acceptable tradeoff. 

## Changes
Added a way to scale the number of workers that verify POST proofs (in incoming ATXs) up and down.

There is an auto scaler that reacts to POST events (started/finished) by scaling the number of workers down/up respectively.

The minimum and maximum number of workers is configurable with `smeshing-opts-verifying-min-workers` and `smeshing-opts-verifying-workers` respectively.

## Test Plan
Added unit tests.

## TODO
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Review by dshulyak — APPROVED** [review]
maybe add a prometheus gauge with posts that are waiting to be verified?

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
