### PR TITLE
[Merged by Bors] - Update poet image for system tests

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Updates the PoET image in system tests

## Changes
Update makefile

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
sorry i accidentally typed :)

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
> sorry i accidentally typed :)

would have been OK here 🙂

**Pull request closed without merging**
