### PR TITLE
[Merged by Bors] - Require golang >= 1.15

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Golang 1.15 has some [nice features](https://golang.org/doc/go1.15) such as `testing.TempDir`.

## Changes
This PR updates CI and scripts to require go >= 1.15.

## Test Plan
N/A

## TODO

- [x] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by dshulyak** [comment]
@lrettig any reason not to go for 1.16?

**Comment by noamnelke** [comment]
> any reason not to go for 1.16?

In general, we want to support older versions, as long as we don't use features from the newer version. This is not to say that you can't use newer versions, or that we shouldn't support those, too. That's why #2475 is a good idea.

**Review by noamnelke — APPROVED** [review]

**Comment by dshulyak** [comment]
> In general, we want to support older versions, as long as we don't use features from the newer version. This is not to say that you can't use newer versions, or that we shouldn't support those, too. That's why #2475 is a good idea.

I don't understand why, to be honest. It is not like it is hard to update golang locally. And there are always improvements/fixes under the hood, even if those are not new APIs. For instance, this is a very useful change for monitoring (among other changes in [runtime](https://golang.org/doc/go1.16#runtime)):

```
On Linux, the runtime now defaults to releasing memory to the operating system promptly (using MADV_DONTNEED), rather than lazily when the operating system is under memory pressure (using MADV_FREE). This means process-level memory statistics like RSS will more accurately reflect the amount of physical memory being used by Go processes. Systems that are currently using GODEBUG=madvdontneed=1 to improve memory monitoring behavior no longer need to set this environment variable. 
```

**Comment by noamnelke** [comment]
@dshulyak the improvement you mention really seems useful and we should therefore upgrade to Go 1.16 in our testnet infra, but it doesn't depend on us requiring it... If the code works on 1.15, that should be the minimum.

While we don't see that many contributions from the community, we're still an open source project and we don't want to force developers to upgrade their Go for no reason, other than "a newer version exists".

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
