### PR TITLE
[Merged by Bors] - Bring back different node weights in app test

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Nodes in app test used to have exponentially different weights. This was removed in #2149, and all nodes currently have the same weight. The test is more realistic if nodes have very different weights.

## Changes
- add back differing weights

## Test Plan
N/A, existing app tests should pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by lrettig** [comment]
bors try

**Review by moshababo — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merg

**Comment by lrettig** [comment]
bors merg

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
