### PR TITLE
[Merged by Bors] - tortoise: use rlock for read-only methods and meter store

### PR DESCRIPTION
**Pull request by dshulyak**
should enable parallel ballot decoding

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]
curious what profiling data you had that trigger this change.

**Comment by dshulyak** [comment]
> curious what profiling data you had that trigger this change.

i didn't profile. this is just a right thing to do. this is on critical code path, and there is some amount of computation (hashing, decoding votes) so holding mutex is a mistake

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
https://github.com/spacemeshos/go-spacemesh/issues/4367

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
