### PR TITLE
[Merged by Bors] - Remove timestamp

### LINKED ISSUE #2225: Remove timestamp field from block header
## Description
The block header contains a `Timestamp` field, which is set, but never read.

It’s problematic to use it anywhere since it’s un-vetted, one can plaster any timestamp that serves them onto anything.
Since we’re not doing anything with this field we may as well call it “arbitrary 8 bytes that the miner can fill with whatever they please”.

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/f76c8b99427a4a9f559da87fced6cf5aa3219266/common/types/block.go#L124-L133

### PR DESCRIPTION
**Pull request by noamnelke**
## Motivation
Closes #2225 (obsoletes #2231)

## Changes
Remove `Timestamp` field from the `BlockHeader` struct.

## Test Plan
Unit tests have been updated and all pass consistently. System tests should be unaffected and will be run.

## DevOps Notes
- [x] Does this code require configuration changes? ❌ 
- [x] Does this code affect public APIs? ❌ 
- [x] Does this code assume a new version of external services (PoET, elasticsearch, etc.) ❌ 
- [x] Does this code make changes to log messages that our monitoring infrastructure may rely on? ❌

### CODE REVIEW

**Comment by noamnelke** [comment]
bors try

**Comment by noamnelke** [comment]
@antonlerner weird behavior from Github actions - it reported `ci-stage1` as both skipped and passing and didn't report `ci-stage2` at all. All test passed, though - so ignore the "failed" bors try.

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Review by antonlerner — APPROVED** [review]

**Comment by noamnelke** [comment]
bors merge

**Pull request closed without merging**
