### PR TITLE
[Merged by Bors] - logs, grpc: integrate zap logger middleware

### PR DESCRIPTION
**Pull request by dshulyak**
it allows to collect logs like:

```
boot-0 finished streaming call with code Unknown method=LayerStream service=spacemesh.v1.MeshService error=send to stream: rpc error: code = Canceled desc = context canceled
```

### CODE REVIEW

**Review by nkryuchkov — APPROVED** [review]

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
