### PR TITLE
[Merged by Bors] - miner: only record tortoise beacon in first block of epoch

### LINKED ISSUE #2809: beacon sync: record beacon in first block of epoch and use it to do syntactic validation
## Description

currently beacon value is recorded in every block as eligibility proof. 

in order to prevent miners from changing tortoise beacon value during an epoch, we want to record tortoise beacon in the first block the miner generate.

we will use this beacon value to do syntactic validation on the block upon receiving the block from the network.

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #2809 

## Changes

- remove tortoise beacon value from block eligibility proof
- record tortoise beacon in the first block of epoch so miners cannot change it mid-way through the epoch

## Test Plan

unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
> ## try
> Build failed:
> 
> * [ci-stage2](https://github.com/spacemeshos/go-spacemesh/runs/3705754535)

same issue as discussed in https://spacemesh.slack.com/archives/C01BBB2U64U/p1630336484017700

**Comment by countvonzero** [comment]
bors try

**Review by nkryuchkov — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
