### PR TITLE
[Merged by Bors] - Remove dependency on go.uber.org/atomic

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Removing dependency that is not really required.

## Changes
-  removed `go.uber.org/atomic`
- changed usages to `sync/atomic`

Regarding `syncedTargetTime atomic.Time` -> `time.Time`, I looked over the code, and I believe this variable is accessed from a single thread and doesn't need to be atomic. But please double-check :pray:.

It's used in the following way:

`App::startServices` -> `Syncer::Start/s.syncOnce.Do` -> spawned goroutine (**only once**) -> loop -> `Syncer::synchronize` -> `Syncer::setStateAfterSync` -> read & write

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
I also don't see `syncedTargetTime` being accessed concurrently, maybe this was the case some time ago but was refactored since then? `time.Time` should be OK as its type.

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors cancel

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
