### PR TITLE
[Merged by Bors] - Update default hare params

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
As discussed on today's R&D call. These are reasonable default params. Per @tal-m, we want hare iterations to be 40-50 in normal network scenarios to meet our security assumptions.

## Changes
- change `RoundDuration` (`hare-round-duration-sec`) to 10sec
- change `LimitIterations` (`hare-limit-iterations`) to 50 by default

## Test Plan
no new tests needed

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan

### CODE REVIEW

**Comment by antonlerner** [comment]
I think since we've had another conversation and hare max iterations has changed to 5, but maybe this is the more robust setting we want as default now. 
if you decide to discard this change thats ok as well, just close this PR

**Comment by lrettig** [comment]
> I think since we've had another conversation and hare max iterations has changed to 5, but maybe this is the more robust setting we want as default now.

Are you referring to the testnet? Or target mainnet params? I don't recall finalizing this number yet, but 50 seems a lot more reasonable than 1000, which is way too many. (Tal indicated that we need 40-50 in order to satisfy our security assumptions.)

Also, just to be clear, this is not `max-concurrent` consensus processes. This is the `max-iterations` for each CP.

**Comment by antonlerner** [comment]
> > I think since we've had another conversation and hare max iterations has changed to 5, but maybe this is the more robust setting we want as default now.
> 
> Are you referring to the testnet? Or target mainnet params? I don't recall finalizing this number yet, but 50 seems a lot more reasonable than 1000, which is way too many. (Tal indicated that we need 40-50 in order to satisfy our security assumptions.)
> 
> Also, just to be clear, this is not `max-concurrent` consensus processes. This is the `max-iterations` for each CP.

Ok so it looks good, maybe use named parameters for this struct, but you can merge it as is...

**Comment by lrettig** [comment]
@antonlerner this should be good to go, but I can't bors merge until you approve it :) thanks!

**Comment by lrettig** [comment]
bors try

**Review by antonlerner — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
