### PR TITLE
[Merged by Bors] - increase cycle gap to 30s for system tests

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
