### PR TITLE
[Merged by Bors] - Use Exit Code to Find Tests Status

### PR DESCRIPTION
**Pull request by web3rover**
This PR fixes these two bugs:

1. Uses exit code of pod instead of status of pod to find out if the tests failed. 
2. `bors merge` should fail if the new system tests fail

### CODE REVIEW

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Review by dshulyak — APPROVED** [review]

**Comment by web3rover** [comment]
bors merge

**Comment by web3rover** [comment]
bors merge

**Pull request closed without merging**
