### PR TITLE
[Merged by Bors] - p2p roundtrip unit test fix

### PR DESCRIPTION
**Pull request by y0sher**
## Motivation
The test was failing occasionally and was pointed to me by @valar999   
## Changes
the ffunction  is now able to check a udp port and request specific port

### CODE REVIEW

**Review by valar999 — APPROVED** [review]

**Comment by y0sher** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Comment by AmitShaul** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Pull request closed without merging**
