### PR TITLE
[Merged by Bors] - Limit size of ActiveSet in ballot encoding

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

Don't allow a ballot to contain `ActiveSet` `ATXID`s. They are immediately discarded after receiving them but other nodes can still send ballots with a list of ATXIDs attached that is unnecessarily downloaded and decoded before being deleted.

## Description

The limit of the slice is changed to 1 (zero isn't allowed by `go-scale`). So any incoming ballot with more than 1 referenced ATX ID will be considered invalid.

Up until now the node has always deleted the `ActiveSet` before storing the encoded blob in the DB. To be sure I checked on my local node as well and it didn't have any ballots with `ActiveSet` containing ATXIDs, so this is safe to do.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
