### PR TITLE
[Merged by Bors] - systest: fix broken selectors for chaos-mesh

### PR DESCRIPTION
**Pull request by dshulyak**
they got broken when i switched systest to use deployment mode, as now pod name is not equal to its identity.

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
need to wait with this fix. partition tests will be at best very flaky, but likely will not even work

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
