### PR TITLE
[Merged by Bors] - update data structure to prepare for MalfeasanceProof generation

### LINKED ISSUE #3918: malfeasance: update data structs for malfeasance proof
## Description

1st part of https://github.com/spacemeshos/go-spacemesh/issues/3915

### data structure
change ActivationTx, Ballot, and hare.Message with the following guidelines:
- easy verification of MalfeasanceProof without extra data
- minimize size of MalfeasanceProof data as the proof are stored in the mesh forever
(signature over hash of message instead of message itself)
- adhere to rules for network upgrade per https://github.com/spacemeshos/go-spacemesh/issues/3211
- (non-goal) separate data that can be independently verified
(vrfKey signed (eligibility) versus edKey signed (gossip messages)) 

### VRF signature
add eligibility type to the signed VRF message

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3918

## Changes

- update ActivationTx, Ballot, hare.Message to sign a metadata that can later be used in `MalfeasanceProof`
- add eligibility type to beacon/voting/hare vrf message to differentiate different types of eligibility

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
