### PR TITLE
Add layerID to tortoise opinion map

### LINKED ISSUE #2424: Add exception votes against blocks the base block votes for
## Description
In the verifying tortoise, when selecting a base block, a node considers the set of blocks in every layer against the "local opinion" for that layer. It adds exceptions to vote _for_ blocks that are in the local opinion but that the base block doesn't explicitly support, and it adds exceptions to vote _against_ blocks that are in the layer but not in the local opinion (which the base block doesn't already explicitly vote against). However, there's currently a flaw in this logic: if the base block supports a block in a given layer that the node hasn't seen--i.e., it's not in the database for that layer and it's not in the local opinion for the layer--then the node should add an exception vote against that block. There's currently no (efficient) way to do this because the base block's opinion vector is just a single long list of the blockIDs that it supports, not indexed by layer. We probably need a better data structure.

## Affected code

This issue appears in commit hash: 007bdb9629ef16687e206950c0a1565476aef070

Related files (optionally with line numbers): `tortoise/verifying_tortoise.go`

https://github.com/spacemeshos/go-spacemesh/blob/43cfaeec21f889d65e2f3f7a5efcadef4834c434/tortoise/verifying_tortoise.go#L480-L488

### LINKED ISSUE #2719: Tortoise vote encoding data structure
Right now tortoise stores/encodes votes in a matrix of size `windowSize**2 * blocksPerLayer**2`: each block includes votes from blocks going back `windowSize` layers, each of which includes votes going back `windowSize` layers.

It seems that this data structure is too big. See @dshulyak comment here: https://github.com/spacemeshos/go-spacemesh/pull/2683#issuecomment-904322215.

Per @tal-m,

> The data structure I had in mind is a 2D matrix, where each row represents a voting block and each column a content block. Each element of the matrix is the opinion of a voting block about the corresponding content block. The window size comes into play because we don't need to store the detailed opinions about content blocks that are more than `windowSize` layers in the past (for those, we only store our own opinion, which should be identical to the opinion of all the voting blocks we see)

> Regarding optimizations:
> I think the unified content block will be a huge improvement to complexity --- since there is almost always 1 block per layer, the matrix needs to be windowSize*votesPerLayer (votesPerLayer=blocksPerLayer in the previous scheme). So that's a blocksPerLayer factor improvement; if we're currently using 50 blocks per layer, it means that even without any additional optimization, the vote storage should be less than 140MB
> I'm sure there's a lot of optimization we can do in the data structure itself. Are we storing it in bit-packed fields? Are we making use of the fact that most honest votes actually have the same opinion? Etc.

See [this slack thread](https://spacemesh.slack.com/archives/CG91F13C7/p1629850014078200)

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Closes #2719 
Closes #2424
See also #2679

## Changes
Adds layerID to the inner tortoise block opinion map

This allows efficient eviction of opinions of blocks in older layers,
and it allows us to efficiently add votes against blocks the base block
votes for that are missing from the input vector for a layer

## Test Plan
TBD

## TODO

- [x] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by dshulyak** [comment]
it doesn't seem to address the problem in https://github.com/spacemeshos/go-spacemesh/issues/2719, but up to you

**Comment by lrettig** [comment]
> it doesn't seem to address the problem in #2719, but up to you

This is the part that addresses it:

https://github.com/spacemeshos/go-spacemesh/blob/10fee3a5ecae31325e0dd6912e5f0a9ac1a2672d/tortoise/verifying_tortoise.go#L215-L220

**Comment by dshulyak** [comment]
@lrettig what is left to finish in this change? it would be nice to lend it, cause of the memory consumption and it also addresses some of the critical issues from your list. if you don't have time i can finish it

**Comment by lrettig** [comment]
> @lrettig what is left to finish in this change? it would be nice to lend it, cause of the memory consumption and it also addresses some of the critical issues from your list. if you don't have time i can finish it

I think this PR is mostly done. IIRC not all of the existing tortoise tests are passing. So the steps to completion are:

1. resolve merge conflicts
2. get existing tests to pass
3. add new tests - if necessary, not sure it's necessary here since this PR adds no new functionality

**Pull request closed without merging**
