### PR TITLE
[Merged by Bors] - raise max message size to 2 mb

### PR DESCRIPTION
**Pull request by dshulyak**
turns out some hare messages are larger than 200kb 
i don't know if 2mb is enough for 800 cluster, but 200kb is definetely not enough for 200 cluster

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
