### PR TITLE
[Merged by Bors] - Fix trigger for Swagger UI update

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

The trigger for creating the swagger definition should be on push of a tag.

## Description

Fix the trigger for the workflow. I also added `workflow_dispatch` to allow the manual trigger of the workflow.

## Test Plan

- n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
test timeout

bors merge

**Comment by fasmat** [comment]
flaky `Test_Checkpoint`

bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by acud** [comment]
@fasmat I wanna try to get the systest resilience PR in so we could have the timeout set on the workflow through the go test runner to see why it hangs. It could be that some cleanup on a test isn't finishing correctly.

**Comment by acud** [comment]
bors merge

**Pull request closed without merging**
