### PR TITLE
[Merged by Bors] - Get mesh transactions

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Replaces #2535
See https://github.com/spacemeshos/api/issues/153

## Changes
- new MeshTransaction object, extends Transaction and adds BlockID and LayerID references
- Removed WriteTransaction method (it wasn't used anywhere) and was almost duplicate of WriteTransactions
- change in the api. MeshService.AccountMeshDataQuery will now be extended with layerId (see https://github.com/spacemeshos/api/pull/155)

## Test Plan
TBD

## TODO
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by lrettig** [comment]
@dshulyak it looks like some more cleanup is required here - both resolving merge conflicts against develop and also some cleanup after upgrading the API module:

```
> make lint
golint --set_exit_status ./...
go vet ./...
# github.com/spacemeshos/go-spacemesh/cmd/node
cmd/node/multi_node.go:186:63: cannot use smApp.mesh (type *mesh.Mesh) as type "github.com/spacemeshos/go-spacemesh/api".TxAPI in argument to grpcserver.NewGlobalStateService:
        *mesh.Mesh does not implement "github.com/spacemeshos/go-spacemesh/api".TxAPI (missing GetTransaction method)
cmd/node/multi_node.go:187:69: cannot use smApp.mesh (type *mesh.Mesh) as type "github.com/spacemeshos/go-spacemesh/api".TxAPI in argument to grpcserver.NewTransactionService:
        *mesh.Mesh does not implement "github.com/spacemeshos/go-spacemesh/api".TxAPI (missing GetTransaction method)
cmd/node/node.go:773:49: cannot use app.mesh (type *mesh.Mesh) as type "github.com/spacemeshos/go-spacemesh/api".TxAPI in argument to grpcserver.NewDebugService:
        *mesh.Mesh does not implement "github.com/spacemeshos/go-spacemesh/api".TxAPI (missing GetTransaction method)
cmd/node/node.go:779:55: cannot use app.mesh (type *mesh.Mesh) as type "github.com/spacemeshos/go-spacemesh/api".TxAPI in argument to grpcserver.NewGlobalStateService:
        *mesh.Mesh does not implement "github.com/spacemeshos/go-spacemesh/api".TxAPI (missing GetTransaction method)
cmd/node/node.go:782:48: cannot use app.mesh (type *mesh.Mesh) as type "github.com/spacemeshos/go-spacemesh/api".TxAPI in argument to grpcserver.NewMeshService:
        *mesh.Mesh does not implement "github.com/spacemeshos/go-spacemesh/api".TxAPI (missing GetTransaction method)
cmd/node/node.go:785:53: cannot use app.mesh (type *mesh.Mesh) as type "github.com/spacemeshos/go-spacemesh/api".TxAPI in argument to grpcserver.NewNodeService:
        *mesh.Mesh does not implement "github.com/spacemeshos/go-spacemesh/api".TxAPI (missing GetTransaction method)
cmd/node/node.go:791:60: cannot use app.mesh (type *mesh.Mesh) as type "github.com/spacemeshos/go-spacemesh/api".TxAPI in argument to grpcserver.NewTransactionService:
        *mesh.Mesh does not implement "github.com/spacemeshos/go-spacemesh/api".TxAPI (missing GetTransaction method)
# github.com/spacemeshos/go-spacemesh/cmd/node
vet: cmd/node/multi_node.go:186:58: cannot use smApp.mesh (variable of type *mesh.Mesh) as api.TxAPI value in argument to grpcserver.NewGlobalStateService: missing method GetTransaction
make: *** [Makefile:211: lint] Error 2
```

**Comment by lrettig** [comment]
Reopened this with the understanding that this is a temporary fix that will need to be removed/reverted once we roll out API v2 and properly implement tx receipts. See https://github.com/spacemeshos/api/pull/155 for context.

**Review by dshulyak — APPROVED** [review]
was reviewed in original pr

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
latenodes flake

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
