### PR TITLE
[Merged by Bors] - Install git LFS with make install

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Add info about Git LFS to readme

## Changes
Just README.md

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by pigmej — COMMENTED** [review]
We wanted to keep LFS as an option not as mandatory, can we make that also visible in the readme?

Lfs is needed only if one wants to run a full test suite, doesn't it?

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
@pigmej at the moment git LFS is a prerequisite for all tests, since `make test` requires it to be installed.

I can change that if that shouldn't be the case and exclude the tests that need LFS from `make test` and instead move them to their own `make` target?

**Comment by piersy** [comment]
@pigmej @fasmat I'd prefer to keep make test running all the tests, it seems arbitrary to not run some tests because they use large files.

**Comment by pigmej** [comment]
I second @piersy here. My point was only about the readme part. We don't need lfs to BUILD or run go-sm.

**Comment by fasmat** [comment]
So how to proceed? Close this PR without merging?

**Comment by fasmat** [comment]
I would like to move `make lfs` at least to `make install` so it is not called every time we run `make test` (it is only required once).

**Review by dshulyak — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
