### PR TITLE
[Merged by Bors] - Fix dependabot.yml being in the wrong folder

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
dependabot.yml is in the wrong folder (workflows instead of .github)

## Changes
This moves the file to the correct location

## Test Plan
none

## TODO
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by jonZlotnik** [comment]
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#about-the-dependabotyml-file

just adding for the sake of knowing where the instructions are.

**Review by jonZlotnik — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by dshulyak** [comment]
@fasmat i stopped your merge. let me please fix regression

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
