### PR TITLE
[Merged by Bors] - block log tweak

### LINKED ISSUE #1875: "block received" log fields
Need to:
1. change _miner_id_ to _sender_id_ in order to be consistent with all the other messages.
2. make _miner_id_ a short_id.

### PR DESCRIPTION
**Pull request by noamnelke**
## Motivation
Closes #1875 

## Changes
Minor change to the formatting of the `got new block` log.

### CODE REVIEW

**Review by barakshani — APPROVED** [review]

**Review by y0sher — APPROVED** [review]
no changes needed in the tests ?

**Comment by noamnelke** [comment]
> no changes needed in the tests ?

No, this field isn't used in tests.

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Pull request closed without merging**
