### PR TITLE
[Merged by Bors] - api: include layer ID in `AccountMeshDataStream`

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

This PR includes layer ID in transaction streamed by `AccountMeshDataStream`

## Changes

- Add layer ID to `AccountMeshDataStream`

## Test Plan

UT

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [ ] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]
as i remember it was a temporary solution until receipts are implemented, not sure where we are with receipts at this point

**Comment by nkryuchkov** [comment]
@dshulyak As far as I know, with receipts, we are at planning to create a SMIP for them. I'm not sure what you meant by mentioning receipts. Did you mean that we should pass a receipt instead of layer ID, and then extract layer ID, so this PR is a temporary solution?

**Comment by nkryuchkov** [comment]
bors merge

**Comment by dshulyak** [comment]
i meant that once receipts are implemented we won't need to have this workaround (and one that i added before for queries)

**Comment by nkryuchkov** [comment]
@dshulyak I see, thanks

**Pull request closed without merging**
