### PR TITLE
[Merged by Bors] - Do not automatically generate change notes

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Since we track changes manually in `CHANGELOG.md` we do not want to add a generated changelog to our releases

## Changes
- remove auto-generated release notes

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by pigmej — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
