### PR TITLE
[Merged by Bors] - Fix import for github.com/go-llsqlite/crawshaw

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
The library has been renamed from `github.com/go-llsqlite/llsqlite` to `github.com/go-llsqlite/crawshaw`. The old URL links to the new repository.

## Changes
- Update import paths and update dependency to most recent version

## Test Plan
existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
