### PR TITLE
[Merged by Bors] - handle concurrent gossip and fetching of propsal/ballot

### LINKED ISSUE #3367: proposal gossip handling should tolerate ballot/proposal exists error
## Description

when we receive gossip about an object A, we actively fetch data referenced in object A. on the other hand, we also can receive those referenced data via gossip. we should tolerate object exists error whenever make sense.

```
2022-07-16 18:20:43 | {"L":"WARN","T":"2022-07-16T21:20:43.119-0400","N":"a89a2.layerFetcher ","M":"failed to handle data","node_id":"a89a2a3bf33a10feb9d0b7d8925660321de53e017f6f2621fd16ad5bdf7c5c20","module":"layerFetcher","requestId":"00efb5dd-aaab-4726-96c3-2ed043d58577","hint":"ballotDB","hash":"0x17ea2d78955d6fe574d031df1c873a2b6127881a000000000000000000000000","errmsg":"save ballot: insert ballot 17ea2d7895: database: object exists","name":"layerFetcher"}
2022-07-16 18:20:43 | {"L":"WARN","T":"2022-07-16T21:20:43.119-0400","N":"a89a2.proposalListener","M":"ballot data availability check failed","node_id":"a89a2a3bf33a10feb9d0b7d8925660321de53e017f6f2621fd16ad5bdf7c5c20","module":"proposalListener","requestId":"00efb5dd-aaab-4726-96c3-2ed043d58577","errmsg":"fetch ballots: save ballot: insert ballot 17ea2d7895: database: object exists","name":"proposalListener"}
2022-07-16 18:20:43 | {"L":"ERROR","T":"2022-07-16T21:20:43.119-0400","N":"a89a2.proposalListener","M":"ballot syntactically invalid","node_id":"a89a2a3bf33a10feb9d0b7d8925660321de53e017f6f2621fd16ad5bdf7c5c20","module":"proposalListener","requestId":"00efb5dd-aaab-4726-96c3-2ed043d58577","proposal_id":"7f5a59bf66","ballot_id":"fe3006b16a","layer_id":71,"errmsg":"fetch ballots: save ballot: insert ballot 17ea2d7895: database: object exists","name":"proposalListener"}
2022-07-16 18:20:43 | {"L":"WARN","T":"2022-07-16T21:20:43.120-0400","N":"a89a2.proposalListener","M":"failed to process ballot","node_id":"a89a2a3bf33a10feb9d0b7d8925660321de53e017f6f2621fd16ad5bdf7c5c20","module":"proposalListener","requestId":"00efb5dd-aaab-4726-96c3-2ed043d58577","proposal_id":"7f5a59bf66","ballot_id":"fe3006b16a","layer_id":71,"errmsg":"syntactic-check ballot: fetch ballots: save ballot: insert ballot 17ea2d7895: database: object exists","name":"proposalListener"}
2022-07-16 18:20:43 | {"L":"ERROR","T":"2022-07-16T21:20:43.120-0400","N":"a89a2.proposalListener","M":"failed to process proposal gossip","node_id":"a89a2a3bf33a10feb9d0b7d8925660321de53e017f6f2621fd16ad5bdf7c5c20","module":"proposalListener","requestId":"00efb5dd-aaab-4726-96c3-2ed043d58577","errmsg":"syntactic-check ballot: fetch ballots: save ballot: insert ballot 17ea2d7895: database: object exists","name":"proposalListener"}


```

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3367 

## Changes

allow concurrent save for these data

## Test Plan

unit test, systest

### CODE REVIEW

**Comment by evt** [comment]
sorry, I'm probably missing something, but is it a concurrent saving or just skipping duplicates on insert?

**Comment by dshulyak** [comment]
duplicate objects should not be broadcasted again, as it creates infinite spam loop. are you sure that this pr doesn't break this condition?

**Comment by countvonzero** [comment]
> sorry, I'm probably missing something, but is it a concurrent saving or just skipping duplicates on insert?

skipping duplicate on insert is one way to handle concurrent saving. alternatively one can handle the sql.ErrObjectExists error on the call sites, which is what i have changed the PR to do.

**Comment by countvonzero** [comment]
> duplicate objects should not be broadcasted again, as it creates infinite spam loop. are you sure that this pr doesn't break this condition?

i've added more details here https://github.com/spacemeshos/go-spacemesh/issues/3367#issuecomment-1200571597
the errors i saw are due to gossip and sync path concurrently fetching ballots.

i admit that i was over-zealous with the previous sql (on conflict do nothing) approach. i changed the code to handle the error on gossip/sync call site. 

please take another look @dshulyak @evt thank you.

**Comment by countvonzero** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
