### PR TITLE
[Merged by Bors] - Expose message sizes in cmd

### PR DESCRIPTION
**Pull request by pigmej**
Having CMD option would be probably useful also.

also disable flaky Test_multipleCPs and Test_multipleCPsAndIterations

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by pigmej** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merged

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
