### PR TITLE
[Merged by Bors] - tortoise: recompute opinion based on result returned from verifiers

### PR DESCRIPTION
**Pull request by dshulyak**
i wanted to simplify previous approach for some time and recently discovered a bug
that it didn't recompute opinion correctly in all cases

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
