### PR TITLE
[Merged by Bors] - Adding tests for common/types/block.go

### PR DESCRIPTION
**Pull request by hackintoshrao**
## Motivation

 improving the test coverage while I'm dissecting the source code and the architecture.

## Changes

Adding unit tests for a few basic functions in common/types/block.go . This improves the test coverage from 15% to 61%.

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
The added tests look good to me.

Thank you for your contribution 🙂

**Comment by fasmat** [comment]
bors merge

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by hackintoshrao** [comment]
@fasmat : Can you help me understand the CI failure? So that  I could fix it.

**Comment by countvonzero** [comment]
> @fasmat : Can you help me understand the CI failure? So that I could fix it.

@hackintoshrao 
the CI failure is due to a flaky test. bors is currently retrying to merge your PR. i'll make sure this PR is merged. thanks

**Pull request closed without merging**
