### PR TITLE
[Merged by Bors] - fixed docker build & make on mac m1

### PR DESCRIPTION
**Pull request by evt**
## Motivation
`make` & `docker build` don't work on mac m1 cpu. This PR fixes both issues.

## Changes
Changes apply to `Dockerfile` and `Makefile`.

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by evt** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by evt** [comment]
bors try

**Review by moshababo — APPROVED** [review]

**Comment by evt** [comment]
bors merge

**Comment by evt** [comment]
bors merge

**Pull request closed without merging**
