### PR TITLE
[Merged by Bors] - Bump post-rs to 0.7.12

### PR DESCRIPTION
**Pull request by poszu**
## Motivation

Bump post-rs to the latest version [0.7.12](https://github.com/spacemeshos/post-rs/releases/tag/v0.7.12)

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
The `Test_GenerateProof_TLS` broke on Mac. The `openssl` and `rustls` were updated in post-rs, so possibly something changed there. In the test, the post-service cannot connect to the node:

```
[2024-09-11T09:44:07Z DEBUG rustls::client::tls13] Got CertificateRequest CertificateRequestPayloadTls13 { context: , extensions: [Unknown(UnknownExtension { typ: StatusRequest, payload:  }), Unknown(UnknownExtension { typ: SCT, payload:  }), SignatureAlgorithms([RSA_PSS_SHA256, ECDSA_NISTP256_SHA256, ED25519, RSA_PSS_SHA384, RSA_PSS_SHA512, RSA_PKCS1_SHA256, RSA_PKCS1_SHA384, RSA_PKCS1_SHA512, ECDSA_NISTP384_SHA384, ECDSA_NISTP521_SHA512, RSA_PKCS1_SHA1, ECDSA_SHA1_Legacy]), AuthorityNames([DistinguishedName(3062310b300906035504061302494c311230100603550408130953706163656d6573683111300f0603550407130854656c204176697631123010060355040a130953706163656d657368311830160603550403130f63612e73706163656d6573682e696f)])] }
[2024-09-11T09:44:07Z DEBUG rustls::client::common] Client auth requested but no cert/sigscheme available
[2024-09-11T09:44:07Z INFO  post_service::client] could not connect to the node: tonic::transport::Error(Transport, ConnectError(Custom { kind: InvalidData, error: InvalidCertificate(UnknownIssuer) }))
```

It seems that something is wrong with the certificates, but I'm not sure what.

**Comment by fasmat** [comment]
The generated certificates appear to be valid (at least according to Keychain access). I also wasn't able to figure out what exactly doesn't work on mac. `rusttls` is available in version `0.23.13` and we are using `0.23.7`, is it worth to try updating the dependency to see if that fixes the issue?

**Comment by poszu** [comment]
Bors merge

**Pull request closed without merging**
