### PR TITLE
[Merged by Bors] - Validate NumUnits is not increasing between successive ATXs

### LINKED ISSUE #3759: Verify number of PoST space units in ATXs of one identity is not increasing
## Description

As stated in https://github.com/spacemeshos/go-spacemesh/issues/3773#issuecomment-1339597893 when verifying an incoming ATX, we should check if the number of space units reported is the same or less than the number of units of the referenced previous ATX.

This allows smeshers to decrease their allocated PoST size, but not increase it (at the moment) since we cannot guarantee that the POPS-VRF nonce published with their initial ATX fulfils the higher difficulty of a larger PoST allocation.

In the future we can consider allowing a smesher to increase their allocated space again. For this we need:

- https://github.com/spacemeshos/post/issues/90
- Re-validation of nonce against the higher difficulty for a larger allocation
- Scheme to migration from old nonce to new nonce in VRF invocations (i.e. starting with which layer does the new nonce apply?)

## Affected code
Packages `go-spacemesh/activation` and code in the PoST repository.

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Closes https://github.com/spacemeshos/go-spacemesh/issues/3759

## Changes
- the `Handler` in the activation package now validates incoming ATXs not to increase NumUnits between successive ATXs of the same smesher
- Validation is now a self contained service that is spun up during startup and used where needed
  - tests for it are in `validation_test.go` and `nipost_test.go`
  - tests that indirectly tested the validation service in `handler_test.go` and `challenge_verifier_test.go` have been simplified / don't test what the tests for the validation service test directly
- Some naming improvements for types and methods to avoid repetition

## Test Plan
Multiple tests were added for new functionality

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Review by noamnelke — APPROVED** [review]
LGTM

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
