### PR TITLE
[Merged by Bors] - fixed state root loaded to be 0 when running fresh node

### LINKED ISSUE #1763: wrong reward calculation (and incorrect state) during sync when there are invalid blocks
See screenshots:

1. correct behaviour: there are 53 blocks in layer 20, but one of them is contextually invalid (as shown after the Tortoise finishes with layer 22, and pbase becomes 21). Then we calculate rewards given there 52 blocks.

Screen Shot 2020-01-30 at 7 00 09 PM

2. incorrect behaviour: miners sync layer 20, and after running the tortoise they also know that one block is contextually invalid. Nevertheless, calculation of reward takes into account 53 blocks, hence we also get a different state

Screen Shot 2020-01-30 at 6 59 48 PM

### PR DESCRIPTION
**Pull request by antonlerner**
## Motivation
State root needs to be initialized when running fresh node

## Changes
stateRoot is not inited using `IntermediateRoot` when loading 
## Test Plan
added UT to test processor loading with root hash != 0
## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Pull request closed without merging**
