### PR TITLE
[Merged by Bors] - Migrate to scale codec for ballots & proposals 

### PR DESCRIPTION
**Pull request by evt**
## Motivation

Part of #3271 (for ballots & proposals)

## Changes
Applied scale codec to ballots & proposals

## Test Plan

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by evt** [comment]
bors try

**Comment by evt** [comment]
bors try

**Comment by evt** [comment]
bors merge

**Review by dshulyak — APPROVED** [review]

**Comment by evt** [comment]
bors merge

**Pull request closed without merging**
