### PR TITLE
[Merged by Bors] - Simplify scrypt in systests and reduce batch size

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Nodes in systests sporadically hang during POST init. The last message is:
```
initialization: continue looking for a nonce	{"startPosition": 256, "batchSize": 1048576}
```

It hangs because the batch size is big and init is performed on CPU (it should eventually finish, it just takes veeery long). This fix changes the batch size to match `labelsPerUnit` for the fastnet preset (which systests use).

## Changes
- reduce batch size to 128 in the fastnet preset,
- reduce scrypt difficulty to the lowest possible N = 2 in the fastnet preset.

## Test Plan
Existing tests pass

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Failed to build a docker image.

bors merge

**Comment by dshulyak** [comment]
> {"L":"ERROR","T":"2023-09-11T21:44:12.883Z","N":"a8349.post","M":"Proof is invalid: MSB value for index: 9 doesn't satisfy difficulty: 248 > 12 (label: [130, 102, 117, 246, 44, 81, 99, 77, 106, 119, 96, 59, 92, 95, 148, 235])","node_id":"a83497fcdd409b180b56907c292cb15a213021745a5d957e7495d11101d52258","module":"post","module":"post::post_impl","file":"ffi/src/post_impl.rs","line":242}


lots of errors like the one above https://grafana.spacemesh.dev/explore?orgId=1&left=%7B%22datasource%22:%22loki-gke-dev%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22test-xwcg%5C%22%7D%20%7C%3D%20%5C%22ERROR%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-gke-dev%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-12h%22,%22to%22:%22now%22%7D%7D

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
Flaky https://github.com/spacemeshos/go-spacemesh/issues/4171

bors try

**Comment by poszu** [comment]
UT fail seems unrelated (flake?):
```
=== FAIL: hare/eligibility TestCalcEligibilityWithSpaceUnit/large_network (2.55s)
    oracle_test.go:285: diff=80 (10% of committeeSize)
    oracle_test.go:286: 
        	Error Trace:	/Users/runner/work/go-spacemesh/go-spacemesh/hare/eligibility/oracle_test.go:286
        	Error:      	"80" is not less than "80"
        	Test:       	TestCalcEligibilityWithSpaceUnit/large_network
```

bors try

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
Flaky `TestAccountMeshDataStream_comprehensive`

Bors merge

**Pull request closed without merging**
