### PR TITLE
[Merged by Bors] - v2alpha1 node service

### PR DESCRIPTION
**Pull request by kacpersaw**
getting node status:
```
> grpcurl -plaintext -d '{}' 127.0.0.1:9092 spacemesh.v2alpha1.NodeService.Status

{
  "connectedPeers": "111",
  "status": "SYNC_STATUS_SYNCING",
  "latestLayer": 50373,
  "appliedLayer": 50372,
  "processedLayer": 50372,
  "currentLayer": 54315
}

```

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors try

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Pull request closed without merging**
