### PR TITLE
[Merged by Bors] - Adjust file permissions for identity files

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

This fixes default permissions for identity files being 0o644 instead of 0o600. Additionally it adds comments to the post supervisor regarding safety of arguments passed to the post service.

## Description

Only default permissions for identity files have been changed.

## Test Plan

- existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by ivan4th — APPROVED** [review]
It would probably be nice to log a warning if the identity directory already exists and has world-readable permissions, at least on Mac / Unix platforms

**Comment by fasmat** [comment]
> It would probably be nice to log a warning if the identity directory already exists and has world-readable permissions, at least on Mac / Unix platforms

I can add this but checking on Windows imo doesn't make any sense: On windows there are only 2 modes for files: 0666 and 0444 either writable for all users or read-only for all users based on this blog post: https://medium.com/@MichalPristas/go-and-file-perms-on-windows-3c944d55dd44 `os.Mkdir` on windows ignores the `perm` argument completely.

I believe we need to leave the directory writable for the user, so on windows only 0666 makes sense for us. Also the code to warn the user is a bit clumsy:

```go
// EnsureIdentity generates an identity key file in given directory.
func EnsureIdentity(dir string) (crypto.PrivKey, error) {
	// TODO add crc check
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return nil, fmt.Errorf("ensure that directory %s exist: %w", dir, err)
	}

	if runtime.GOOS != "windows" {
		info, err := os.Stat(dir)
		if err != nil {
			return nil, fmt.Errorf("stat %s: %w", dir, err)
		}
		if info.Mode()&0o777 != 0o700 {
			// TODO: instead of global logger pass logger to EnsureIdentity
			log.Warning("identity directory %s has insecure permissions: %s, consider restricting access to user only",
				dir, info.Mode(),
			)
		}
	}
// ...
}
```

and similar for the identity file itself when loading the key. To my knowledge we are not using the p2p key in the node anywhere (besides as a source of randomness) so if the key gets stolen or is deleted the node can just create a new one without any impact to security.

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
