### PR TITLE
[Merged by Bors] - PoST: pass logger through to post-rs

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
This integrates the new logging in `post` (https://github.com/spacemeshos/post/pull/137) into `go-spacemesh`.

## Changes
The logger needs to be passed thorough to some components of `post`.

Do not merge before
- [x] https://github.com/spacemeshos/post-rs/pull/47
- [x] https://github.com/spacemeshos/post/pull/137
- [x] https://github.com/spacemeshos/go-spacemesh/pull/4390

are merged and released

## Test Plan
Existing tests pass.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by poszu — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
