### PR TITLE
[Merged by Bors] - Reset p2p test params

### LINKED ISSUE #2396: P2P test is flaky
## Description
P2P system test fails regularly with an error such as the following:

```
>       assert total_expected_gossip == len(results), err_msg
E       AssertionError: msg_testing: Total gossip messages in ES is not as expected
E         expected 4440, got 3983
E       assert 4440 == 3983
E         -4440
E         +3983
```

I had to reduce the number of test gossip messages from 100 to 75 to get the test to pass. Reducing the number of messages, or pods, or both, allows the test to pass. But it was always set to 100 messages. I also tried increasing the resources for the pods. Adding memory didn't help; adding processors caused errors from k8s.

What I see in kibana after a failed run is that usually a single pod doesn't receive enough gossip messages; all the others are okay. For most pods, the number of messages that peers send it, and the number of messages it reports receiving, are the same. For the failed pod, however, I see a pattern where it just stops printing logs for minutes at a time. Other pods continue to report sending it messages during this time, so that the number of messages sent is much greater than the number of messages reported received in the logs. Here's a recent example:

image
image

## Steps To Reproduce
See #2395

## Expected Behavior
The test should pass. Increasing the number of messages or pods should still work.

## Environment
Please complete the following information:
 - OS: CI (ubuntu latest)
 - Node Version: 55957a811bbcdaf6eb2e215120090434d61e720f (after merging #2323)

## Additional Resources 
Links to recent failures:
- https://github.com/spacemeshos/go-spacemesh/runs/2423571222?check_suite_focus=true
- https://github.com/spacemeshos/go-spacemesh/runs/2422134431?check_suite_focus=true
- https://github.com/spacemeshos/go-spacemesh/runs/2416023213?check_suite_focus=true
- https://github.com/spacemeshos/go-spacemesh/runs/2413815711?check_suite_focus=true

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
I had to slightly lower a parameter to get the p2p test to pass when merging #2323. This sets it back to what it was, and hopefully makes the test less flaky.

Closes #2396

## Changes
Reset param for p2p systest to what it was before

## Test Plan
N/A

## TODO

- [x] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
@AmitShaul it looks like we can reset this param to what it was previously, now that systests are working again - could you approve? Thanks!

**Review by AmitShaul — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
