### PR TITLE
commit go.sum after go mod download with golang 1.16

### PR DESCRIPTION
**Pull request by dshulyak**
## Motivation
Without updated go.sum some tests are failing with missing dependencies, an example of the failure:

```   
node_test.go:577: 
        	Error Trace:	node_test.go:577
        	Error:      	Received unexpected error:
        	            	failed to build poet: go build failed: exit status 1
        	            	stderr: /home/dd/go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20201013202053-99eed195dc2d/config.go:10:2: missing go.sum entry for module providing package github.com/jessevdk/go-flags (imported by github.com/spacemeshos/poet); to add:
        	            		go get github.com/spacemeshos/poet@v0.1.1-0.20201013202053-99eed195dc2d
        	            	
        	Test:       	TestSpacemeshApp_NodeService
```

I suspect it has something to do with older/newer golang versions, I am using `go version go1.16.3 linux/amd64`
## Changes
Execute `go mod download` and save changes to go.sum.

## DevOps Notes
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]
This change is backwards compatible with Go 1.14 👍🏻

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
This was fixed in https://github.com/spacemeshos/go-spacemesh/pull/2401/

**Pull request closed without merging**
