### PR TITLE
[Merged by Bors] - Target go 1.19 with go-spacemesh

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
With Go 1.19 now being > 2 months old and 1.20 being released in ~ 4 months go-spacemesh could be updated to target the most recent go version.

## Changes
 I updated the github actions, go.mod file and REAMDE.md

## Test Plan
Existing tests pass.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by poszu — CHANGES_REQUESTED** [review]
I think that you missed Dockerfiles :)

**Review by countvonzero — APPROVED** [review]

**Comment by fasmat** [comment]
bors try

**Review by poszu — APPROVED** [review]
NIT: Go version in systest/Dockerfile could be pinned too.

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
