### PR TITLE
[Merged by Bors] - Fix merge issue from #1787 that reverted part of #1828

### PR DESCRIPTION
**Pull request by noamnelke**
## Motivation
A merge issue from #1787 reverted part of #1828

## Changes
Skip running tests on `develop` in travis.

### CODE REVIEW

**Review by AmitShaul — APPROVED** [review]

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Pull request closed without merging**
