### PR TITLE
[Merged by Bors] - beacon: handle malicious identity

### LINKED ISSUE #4772: beacon: vote against proposal from malicious identities
## Description
when we have a malfeasance proof for an identity, protocol should vote against its proposals and give it weight 0 in voting.

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation
Closes #4772

## Changes
for malicious identity's 
- proposal: categorized as potentially valid (voting against)
- first vote: accept with weight 0
- following vote: accept with weight 0

malicious identity's weight is not included in the total epoch weight

### CODE REVIEW

**Review by dshulyak — COMMENTED** [review]
doesn't it require grading too? otherwise how we can be sure that malicious identities are seen the same way

**Comment by countvonzero** [comment]
> doesn't it require grading too? otherwise how we can be sure that malicious identities are seen the same way

i specifically asked Tal/Iddo in barcelona. they said it only requires 2 grades going into the protocol. (malicious or not) because this is tortoise style consensus. (i don't fully understand why but tortoise did only use 2 grades).

so i only count identities that are malicious before the protocol starts.

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
