### PR TITLE
[Merged by Bors] - Update CONTRIBUTING.md for correct label

### PR DESCRIPTION
**Pull request by jack17529**
## Motivation
Correct label for funded.

### CODE REVIEW

**Review by lrettig — APPROVED** [review]

**Comment by lrettig** [comment]
Thanks. @avive do you still want to include this link, given that there are currently no open, funded issues?

**Comment by avive** [comment]
I hope we can have more soon :-)

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
