### PR TITLE
[Merged by Bors] - Bump poet to v0.8.8

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Bump to new version

## Test Plan
existing test suites

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Comment by dshulyak** [comment]
is there a way to see what happened in poet? i tried looking at commits but they are not squashed

**Comment by poszu** [comment]
> is there a way to see what happened in poet? i tried looking at commits but they are not squashed

Here's diff between v0.8.7 -> v0.8.8: https://github.com/spacemeshos/poet/compare/v0.8.7...v0.8.8

TLDR, there are 2 changes worth noticing:
- Add more logs and round members metric by @poszu in https://github.com/spacemeshos/poet/pull/338
- Reject conficting challenge registrations by @poszu in https://github.com/spacemeshos/poet/pull/341

Others are bumps + refactor of UTs

**Review by dshulyak — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
