### PR TITLE
[Merged by Bors] - beacon: use big.Int to track if smesher voted in a round

### PR DESCRIPTION
**Pull request by dshulyak**
the mistake was that `limit` parameter is already a number of bits. there was no need to check how much bits were needed to represent limit.

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
