### PR TITLE
[Merged by Bors] - Improve database migrations

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Part of #5206: extend database migrations to optionally include arbitrary code. The goal is to migrate existing data into new formats when plain SQL isn't sufficient.

## Changes
- Migrations for `localsql` still need to be defined in SQL, additionally they can also be defined in Code
- This allows for easy DB migrations when no data needs to be migrated - primarily in tests.
  - So `sql.InMemory()` doesn't need to be passed extra parameters and only applies migrations in SQL to get the right schema without migrating any data.
- Code migrations can be tested against their associated SQL migrations to produce the same schemas (see tests in this PR)
- In the future we can remove the Migrations defined in Code and only leave the SQL migrations.
  - SQL migrations are sufficient for onboarding new nodes
  - Upgrading existing nodes is only possible from the last version where the code migration is present.

Example: all nodes older than `v1.3.0` can be upgraded to `v1.3.0`. We can remove the go migrations created for `v1.3.0` in release `v1.4.0`. Nodes running version `v1.3.0` (or newer) can upgrade without issues to `v1.4.0`. Older nodes first have to upgrade to `v1.3.x` before being able to upgrade to `v1.4.0`.

## Test Plan
- new tests for migrations
- updated existing tests to be compatible

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by poszu** [comment]
>Example: all nodes older than v1.3.0 can be upgraded to v1.3.0. We can remove the go migrations created for v1.3.0 in release v1.4.0. Nodes running version v1.3.0 (or newer) can upgrade without issues to v1.4.0. Older nodes first have to upgrade to v1.3.x before being able to upgrade to v1.4.0.

Upgrading version minor by minor (1.2.x -> 1.3.0-> 1.4.z) probably needs additional support in Smapp. cc @brusherru

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
