### PR TITLE
[Merged by Bors] - Use uint32 to work with network id

### LINKED ISSUE #2113: Increase network ID range
## Description
Right now the `network-id` in the config cannot be larger than 128 since it's stored in `int8`.

We should have a larger range to make it easier to segment into different types of networks, e.g., testnet is `1xx`, devnet `2xx`, local networks `1xxx`, etc.

Also I'm not sure why this is an int rather than uint, since I don't think we ever want it to be negative.

CC @avive @noamnelke @y0sher any thoughts to add here? Any reason not to change this?

## Affected code
https://github.com/spacemeshos/go-spacemesh/blob/b4a7bcdd152d5f4af3da00abbadab2439b9ce90f/cmd/root.go#L81

This issue appears in commit hash: b4a7bcdd152d5f4af3da00abbadab2439b9ce90f

### PR DESCRIPTION
**Pull request by dshulyak**
## Motivation
Int8 is too short and forces reuse of the same ids for testnets.
Closes: https://github.com/spacemeshos/go-spacemesh/issues/2113

## Changes
- NetworkID is stored internally as uint32 instead of int8.
- handshake data will use uint32 instead of int32 for consistency

## Test Plan
Existing unit and system tests.

## TODO
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by antonlerner — APPROVED** [review]

**Review by lrettig — APPROVED** [review]

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
