### PR TITLE
[Merged by Bors] - Bump poet to v0.9.1

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
A new poet version came out

## Changes
bump poet to the latest v0.9.1

## Test Plan
existing tests pass

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]
could you please remove devops notes, they are not used by anyone, from commit message and update changelog?

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Docker push failed in the systests workflow. 

bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
