### PR TITLE
[Merged by Bors] - systest: reduce ballot delay in systest for diff beacon

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

related to #4112

speed up systest partition test recovery

- make the delay configurable with default value of 1 epoch if not set
- set value in the preset configs
- reduce the partition duration from 2 to 1 epoch in test

### CODE REVIEW

**Comment by countvonzero** [comment]
@dshulyak hopefully this will reduce the failure rate for 50-50 test.

**Comment by dshulyak** [comment]
it looks like that it is unconditionally overwritten to number of layers in the epoch

image

**Comment by countvonzero** [comment]
@dshulyak thanks! can you review again. i have
- remove the overwrite of value and make it configurable
- set value in the preset configs
- reduce the partition duration from 2 to 1 epoch in test

**Review by dshulyak — APPROVED** [review]
@countvonzero what do you think about setting it to epoch length if value is zero (and make it zero by default)? it is unlikely will be anything else than epoch length in testnets

**Comment by countvonzero** [comment]
> @countvonzero what do you think about setting it to epoch length if value is zero (and make it zero by default)? it is unlikely will be anything else than epoch length in testnets

sure. make sense. done

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
