### PR TITLE
[Merged by Bors] - remove fixed oracle

### PR DESCRIPTION
**Pull request by poszu**
## Motivation

it's not used anywhere

## Test Plan

n/a
## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by fasmat — APPROVED** [review]
I think this was needed for some test in the previous hare and was forgotten about when we moved to hare3?

**Comment by poszu** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
Bors merge

**Pull request closed without merging**
