### PR TITLE
[Merged by Bors] - Improve logging in ATX Builder

### PR DESCRIPTION
**Pull request by poszu**
## Motivation

Added logs around building a NiPoST challenge to understand its progress better.

## Test Plan

n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
btw. I have a similar PR here: https://github.com/spacemeshos/go-spacemesh/pull/5798

**Comment by poszu** [comment]
> btw. I have a similar PR here: #5798

How about merging changes from it to this PR to avoid running ci twice?

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
> How about merging changes from it to this PR to avoid running ci twice?

cherry-picked the commit

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
