### PR TITLE
[Merged by Bors] - genesis: add final ledger

### PR DESCRIPTION
**Pull request by dshulyak**
see https://github.com/spacemeshos/wiki/wiki/Genesis-ledger

### CODE REVIEW

**Review by pigmej — APPROVED** [review]
That list is identical to https://github.com/spacemeshos/wiki/wiki/Genesis-ledger at the time of writing.

**Comment by dshulyak** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by noamnelke** [comment]
I think there might be one last update missing from the list. I have no way of verifying this, but @tal-m said that @lrettig didn't update one of his keys that needs to change.

**Pull request closed without merging**
