### PR TITLE
[Merged by Bors] - p2p: reduce log to info in p2p tests

### LINKED ISSUE #2736: p2p system test failure in `test_many_gossip_sim`
## Description
when running p2p system tests, this error occasionally fails `test_many_gossip_sim`
```
>       assert total_expected_gossip == len(results), err_msg
E       AssertionError: msg_testing: Total gossip messages in ES is not as expected
E         expected 2580, got 2548
E       assert 2580 == 2548
E         -2580
E         +2548
```

## Steps to reproduce
run p2p system tests

## Environment
Please complete the following information:
 - OS: 
 
 - Node Version: 
 
 - Smapp version (if applicable):

### LINKED ISSUE #2748: Flaky TestBlockBuilder_notSynced
## Description

Not terminated gracefully

### PR DESCRIPTION
**Pull request by dshulyak**
## Motivation

Trying to reduce noise in p2p messages test, to exclude any potential issues related to elk.

closes: https://github.com/spacemeshos/go-spacemesh/issues/2748
closes: https://github.com/spacemeshos/go-spacemesh/issues/2736

## Changes
- log level in cmd/p2p changed to info
- query in test_p2p.py changed to `api_test_gossip: got test gossip message`

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
failed in setup with genesis delta.

bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
deployment in sync test has timed out

bors try

**Comment by dshulyak** [comment]
bors try

**Review by nkryuchkov — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Review by countvonzero — APPROVED** [review]

**Review by antonlerner — APPROVED** [review]

**Comment by dshulyak** [comment]
infra failure. let's see if it is temporary

bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
