### PR TITLE
[Merged by Bors] - Bump poet to v0.9.3

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Bump to the latest version
## Changes
- bumped poet to v0.9.3
- adjusted the code to match the changed poet module structure
- fixed poet client UT (missing PoW)

## Test Plan
existing tests pass

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Unrelated errors in systest:
```
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 102 [running]:
	>  runtime/debug.Stack()
	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/log/log.go:60 +0xcd
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).WithName(0xc0001f3400, ***0x1d72b1a, 0x14***)
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/log/deleg.go:147 +0x45
	>  github.com/go-logr/logr.Logger.WithName(***0x2011c80, 0xc0001f3400***, 0x0***, ***0x1d72b1a?, 0x1d5b189?***)
	>  	/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:336 +0x3d
	>  sigs.k8s.io/controller-runtime/pkg/client.newClient(0x1d01140?, ***0x0, 0xc00011d570, ***0x0, 0x0***, 0x0, ***0x0, 0x0***, 0x0***)
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/client/client.go:122 +0xec
	>  sigs.k8s.io/controller-runtime/pkg/client.New(0x1ff96e0?, ***0x0, 0xc00011d570, ***0x0, 0x0***, 0x0, ***0x0, 0x0***, 0x0***)
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.1/pkg/client/client.go:103 +0x7d
	>  github.com/spacemeshos/go-spacemesh/systest/testcontext.New(0xc000583040, ***0xc00042fa30, 0x1, 0x0?***)
	>  	/build/systest/testcontext/context.go:291 +0x32e
	>  github.com/spacemeshos/go-spacemesh/systest/tests.TestSmeshing(0xc000583040?)
	>  	/build/systest/tests/smeshing_test.go:34 +0xd0
	>  testing.tRunner(0xc000583040, 0x1e63e28)
	>  	/usr/local/go/src/testing/testing.go:1595 +0xff
	>  created by testing.(*T).Run in goroutine 1
	>  	/usr/local/go/src/testing/testing.go:1648 +0x3ad
```

bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
