### PR TITLE
[Merged by Bors] - [systest] Disable scaling post verifiers workers

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
System tests have been very flaky recently after #5354. A 30s CG is too short to process 48 ATXs on one thread in some tests. It results in the own ATX getting stuck in the handler queue and being published late.

Another source of tests failures seems to be graceful shutdown of GRPC streams. Not handling it results in a following error in the test:
```
proposal event for smesher-5: rpc error: code = Unavailable desc = closing transport due to: connection error: desc = "error reading from server: EOF", received prior goaway: code: NO_ERROR, debug data: "graceful_stop"
```

## Changes
- disabled scaling post verifiers worker pool
- added handling a case when the proposals stream is closed on the server side with code `Unavailable`.

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
Bors try

**Comment by poszu** [comment]
Bors try

**Review by dshulyak — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
