### PR TITLE
[Merged by Bors] - Transition `state` package into `svm` package

### LINKED ISSUE #2827: Transition `state` package into `svm` package
- [x] Create `svm` package
- [x] Move `state` package into `svm` package
- [x] Breakout `mempool` into separate package (this is currently the `tx_pool.go` file and matching test)

### PR DESCRIPTION
**Pull request by noamnelke**
## Motivation
Closes #2827

## Changes
Transition `state` package into `svm` package. This is a refactor that should not impact existing functionality.

## Test Plan
Existing unit and system tests.

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by noamnelke** [comment]
bors try

**Comment by noamnelke** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
won't it be cleaner to have a `vm` module instead of `svm`? i guess it doesn't matter much, but  `svm` is a vm that implements a certain interface and there could be many different implementations

**Comment by noamnelke** [comment]
@dshulyak I agree in general, but not on the specifics... As I see it, `SVM` is what I call the interface, while `rust-SVM` is a specific implementation of it. We may write a `C-SVM` one day, but it will also be an implementation of `SVM`. If we strip the `s` it will be just a virtual machine, which is too generic here, IMO.

The `svm` package that I create here is just a wrapper around the actual SVM, which will be the old implementation at first and then replaced with `rust-SVM` (inside the wrapper, without changing its exposed methods).

Do you agree?

**Comment by noamnelke** [comment]
bors merge

**Review by neysofu — APPROVED** [review]
LGTM!

**Comment by dshulyak** [comment]
> I agree in general, but not on the specifics... As I see it, SVM is what I call the interface, while rust-SVM is a specific implementation of it. We may write a C-SVM one day, but it will also be an implementation of SVM. If we strip the s it will be just a virtual machine, which is too generic here, IMO.

i guess this a valid view. i usually look at the whole module name, in this case `spacemeshos/go-spacemesh/vm` doesn't seem generic and not very easy to misunderstand the intention

**Comment by noamnelke** [comment]
@dshulyak Your last point convinced me. I looked it up and it looks like the Ethereum devs also agree with you - in geth the EVM package is just called `vm`. We can rename it in a following PR.

**Pull request closed without merging**
