### PR TITLE
[Merged by Bors] - invalid miner cache

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
this is technically not needed anymore, but code is incomplete without this change. i will merge it and remove it later with a refactoring  that removes LegacyLayer alltogether

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
arm builder doesn't work

> curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to objects.githubusercontent.com:443 
make: *** [Makefile-libs.Inc:81: /home/gh-runner/actions-runner/_work/go-spacemesh/go-spacemesh/build/profiler] Error 35

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
