### PR TITLE
[Merged by Bors] - Timeout increased to prevent race

### PR DESCRIPTION
**Pull request by sudachen**
## Motivation

Workaround to prevent race on handling layer in Test_multipleCPs causing panic

## Changes

Increased timeout between layers 

## Test Plan
- Unit tests

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]

**Comment by sudachen** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by sudachen** [comment]
bors merge

**Comment by sudachen** [comment]
bors merge

**Pull request closed without merging**
