### PR TITLE
[Merged by Bors] - p2p: add configuration for direct peers

### PR DESCRIPTION
**Pull request by dshulyak**
see rendered readme for p2p module https://github.com/spacemeshos/go-spacemesh/blob/7066febb821b82f035ab0d539ba95dfad4e8b347/p2p/README.md

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
