### PR TITLE
[Merged by Bors] - tortoise: switch back into verifying only if same layers can be verified

### LINKED ISSUE #4503: tortoise: switch into verifying mode only when layers up to the last one can be verified
in the implementation we will switch from full into verifying if any layer crossed pessimistic threshold. it doesn't cause any major issues, but creates a spam in logs and forces consumers to do more work, as tortoise will report same consensus results multiple times.

to avoid this, tortoise should be more pessimistic about when it switches back into verifying mode. check that all layers confirmed in full mode were confirmed in verifying too and only then switch

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/go-spacemesh/issues/4503
depends on: https://github.com/spacemeshos/go-spacemesh/pull/4438

in the implementation we will switch from full into verifying if any layer crossed pessimistic threshold. it doesn't cause any major issues, but creates a spam in logs and forces tortoise users to do more work, as tortoise will report same consensus results multiple times.

to avoid this, tortoise should be more pessimistic about when it switches back into verifying mode. check that all layers confirmed in full mode were confirmed in verifying too and only then switch

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
