### PR TITLE
Add new transactions abstraction (Smip23)

### PR DESCRIPTION
**Pull request by sudachen**
## Motivation

This PR adds new transactions abstraction allowing to operate with different classes of transactions.

## Changes

1) Added 3 new types of transactions with 2 signature schemes each. Also, there is one type for the old transactions layout.
2) Client code is adoped to use the new transactions abstraction.

## TODO

- [ ] Add NetworkID calculation
- [x] Sync with current development branch
- [x] Add documentation comments

### CODE REVIEW

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by sudachen** [comment]
bors try

**Comment by nkryuchkov** [comment]
@sudachen Do we still need this PR? I see that there's a lot of merge conflicts. Do you think it's worth fixing them? Was this PR ready for merging before conflicts appeared? Are fixing merge conflicts and review approval the only blockers?

**Comment by sudachen** [comment]
It contains two part. The first one is the transaction abstraction and high possible can be reused, the second is a bunch of changes in code to make it use transaction interface instead the old transaction implementation. So I think this PR cans be simple closed. But please keep the branch.

**Pull request closed without merging**
