### PR TITLE
[Merged by Bors] - beacon: ignore votes on proposals unknown to the node

### LINKED ISSUE #3102: beacon: ignore votes on proposals node doesn't have
## Description

slack conversation
```
kimmy lin:
@Tal
want to double-check something with you for tortoise beacon.
in the proposal phase, we received a set of proposals.
in the first voting round, we receive valid and potential valid proposals from each smesher
however, we did NOT check if the valid/potentially valid proposals received in the first voting round to be a subset of the proposals received in the proposal phase. is that ok?

Tal Moran  23:19
@kimmy Yes, that's ok. The list of proposals each smesher sends is part of the vote encoding for the subsequent rounds. We don't need to check their validity, but we ignore votes for proposals that are not on our list.
```

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3102

## Changes

ignore votes on proposals that are not in the node's initial proposals received during the proposal phase

this change can potentially cause disagreement on beacon value if network delay proves to be more significant than the grace period. we need empirical data to tune the grace period param to make sure miners agree on beacon value

## Test Plan

unittest, system tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Review by nkryuchkov — APPROVED** [review]

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
