### PR TITLE
Convert LayerID and EpochID to uint32

### LINKED ISSUE #2082: LayerID uint64 -> uint32
See https://github.com/spacemeshos/api/issues/88 for background. With 32 bits and five minute layers we get nearly 41,000 years. Even if the layer time were to speed up to one minute, it would still be enough for ~8100 years.

For the record here is the math:

```
# max_uint32 divided by number of five-minute layers per year
In [3]: 2**32 / (60 / 5. * 24 * 365.25)
Out[3]: 40829.79025020914

# max_uint32 divided by number of minutes per year
In [4]: 2**32 / (60 * 24 * 365.25)
Out[4]: 8165.958050041828
```

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Closes #2082 

## Changes
- Convert LayerID and EpochID to uint32

## Test Plan
No new tests required, existing tests should suffice. No functionality was added.

## TODO
- [x] Do a more thorough grep for `uint64`

### CODE REVIEW

**Comment by y0sher** [comment]
is this something we discussed in research meetings? I remember we decided these will be `uint64`. if I'm missing something please add some context to this pr.

**Comment by avive** [comment]
> is this something we discussed in research meetings? I remember we decided these will be `uint64`. if I'm missing something please add some context to this pr.

Please see https://github.com/spacemeshos/api/issues/88

**Comment by lrettig** [comment]
Confirmed that remaining uint64 references refer to things such as nonce, balance, disk space, tick count, sequence number, etc. and not layer or epoch. Might need to double-check this math ([diff](https://github.com/spacemeshos/go-spacemesh/pull/2134/commits/f3d37caee2b7345ef6c923bbfdc452fef60aea99#diff-b4762dde5e536ae4196cf8afd991f6b8)):

https://github.com/spacemeshos/go-spacemesh/blob/f3d37caee2b7345ef6c923bbfdc452fef60aea99/miner/blockoracle.go#L205-L211

And this which has not changed:

https://github.com/spacemeshos/go-spacemesh/blob/f3d37caee2b7345ef6c923bbfdc452fef60aea99/miner/epochbeacon.go#L11-L17

I'm assuming we don't want to change the size of the beacon values.

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by antonlerner** [comment]
closed due to inactivity and because a lot has changed since probabaly

**Comment by lrettig** [comment]
This is still useful and important, let's keep this open. I will try to refresh it. Pretty sure this is mostly done.

**Comment by moshababo** [comment]
@antonlerner it can be re-assigned to someone else.

**Comment by noamnelke** [comment]
Closing this in favor of https://github.com/spacemeshos/go-spacemesh/pull/2489

@lrettig that PR will convert `LayerID` to `uint32`. Do you think it's important to also handle `EpochID`? If you do - let's create a separate issue for it (unless @dshulyak wants to take care of that in the same PR).

**Pull request closed without merging**
