### PR TITLE
feat: hare to use shorter hashes on preround

### LINKED ISSUE #5606: compact encoding for hare preround message
hare preround message includes every proposal that is eligible for rewards. it references it by specifying first 20 bytes of blake3 hash of the full proposal. with 50 proposals per layer the message is around 1KB, not including vrf and regular signature. with 500 proposals per layer it grows to 10KB per preround message. number of preround messages are bounded to the size of hare committee, right now we are running it with 400 participants, but aim to increase it to 800.

with 10KB per preround message every peer has to download 4MB of unique data within 12s, in practice it downloads some duplicates because of the redundancy on gossip layer. the other part of the problem is that it scales with number of connections that node maintains. if node has 1000 connections, it can expect to be requested 4GB of data within 12s. eventually, if not now, this will be unsustainable to keep such number of connections.

#### compact encoding protocol

the reason why we keep 20 bytes is to prevent collisions, as otherwise votes are ambiguous and cannot be counted properly. moreover adversary can create collisions intentionally if identifier will be kept short to 2 or 4 bytes.

the proposal is to introduce compact encoding that is not open to dos attack, maintain low rate of accidental collisions, and in case of collisions provide a safe fallback.  it can reduce traffic either x5 or x10, depending on the option that we choose.

protocol for encoder:
- construct preround message with a collection of full proposal identifiers. proposals should be sorted in lexicographic order
- sign message with full proposal identifier 
- replace each proposal identifier with an output from `short_hash(vrf, proposal_identifier)`

`short_hash` is a cheap hashing function, such as siphash or halfsiphash https://github.com/veorq/SipHash/blob/master/halfsiphash.c.
we may decide how much we want to truncate output.

protocol for decoder:
- receive a message, verify a vrf
- for all proposals that you have locally compute `short_hash(vrf, proposal_identifer)`
- if received message votes several times on the same proposal
- validate signature on reconstruct message

we need to handle two edge cases due to possible collisions:
- message includes multiple short identical id. in this case we decode them in lexicographic order. so for example if we received  short ids [4,4], and we have locally proposals 0xa, and 0xb, we decode 0xa and then 0xb.
- message includes single id, but locally we have collisions. in such case we have to verify signatures for different proposal and find if one of the matches.

### PR DESCRIPTION
**Pull request by acud**
## Motivation

Current `hare` prerounds use 20-byte `blake3` hashes of the proposals. This PR aims to reduce the message size by adopting the changes described in #5606 
## Description

Adopts the changes in the aforementioned ticket by adding a field onto the `Value` type which encodes the shorter checksums. This field is to be used only on the preround. This approach saves the overhead of encoding `Proposals` as different types (either `Hash20` or a 2-byte hash) - this will either require self-describing encoding, or a new field describing the length of the data in each proposal.

_IN PROGRESS, PLEASE DO NOT GIVE IT A THOROUGH REVIEW, GENERAL COMMENTS ON DESIGN DECISIONS WELCOME_

Closes #5606 

## Test Plan

- unit tests
- running it on a testnet that would fork to choose the new protocol version at a given epoch

ref https://github.com/spacemeshos/go-spacemesh/pull/5256 https://github.com/spacemeshos/go-spacemesh/pull/4765

## TODO

- [x] unit tests
- [x] change to 3 or 4 byte encoding to prevent collisions
- [ ] error handling from `reconstructProposals` could probably be improved to just fallback into a full proposals list exchange instead of returning the error
- [ ] add cmd configuration (for switchover epoch)
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by poszu** [comment]
@acud I understand, that files in `hare4/` are copies of files in `hare3/` with required changes. Please make it in two+ commits to make the review easier.
1. commit copying files
2. commits with changes

This way, the reviewer can easily focus on the diff between hare3 and hare4.

**Comment by acud** [comment]
Done @poszu. I'm gonna keep on squashing the commits into the second commit until this becomes reviewable. OK?

**Comment by ivan4th** [comment]
It would probably make sense to mark this PR as a draft until it's ready for review?

**Comment by acud** [comment]
bors try

**Comment by acud** [comment]
closing in favor of #6129

**Pull request closed without merging**
