### PR TITLE
[Merged by Bors] - Cleanup log fields

### PR DESCRIPTION
**Pull request by noamnelke**
## Motivation
Reduce confusion around how to use `LoggableField`s

## Changes
- Introduce `log.FieldNamed()` for cases where a field's default name isn't clear, or more than one field of same type are logged.
- Replace all usages of the old-style `log.<type>` and replace with bare logging.
- Remove old-style methods.

## Test Plan
Unit + system tests.

### CODE REVIEW

**Comment by noamnelke** [comment]
bors try

**Review by y0sher — APPROVED** [review]
cool, that'll save some  headaches.

**Comment by noamnelke** [comment]
bors try

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
