### PR TITLE
[Merged by Bors] - Fixup docker image name for systests triggered from Actions

### PR DESCRIPTION
**Pull request by poszu**
The systests triggered manually via a butting in _Actions_ don't work because of docker image name mismatch (`make dockerbuild-go` uses short commit hash for image tag on staging and trying).

Now the docker image tag is passed to systests (via smesher_image variable) explicitly.

Additionally removed doubled dockerpush.

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
