### PR TITLE
[Merged by Bors] - Fix db-allow-schema-drift handling

### PR DESCRIPTION
**Pull request by ivan4th**
-------

## Motivation

`db-allow-schema-drift` stopped working after adding separate conn pool for the API

## Description

Fix schema drift handling for the API db connection pool

## Test Plan

Verify on a mainnet node

### CODE REVIEW

**Review by jellonek — APPROVED** [review]

**Comment by jellonek** [comment]
tbh. few lines above db was already checked for schema difference, so maybe we should there even use `WithNoCheckSchemaDrift`?

**Comment by ivan4th** [comment]
@jellonek makes sense, it's actually enough to just ignore schema drift for the api conn pool

**Review by jellonek — APPROVED** [review]

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
bors cancel

**Comment by ivan4th** [comment]
bors merge

**Review by fasmat — APPROVED** [review]

**Pull request closed without merging**
