### PR TITLE
[Merged by Bors] - gcloud version change

### PR DESCRIPTION
**Pull request by andres-spacemesh**
## Motivation

Closes #

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
Any particular reason as why we are using `v0` instead of `v1` of both tools?

**Comment by pigmej** [comment]
> Any particular reason as why we are using `v0` instead of `v1`?

Our pipelines are broken with v1 currently.

**Comment by fasmat** [comment]
@pigmej Then we just need to make sure to decline the PR dependabot creates in the next few hours for updating these actions.

**Review by pigmej — APPROVED** [review]

**Review by fasmat — APPROVED** [review]

**Comment by pigmej** [comment]
> @pigmej Then we just need to make sure to decline the PR dependabot creates in the next few hours for updating these actions.

Yeah...

And work on fixing them soon :)

**Comment by andres-spacemesh** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Pull request closed without merging**
