### PR TITLE
[Merged by Bors] - Fix response data slice too small

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

The response msg object needs to be increased in size to allow 8.0 Mio ATXs to be processed by the node

## Description

Bring `Response.Data` in line with other objects to be able to handle 8.0 Mio ATXs

## Test Plan

- n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by pigmej — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Review by ivan4th — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
