### PR TITLE
[Merged by Bors] - api: v2alpha1 TransactionList: Fix typo in EndLayer filter

### PR DESCRIPTION
**Pull request by kacpersaw**
EndLayer filter used Address field instead of Layer to prepare SQL query.

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Pull request closed without merging**
