### PR TITLE
[Merged by Bors] - lower interval so that test doesn't stuck waiting 4h

### LINKED ISSUE #5681: Flaky test: `TestSyncer/terminate_empty_epoch`
## Description

```
=== FAIL: syncer/atxsync  (0.00s)
panic: test timed out after 5m0s
running tests:
	TestSyncer (5m0s)
	TestSyncer/terminate_empty_epoch (5m0s)
```

Example run: https://github.com/spacemeshos/go-spacemesh/actions/runs/8234003897/job/22514818138
another run: https://github.com/spacemeshos/go-spacemesh/actions/runs/8234987365/job/22518069458

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/go-spacemesh/issues/5681

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors cancel

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
