### PR TITLE
check tx order for block syntactic validity

### LINKED ISSUE #3234: block: consider block syntactically invalid when txs are out of order
## Description

a follow up on #3036, make a block syntactically invalid when the transactions are out of order (nonce gap within the same account)
so honest nodes automatically vote against it.

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3234

## Changes

consider a block syntactic invalid when the txs are not in nonce order within the same account

## Test Plan

unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
> Build failed:
> 
> * [ci-stage2](https://github.com/spacemeshos/go-spacemesh/runs/7004950771?check_suite_focus=true)

hare unittest timed out

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
> Build failed:
> 
> * [ci-stage2](https://github.com/spacemeshos/go-spacemesh/runs/7007715847?check_suite_focus=true)

https://github.com/spacemeshos/go-spacemesh/issues/3291

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
this change is not feasible for now. currently txs in a synced block is saved to db without its header parsed.

**Pull request closed without merging**
