### PR TITLE
[Merged by Bors] - remove flag tortoise-beacon-wait-after-epoch-start

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

clean up unused flag

## Changes

remove --tortoise-beacon-wait-after-epoch-start

## Test Plan

unit test

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by nkryuchkov — APPROVED** [review]
It still exists in https://github.com/spacemeshos/go-spacemesh/blob/clean-up-beacon-flag/.env#L61-L62

**Comment by countvonzero** [comment]
> It still exists in https://github.com/spacemeshos/go-spacemesh/blob/clean-up-beacon-flag/.env#L61-L62

thanks. done

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
