### PR TITLE
[Merged by Bors] - bump post-rs to v0.7.11

### PR DESCRIPTION
**Pull request by poszu**
## Motivation

Update to the latest release. Node: updated the post-rs binary name to post-service.

## Test Plan

existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
Do we need to update `spacemeshos/post` as well?

**Comment by poszu** [comment]
drafted, as the release is broken for windows :/

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
