### PR TITLE
[Merged by Bors] - Fix p2p version comparison test and logic

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
See #2168 

## Changes
- Fix version comparison logic

## Test Plan
- Added regression test for logic

## TODO
- [x] Discuss and decide what to do about `test_diff_client_ver`: we probably want to try connecting an _older_ node rather than a _newer_ one here

### CODE REVIEW

**Comment by lrettig** [comment]
> Make it possible to successfully run this test locally, don't override clientv2 docker image name

Addressed in #2131 in 5374ea0ca0f71391c9f6cf10789c1193df93bb0e

> decide what to do about the case where clientv2 image needs a different set of command line flags

Most of the places these are used in the tests, they should be overridden. The only exception I've found is the p2p test. Need to discuss with everyone else how we want this test to work, but I suspect the answer here will be, manually create and push a docker image, set it in the config file, and set `noreplace`.

**Comment by y0sher** [comment]
I don't see a problem with the latter solution.. this runs only a thin p2p node so it shouldn't require a lot of changes are rebuilding, though if we don't do an automatic process it's worth to somehow mention this in the tests or code so if someone changes something she will notice that the dockerimage should be updated.

**Comment by lrettig** [comment]
> I don't see a problem with the latter solution.. this runs only a thin p2p node so it shouldn't require a lot of changes are rebuilding, though if we don't do an automatic process it's worth to somehow mention this in the tests or code so if someone changes something she will notice that the dockerimage should be updated.

Agree on your point about documenting this, I can do that as part of this PR. Regarding the core logic of the [test in question](https://github.com/spacemeshos/go-spacemesh/blob/edb8baedd9fe84b10c114e6b033b9a843044c295/tests/p2p/test_p2p.py#L314), do you agree that it should be testing that a bootstrap server running a _newer_ client version (say, `v0.2.0`) should refuse to allow a client running an _older_ version (say, `v0.1.0`) to connect to it? If so, I think we're on the same page here, and I can sort out the code. Thanks!

**Comment by lrettig** [comment]
Confirmed on R&D call today that this is the goal - in the long term we want a more robust design here (e.g., versioning individual protocols) but in the short term we want nodes running newer versions of the protocol to refuse to bootstrap nodes running older versions. I'll make the necessary changes here and then mark this PR as ready to review and merge.

**Comment by lrettig** [comment]
I reduced the scope of this PR to one simple fix of the logic. I'll handle updating the P2P test in #2131. @y0sher could you please review?

**Review by y0sher — APPROVED** [review]
Sorry it took so long, I was sure it is still a draft. Looks perfectly good to me.

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge-

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
