### PR TITLE
[Merged by Bors] - block construction: enable optimistic filtering in systests

### LINKED ISSUE #3346: enable optimistic filtering in systest
## Description

attempt # 0 (https://github.com/spacemeshos/go-spacemesh/pull/3342) to fix this has failed. 

the PR (enabled optimistic filtering) caused systest TestFailedNode to be flaky.
when optimistic filtering is ON, and the consensus mesh disagree with the node's local mesh hash, it will not generate the block,
causing the layer to be empty.
the PR is reverted in #3345 

more details on how the test fails can be found here
https://github.com/spacemeshos/go-spacemesh/issues/3343

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3346

## Changes

- allow 100% agreement, replacing > with >=
- make sure consensus on empty layer hash is not consensus.
- add unit tests
- reduce consensus threshold to 90% in systests

## Test Plan

unittest, systests, longevity

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Review by abergasov — APPROVED** [review]

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
