### PR TITLE
[Merged by Bors] - added unit test for multi node simulator sanity

### LINKED ISSUE #1692: Create unit and sanity tests for fast_node_sim
# Overview / Motivation
we currently don't have tests that check the entire fast node simulator

# The Task
TODO: Clearly describe the issue requirements here...

# Implementation Notes
TODO: Add links to relevant resources, specs, related issues, etc...

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who haven't introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

### PR DESCRIPTION
**Pull request by antonlerner**
## Motivation
Closes #1692 

## Changes
Added sanity test for multi node simulator

### CODE REVIEW

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Review by gavraz — APPROVED** [review]

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors try

**Comment by antonlerner** [comment]
bors try

**Comment by antonlerner** [comment]
bors try

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors try

**Comment by antonlerner** [comment]
bors merge

**Pull request closed without merging**
