### PR TITLE
[Merged by Bors] - remove the last use of leveldb

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

remove the last use of level db

## Changes

create a new table `niposts` for key/value pair storage.

## Test Plan

unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]
we could also store nipost in a file

**Comment by countvonzero** [comment]
> we could also store nipost in a file

yeah, i considered that. i ended up using sql because the error handling seems simpler considering the logic of overwriting previous data

**Comment by countvonzero** [comment]
@dshulyak 
the unittest failed because i removed the dep from go.mod / go.sum. i ended up doing https://github.com/spacemeshos/go-spacemesh/pull/3262/commits/04e6f63f4b0c6238f591ec57822d5bb8e8094afa to satisfy both CI quicktests and unit tests.

do you have better suggestion?

```
--- FAIL: TestNewNIPostBuilderNotInitialized (0.33s)
    nipost_test.go:247: 
        	Error Trace:	nipost_test.go:247
        	Error:      	Received unexpected error:
        	            	default integration config: failed to build poet: go build failed: exit status 1
Error:         	            	stderr: ../../../../go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.202206160532[40](https://github.com/spacemeshos/go-spacemesh/runs/6930601572?check_suite_focus=true#step:6:41)-3adb19bb0395/service/db.go:5:2: missing go.sum entry for module providing package github.com/syndtr/goleveldb/leveldb (imported by github.com/spacemeshos/poet/service); to add:
        	            		go get github.com/spacemeshos/poet/service@v0.1.1-0.20220616053240-3adb19bb0395
Error:         	            	../../../../go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20220616053240-3adb19bb0395/service/db.go:6:2: missing go.sum entry for module providing package github.com/syndtr/goleveldb/leveldb/iterator (imported by github.com/spacemeshos/poet/service); to add:
        	            		go get github.com/spacemeshos/poet/service@v0.1.1-0.20220616053240-3adb19bb0395
Error:         	            	../../../../go/pkg/mod/github.com/spacemeshos/poet@v0.1.1-0.20220616053240-3adb19bb0395/service/db.go:7:2: missing go.sum entry for module providing package github.com/syndtr/goleveldb/leveldb/opt (imported by github.com/spacemeshos/poet/service); to add:
        	            		go get github.com/spacemeshos/poet/service@v0.1.1-0.20220616053240-3adb19bb0395
        	Test:       	TestNewNIPostBuilderNotInitialized
```

**Comment by dshulyak** [comment]
it should be added to the poet here https://github.com/spacemeshos/poet/blob/develop/integration/harness.go#L18

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
