### PR TITLE
[Merged by Bors] - partition test: increase healing time

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation
remove flakiness in the systest

### CODE REVIEW

**Review by fasmat — APPROVED** [review]
should we also use this PR to reduce the timeouts of Systemtest I and Systemtest II again?

**Comment by countvonzero** [comment]
> should we also use this PR to reduce the timeouts of Systemtest I and Systemtest II again?

great idea. done

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
