### PR TITLE
[Merged by Bors] - Fix code coverage failing

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Code coverage is failing because it tests packages that are not part of the node code and runs into name collisions of global variables

## Changes
Remove packages of utility tools from code coverage tests and unit tests.

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]
would it better to move all binaries into single module just for them, and filter out that module?

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
> would it better to move all binaries into single module just for them, and filter out that module?

I moved all binaries to sub-packages of `cmd`. I couldn't filter out just the `cmd` package as there are unit tests in the `cmd/bootstrapper` package and moving them is a bit more involved (they use global variables) so I would like to do that in a separate PR.

**Comment by fasmat** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
