### PR TITLE
WIP: Merkle delete tests

### PR DESCRIPTION
**Pull request by dgonzalez**

### CODE REVIEW

**Comment by avive** [comment]
@dgonzalez - what is the status of this issue? Any plans to get this done soon?

**Comment by dgonzalez** [comment]
I made some progress mainly learning about merkle tries and different
implementations. I need to push more changes but the delete in general does
not require a huge amount of changes. The tests are structured a bit
funky... do we have any standard for them e.g. tests on a different package
or folder structure.

**Comment by avive** [comment]
Good point regarding tests. What we found is that what's typically called `unit tests` and can be used with golang coverage support must be in the same package as the tested code and typically `integration tests` go in their own test package so they can only use exported package apis. Our initial focus is to have unit tests that cover all major code paths. Makes sense or perhaps we are missing something obvious about go tests here?

**Comment by dgonzalez** [comment]
No no. It makes perfect senses to me. Unit tests should be on the same
package whereas integration and BDD should be even in their own project.
Will push changes soon (just got suddenly very busy at work).

**Comment by avive** [comment]
@dgonzalez - are you planning to finish this PR?

**Comment by dgonzalez** [comment]
Hi, I am totally swamped at work :(. If anyone wants to take over happy to give it. Thanks.

**Pull request closed without merging**
