### PR TITLE
[Merged by Bors] - Systest: update README

### PR DESCRIPTION
**Pull request by evt**
## Motivation
I've noticed a few discrepancies when going through systest installation process. So here are a few changes to make this process cleaner.

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by dshulyak** [comment]
@evt do you want to merge it?

**Comment by evt** [comment]
> @evt do you want to merge it?

@dshulyak just added some more bits into README. Also shall we change limits like attached may be as long as tests work with them?
Screenshot 2022-04-20 at 12 13 26

**Comment by dshulyak** [comment]
@evt sure lets decrease limits

**Comment by evt** [comment]
bors try

**Comment by evt** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by evt** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
