### PR TITLE
[Merged by Bors] - sql: add coinbase index to atxs table

### LINKED ISSUE #5581: consider adding index by coinbase for atxs
see related pr https://github.com/spacemeshos/go-spacemesh/pull/5566

we lack an index by coinbase for fast filtering atxs by it, hence queries that want to use such filter will have to do sequential scan.
i previously thought that we can do without it if we apply filter by epoch first, and then filter by coinbase all atxs within that epoch.
but since then number of atxs grew significantly and this approach may not be viable.

it is probably worth it to add an index by coinbase, as it we can expect it to be frequent query. probably people will care about all atxs that they have more than an individual atxs.

### PR DESCRIPTION
**Pull request by kacpersaw**
## Description

Added index by coinbase to atxs table as the number of atxs grew significantly and we can expect that it will be frequently queried from API.

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]
could you doublecheck how fast are new atxs queries, with and without this index, before merging?

to make api read from disk you could drop kernel caches with:

> echo 3 > /proc/sys/vm/drop_caches

**Comment by kacpersaw** [comment]
@dshulyak it's better than before. Checked on macOS M1

### With index
```
INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T14:15:19+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:57557", "grpc.code": "OK", "grpc.time_ms": 6906.889}

INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T14:18:37+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:58591", "grpc.code": "OK", "grpc.time_ms": 7242.017}

INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T15:09:51+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:61473", "grpc.code": "OK", "grpc.time_ms": 7406.61}

INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T15:10:27+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:61530", "grpc.code": "OK", "grpc.time_ms": 7715.156}
```
### Without index
```
INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T14:16:13+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:57823", "grpc.code": "OK", "grpc.time_ms": 10101.229}

INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T14:17:12+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:58145", "grpc.code": "OK", "grpc.time_ms": 9029.339}

INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T15:11:00+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:61557", "grpc.code": "OK", "grpc.time_ms": 9657.68}

INFO	grpc	finished unary call with code OK	{"grpc.start_time": "2024-02-19T15:11:22+01:00", "system": "grpc", "span.kind": "server", "grpc.service": "spacemesh.v2alpha1.ActivationService", "grpc.method": "List", "peer.address": "127.0.0.1:61578", "grpc.code": "OK", "grpc.time_ms": 9886.525}
```

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Pull request closed without merging**
