### PR TITLE
[Merged by Bors] - Pass standard net.Addr struct around P2P package

### PR DESCRIPTION
**Pull request by dhyon**
### Motivation
Address #181

### CODE REVIEW

**Comment by dhyon** [comment]
hey @y0sher am I trending in the right direction of what you hand in mind for issue #181 ? I'd like some feedback before I go too far with this.

**Comment by y0sher** [comment]
Hi, looks good so far! That's pretty much what I meant. The goal is the use
the same primitives all over the package ( when referring to the same value
type )

**Comment by y0sher** [comment]
bors try

**Comment by y0sher** [comment]
looks good to me let's wait for bors to run system tests.

**Review by y0sher — APPROVED** [review]

**Comment by y0sher** [comment]
bors merge

**Comment by y0sher** [comment]
bors merge

**Pull request closed without merging**
