### PR TITLE
[Merged by Bors] - Enable auto-fixable linters

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

Currently, a significant amount of changes in many PRs is moving imports around, adding or removing trailing newlines, or doing similar things, which increases PR sizes and distracts. There're some linters in `golangci-lint` that can auto-fix code-styling issues and apply the same format to all code. This PR enables them and adds a new `Makefile` target which auto-fixes the code according to code-style linters rules: `make golangci-lint-fix`.

## Changes

- Enable new linters:
    - gci
    - godot
    - gofmt
    - gofumpt
    - whitespace
- Add `make golangci-lint-fix` to auto-fix linter issues

## Test Plan

No testing needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try

**Review by countvonzero — APPROVED** [review]
thanks for doing the grungy work

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
