### PR TITLE
[Merged by Bors] - remove unused logic for orphan blocks

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

code cleanup

## Changes

orphan blocks logic is unused

## Test Plan

unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
do you know how they were used, and why abandoned?

**Review by nkryuchkov — APPROVED** [review]

**Comment by countvonzero** [comment]
> do you know how they were used, and why abandoned?

no i don't. @y0sher @antonlerner @noamnelke @lrettig any idea?

in any case, my thought on this is that it's currently unused. 
if the concept is still useful, i'll add it in the unified content block impl. it's easier to cleanup unused code now before introducing UCB.

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
