### PR TITLE
[Merged by Bors] - sql: remove rewards_coinbase_layer as it is created with primary

### LINKED ISSUE #4691: redundant index `rewards_by_coinbase `on table `rewards`
The table `rewards` is created as `WITHOUT ROWID` which is creating clustered index on the primary key implicitely.
To save storage and computing overhead it would make sense to remove the index `rewards_by_coinbase`.

https://github.com/spacemeshos/go-spacemesh/blob/9c5e88b01e57b4128108ef8439b4225820ffb33a/sql/migrations/0001_initial.sql#L60

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/go-spacemesh/issues/4691

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
this actually needs to go into 0002_migration file

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
