### PR TITLE
[Merged by Bors] - Remove Subscription mechanism from internal clock

### LINKED ISSUE #4010: Design Proposal: remove pub/sub pattern from internal clock
## Description
go-spacemesh has an internal clock that is used for multiple purposes, but most importantly to signal to other parts of the codebase when layers start and end and when a certain layer has been reached.

The problem with the current implementation is the `Subscribe` / `Unsubscribe` methods of the clock. These cause avoidable issues if instead the code would only use `AwaitLayer` and `GetCurrentLayer`.

### Affected code
- `TimeClock`
- `Ticker`
- `LayerConverter`
- and possible other classes / interfaces in the `timesync` package

### Issues with the current approach

The current approach has a few drawbacks:
- The Pub / Sub design causes the clock to take longer to signal a layer change the more listeners subscribe to this signal. This can cause performance issues if many parts of the code subscribe to the clock or worse: do not unsubscribe if they are not interested in the signal any more.
- If a listener subscribes and then isn't immediately ready to read the update via the channel it received from the subscription the signal it will cause the clock to skip sending the signal. This will cause the subscriber to wait reading on a channel that is never written to or closed leading to a deadlock.

### Proposal

go-spacemesh needs the following features across its codebase that are time-related:

- `CurrentLayer` this method needs to return the current layer of the network based on the system time. This might in some cases be not monotonic (i.e. when the system time was changed via NTP).
- `AwaitLayer` this method returns a channel that is closed when the layer in question is reached. This again uses wall time (the system time of the computer) to determine which is the current layer. The returned channel is closed when the layer has been reached OR surpassed (e.g. the system was hibernating for multiple layers - `AwaitLayer` on all those layers will signal at the same time when the system wakes up). Code that should be executed in a specific layer and uses `AwaitLayer` should check again with `CurrentLayer` if the layer in question might have passed already.

### Advantages and disadvantages with the proposed approach

- `AwaitLayer` scales to an arbitrary number of listeners without causing performance issues: Only one `close` operation per layer is performed by the clock, independently of how many listeners await it.
- `AwaitLayer` signals exactly once to all listeners, when the layer is reached or has been passed, The signal can be processed by listeners immediately or later without affecting the clock. `Subscribe` on the other hand tries to signal to multiple listeners at the same time. In the case of time jumps possibly multiple layers are signalled to multiple listeners. The clock has to skip signalling if a listener doesn't react to the signal immediately or it gets stuck, causing "missed tick" errors.
- The returned channel from `AwaitLayer` signals that the layer has been reached OR passed. The caller needs to make sure that they know which layer they are in by having to call `CurrentLayer` again after receiving the signal.

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Closes #4010, this is a follow up to #4012, #4013, #4014 and removes the now obsolete pub/sub mechanism of the internal clock.

## Changes
The core of the change is the `timesync` package, the rest of the PR is adapting the existing code to the new interface of the clock. `AwaitLayer` and `Subscribe` have the same purpose, but behave differently. This PR removes the duplicated code and simplifies the clock:

- `Subscribe`/`Unsubscribe` and all logic associated with these two methods has been removed
- `Ticker` and `TimeClock` have been merged into `NodeClock`
- Methods `GetGenesisTime` and `GetCurrentLayer` have been renamed to `GenesisTime` and `CurrentLayer`.
- The clock itself is now ticking once at the beginning of a layer and adjusts the waiting period until the next layer based on when the tick was issued.

## Test Plan
Tests for `NodeClock` have been written from scratch, with emphasis on safe concurrent use and stability against time shifts that might be caused by NTP or the node hibernating.

For this I added a dependency on http://github.com/benbjohnson/clock (was already an indirect dependency). It allows to mock time more easily in tests than it would be possible with `gomock`.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
Bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
Bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors merge-

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
