### PR TITLE
[Merged by Bors] - config: make genesis config a part of a regular config and simplify it

### LINKED ISSUE #2004: Move genesis account configuration to config file
## Background
As highlighted in #1903, the default node configuration creates pre-loaded tap accounts for testing (whose private keys must be in the code). In an open testnet we don't want these accounts to exist.

It's currently possible to configure the pre-loaded accounts via the `GenesisConfPath` in the configuration, which should point to a file containing this configuration. This makes it technically harder to control.

## Required changes
The pre-loaded tap accounts should be configurable using the main `config.toml`.

### Inline tables in TOML
Including a list of objects in a TOML file doesn't have to be very hard. The TOML documentation lists the following option at the end of the section on [Array of Tables](https://github.com/toml-lang/toml#user-content-array-of-tables):
```toml
points = [ { x = 1, y = 2, z = 3 },
           { x = 7, y = 8, z = 9 },
           { x = 2, y = 4, z = 8 } ]
```

---

Of course the node doesn't require any particular format for config files, other than TOML, JSON and any other common format is supported.

### PR DESCRIPTION
**Pull request by dshulyak**
## Motivation

required for: https://github.com/spacemeshos/go-spacemesh/issues/2493
closes: https://github.com/spacemeshos/go-spacemesh/issues/2004

## Changes

Config accepts the following map of accounts that will be included in a genesis:

```json
{
  "genesis": {
    "accounts": {
      "0x01": 10,
      "0x02": 20
    }
  }
}
```

## Test Plan
Unit tests and CI

## TODO
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by noamnelke** [comment]
bors try

**Review by noamnelke — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
