### PR TITLE
[Merged by Bors] - Lowered vrf eligibility threshold to Info

### PR DESCRIPTION
**Pull request by pigmej**

### CODE REVIEW

**Review by fasmat — APPROVED** [review]
@acud this probably needs to be done for `hare4` too 🙂

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Review by ivan4th — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
