### PR TITLE
[Merged by Bors] - activation: prove with empty challenge only once

### LINKED ISSUE #3087: activation: prove with empty challenge only once
## Description

Currently, generating proof using an empty challenge occurs at the end of the initialization phase every time smeshing is started. Actually, we need to do this only once. We can probably check if ATX is initial and generate proof only in this case.

## Affected code

`activation`

This issue appears in commit hash: 
`df19fc27528625e02bac4472a5d5dc911adfbb9a`

Related files (optionally with line numbers): 
https://github.com/spacemeshos/go-spacemesh/blob/develop/activation/activation.go#L302

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

Closes #3087

## Changes

- generate proof only only if ATX is initial

## Test Plan

Unit tests, system tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try

**Comment by dshulyak** [comment]
i think it needs a test

**Comment by nkryuchkov** [comment]
@dshulyak Thanks. Added.

**Review by dshulyak — APPROVED** [review]

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
