### PR TITLE
[Merged by Bors] - start CI tests from the longest to the shortest

### PR DESCRIPTION
**Pull request by AmitShaul**
## Motivation
added sleep for CI tests to enable longer tests start earlier than shorter ones

### CODE REVIEW

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try-

**Comment by AmitShaul** [comment]
bors try-

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Review by noamnelke — APPROVED** [review]
As I mentioned before, I don't like this solution. I'm approving as a temp-hack, but I think there are much better solutions we can implement for this. Let's discuss the better solutions if you don't know what I mean.

**Comment by AmitShaul** [comment]
bors merge

**Pull request closed without merging**
