### PR TITLE
[Merged by Bors] - refactor(systest): remove unused labels

### PR DESCRIPTION
**Pull request by acud**
## Motivation

The labels in the systest package don't seem to do much. Unless someone can argue for their necessity - I would suggest to remove them.
## Description

...

## Test Plan

Make sure systests still do what they're supposed to do without this.

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by poszu — CHANGES_REQUESTED** [review]
I agree with the effort 100%, thanks! The labels are still present in few places though:
- https://github.com/spacemeshos/go-spacemesh/blob/e70a1086205bfe9f8056b2446900ef5f3a17b33c/.github/workflows/systest.yml#L136
- https://github.com/spacemeshos/go-spacemesh/blob/978d03c7f102aafef02a0304bfca8c8d9a414db7/systest/Makefile#L25
- https://github.com/spacemeshos/go-spacemesh/blob/978d03c7f102aafef02a0304bfca8c8d9a414db7/systest/Makefile#L40

**Comment by fasmat** [comment]
Btw. these labels are used - we have multiple tests that are currently not executed because they are not labeled `sanity`:

```
=== RUN   TestStepCreate
    context.go:305: not labeled with 'sanity'
--- SKIP: TestStepCreate (0.00s)
=== RUN   TestStepShortDisconnect
    context.go:305: not labeled with 'sanity'
--- SKIP: TestStepShortDisconnect (0.00s)
=== RUN   TestStepTransactions
    context.go:305: not labeled with 'sanity'
--- SKIP: TestStepTransactions (0.00s)
=== RUN   TestStepReplaceNodes
    context.go:305: not labeled with 'sanity'
--- SKIP: TestStepReplaceNodes (0.00s)
=== RUN   TestStepVerifyConsistency
    context.go:305: not labeled with 'sanity'
--- SKIP: TestStepVerifyConsistency (0.00s)
=== RUN   TestScheduleBasic
    context.go:305: not labeled with 'sanity'
--- SKIP: TestScheduleBasic (0.00s)
=== RUN   TestScheduleTransactions
    context.go:305: not labeled with 'sanity'
--- SKIP: TestScheduleTransactions (0.00s)
=== RUN   TestStepValidation
    context.go:305: not labeled with 'sanity'
--- SKIP: TestStepValidation (0.00s)
```

With the change as it is they would now be executed. I didn't check how long those take to run but since the `README.md` calls them "Longevity tests" I'd suggest those should continued to be skipped during `systests`? At least one of them (`TestScheduleBasic`) takes > 1 hour to complete

**Comment by poszu** [comment]
>Btw. these labels are used - we have multiple tests that are currently not executed because they are not labeled sanity

In this case, we should not merge this w/o an alternative solution. Thanks @fasmat

**Comment by acud** [comment]
bors try

**Comment by acud** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Comment by acud** [comment]
@poszu https://github.com/spacemeshos/go-spacemesh/actions/runs/9995613606/job/27628169439#step:17:181

**Review by poszu — APPROVED** [review]

**Comment by acud** [comment]
bors merge

**Pull request closed without merging**
