### PR TITLE
[Merged by Bors] - Bump post to v0.6.6

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Includes:
- fixes in POST k2 pow,
- fixed log level mapping (debug -> trace) for logs in post-rs,
- fixed post profiler release for ARM

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Flaky `TestNodesUsingDifferentPoets` - failed to reach poet service (unavailable)

bors merge

**Pull request closed without merging**
