### PR TITLE
[WIP] Add some love to Makefile

### PR DESCRIPTION
**Pull request by divan**
## Motivation
I was familiarizing myself with Makefile and realized that there is no easy way to learn the list of targets and make sense of what they're for. As the love to ASCII art is hard not to notice on Spacemesh website, I thought it would be a good idea to add some ASCII-based help/usage command to Makefile.

## Changes
 - new Makefile `help` is added, which displays fancy usage info and list of existing targets
 - each target mentioned in help now has a comment in the form "## Description" or "##@category Description"

## Demo
Screenshot 2020-08-01 at 22 08 53

## TODO
- [x] Make sure if all "public" targets are listed and described correctly
- [x] Make sure "internal" targets (not intended to be run by developers) are hidden from the help output to keep it concise
- [x] Verify if it looks acceptable on white background
- [ ] Test on Windows (if there any devs on Windows)
- [x] Remove placeholder for Spacemesh logo (or find a way to display logo in ASCII)

### CODE REVIEW

**Comment by y0sher** [comment]
Hi @divan ! this looks awesome. thanks for the PR!
can't wait to see the final result :star_struck:

**Comment by divan** [comment]
Thanks @y0sher. I think first two items in the checklist is more of a question to the core dev team members. I inferred the descriptions and actually used targets just by reading Makefile, and not sure everything is correct. So inputs/feedback would be appreciated here.

**Comment by lrettig** [comment]
This is great, thanks for the contribution @divan! I added some ascii art and slightly changed the way the printing happens in the makefile.

Re: the outstanding tasks here:

> Verify if it looks acceptable on white background

It looks okay, not great. You can't read the "spacemesh" text in the box at the top, but all of the other text is visible. I don't think there's much we can do about this. It's still perfectly usable.

> Test on Windows (if there any devs on Windows)

It doesn't currently work on Windows, I tested this. It has to do with how the shell interprets this line:

https://github.com/divan/go-spacemesh/blob/140bc569a1a1b76e6cf1cc0ed80b84b887d600dc/Makefile#L80

I don't know how to "export" a make variable to a shell env var in Windows. I tried some of the other ideas in [this SO thread](https://stackoverflow.com/questions/649246/is-it-possible-to-create-a-multi-line-string-variable-in-a-makefile) but none of them work on Windows, the interpolation rules seem to be different and it doesn't seem to like multi-line env vars.

**Comment by lrettig** [comment]
Since this is purely aesthetic, I think it can be merged without Windows support for now - @divan already wrapped this in `if` statements to disable it on Windows.

**Review by lrettig — APPROVED** [review]

**Comment by antonlerner** [comment]
closed due to inactivity

**Pull request closed without merging**
