### PR TITLE
[Merged by Bors] - node: make sure that hrp is configurable

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by dshulyak** [comment]
@fasmat could you check this change, it was included in https://github.com/spacemeshos/go-spacemesh/pull/4663

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
I would not use different binaries for different networks. The HRP has to be provided as part of the config or via CLI parameters. Maybe we have to refactor the Adress generator as a service then as well that gets injected the config to receive it.

**Comment by dshulyak** [comment]
> I would not use different binaries for different networks. The HRP has to be provided as part of the config or via CLI parameters. Maybe we have to refactor the Adress generator as a service then as well that gets injected the config to receive it.

ok, i will remove that from description, so we can reconsider whats better later

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
