### PR TITLE
[Merged by Bors] - Drop peers when outbound message queue is full

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Closely related to #2435
Partially addresses #1868, #2386 (and maybe #2405)

## Changes
When the outbound message queue for a given connection is full, rather than blocking on `Send`, begin dropping messages and printing errors (rather than allowing the blocking to propagate up the gossip stack)

It would be good to go one step further and drop peers that are hanging, but this is a quick, simple fix for the acute issue we're seeing on the testnets. See #2385.

## Test Plan
Includes a new unit test for both `conn` and `msgconn` types

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by dshulyak** [comment]
This queue is not only for broadcast, but also for direct requests (msg server and fetcher), is it the case? If so we can't simply drop messages, we must disconnect peer and return with error.

**Comment by lrettig** [comment]
> This queue is not only for broadcast, but also for direct requests (msg server and fetcher), is it the case? If so we can't simply drop messages, we must disconnect peer and return with error.

This is correct. I updated this to drop peers if the outbound queue is full. Could you please take a look and see if this is what you had in mind?

**Comment by dshulyak** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
yes, thanks! 

i am wondering how it can fail. are we ever sending bursts of data over short period of time,? if we do it will naturally take some time and queue may fill up with smaller messages.

**Comment by lrettig** [comment]
Thanks. Not sure why the apptests failed, I can't recreate the `TestShutdown` failure locally. It looks like it's this goroutine but I don't see anything wrong with the shutdown logic:

```
        goroutine 313099 [select]:
        github.com/spacemeshos/go-spacemesh/activation.(*Builder).waitOrStop(0xc01a486000, 0x132b6a0, 0xc02159a300, 0xc01a47cb40, 0xc01a47bee0, 0xc02159bb80)
        	/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:283 +0xbd
        github.com/spacemeshos/go-spacemesh/activation.(*Builder).loop(0xc01a486000, 0x132b6a0, 0xc02159a300)
        	/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:309 +0x1ff
        created by github.com/spacemeshos/go-spacemesh/activation.(*Builder).StartSmeshing.func1
        	/home/runner/work/go-spacemesh/go-spacemesh/activation/activation.go:246 +0x15f
```

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
> i am wondering how it can fail. are we ever sending bursts of data over short period of time,? if we do it will naturally take some time and queue may fill up with smaller messages.

Yes, definitely. This pattern is pretty common due to gossip: every node does something, such as sending a hare message or creating blocks, then gossips them at the same time, so there's a massive explosion of data across the network in a brief period. If the node has a stable connection to its peers then the queue should not fill up since it should be able to send messages pretty quickly, but we do need to parameterize this so that the queue channel is large enough to handle these bursts.

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

>

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge-

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by dshulyak** [comment]
this change clearly makes p2p systest fail more often

**Comment by lrettig** [comment]
It's probably the debug logs, will try to comment those out, I've seen this issue before

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
This is done and ready to be merged, but stuck on flaky tests. Assigning to @antonlerner to make sure it gets merged. Let me know if I've missed anything or if there are any questions. Thanks!

**Comment by dshulyak** [comment]
bors try

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
