### PR TITLE
[Merged by Bors] - Upgrade go-libp2p

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

`go-libp2p` v0.34.0 had to be rolled back because of a bug that was introduced and affected go-spacemesh, for details see: https://github.com/spacemeshos/go-spacemesh/pull/6017

Since then `go-libp2p` v0.35.1 has been released that fixes the issue. Upgrading to this version would also allow us to update other dependencies that are currently blocked.

## Description

Upgrade `go-libp2p` and other libraries dependent on it or blocked from updating so far.

## Test Plan

existing tests pass.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by ivan4th — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
rpc errors

bors merge

**Pull request closed without merging**
