### PR TITLE
Testnet 130 candidate

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Candidate build for next testnet

## Changes
- improved contextual logging

### CODE REVIEW

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by avive** [comment]
Is this release be compatible w TN 29 or requires a new network?

**Comment by lrettig** [comment]
> Is this release be compatible w TN 29 or requires a new network?

So far, it's compatible. But the next testnet will likely include #2411 which would make it incompatible.

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
This has been live in tn130 for a while, merging

**Pull request merged**
