### PR TITLE
[Merged by Bors] - Update join testnet instructions

### PR DESCRIPTION
**Pull request by avive**
Update testnet go-spacemesh release link and toml canonical url.

## Motivation

Closes #

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

### CODE REVIEW

**Review by antonlerner — APPROVED** [review]

**Comment by avive** [comment]
bors merge

**Review by almogdepaz — APPROVED** [review]

**Review by gavraz — APPROVED** [review]
Just check that link works

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Pull request closed without merging**
