### PR TITLE
[Merged by Bors] - systests: deflake tests that watch layers

### LINKED ISSUE #4468: system tests that are watching layer updates are prone to flakes
latest failure: https://github.com/spacemeshos/go-spacemesh/actions/runs/5157057155/jobs/9289424245

there is a number of tests that are watching layers with: TestFailedNodes, TestPartition/*

```go
states, err := stateapi.GlobalStateStream(ctx,
		&pb.GlobalStateStreamRequest{
			GlobalStateDataFlags: uint32(pb.GlobalStateDataFlag_GLOBAL_STATE_DATA_FLAG_GLOBAL_STATE_HASH),
		})
```

the hash is read when we trigger layer update in mesh code:

```go
events.ReportLayerUpdate(events.LayerUpdate{
			LayerID: layer.Layer,
			Status:  events.LayerStatusTypeApplied,
		})
```

opinion often changes within several seconds, such as node was against the layer, then 5s later it changed opinion to support of the block. this causes flake in tests, where opinion doesn't match on the cluster

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/go-spacemesh/issues/4468

- always send out notifcation when effective genesis is verified, as ballots are voting against it
- send grpc event with opinion, once layer is verified. at that point opinion is not likely to change
- every time layer was undecided and crossed
- add count variable to namespace, to control how many times selected tests are executed

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
last failure https://github.com/spacemeshos/go-spacemesh/issues/4497 . not related to fixed tests

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
