### PR TITLE
[Merged by Bors] - enable hare3 with comittee 400 at 33101

### LINKED ISSUE #276: enable hare3 on mainnet
the prerequisite is to run hare3 on testnet with 800+ nodes for 1 week.
on success it should be enabled in next release.

i will optimistically target it for release at 17 oct (2 weeks from now)

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/pm/issues/276

it is set to 33101 which is 12 days from the time when this change was created.
current layer = 29645. 12 days is 3456 layers.

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
