### PR TITLE
[Merged by Bors] - relax sync failure on ATX failure

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation
when syncing current epoch, sync fails whenever it fails to fetch an ATX, and it will take the node from synced state to notSynced state. this is possibly too aggressive for current epoch, as ATXs are not fully gossiped in the network.

## Changes
for current epoch, only fail sync on ATX failure at last layer. 
for previous epoch, sync fails as soon as it fails to fetch ATXs for that epoch.

## Test Plan
unit test

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by antonlerner** [comment]
I assume that this PR is a bit less relevant after #2573 
Would you still like to merge this change? @countvonzero

**Review by antonlerner — APPROVED** [review]

**Comment by countvonzero** [comment]
@antonlerner 

yes. i think this PR is still useful. for getting epoch ATXs, layer fetcher simply pick one peer to send request. if network is flaky we will fall out-of-sync and require gossip-sync to recover. i think this is too severe.

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
