### PR TITLE
[Merged by Bors] - sync polling

### PR DESCRIPTION
**Pull request by almogdepaz**
Motivation
sync waits for layer tick to start syncing, this pr turns sync into using an independent timer
to allow better usability

them when this it's merged -->

Changes
syncer will check sync status every "SyncInterval"

Test Plan
same as before

### CODE REVIEW

**Comment by almogdepaz** [comment]
bors try

**Comment by almogdepaz** [comment]
bors try

**Review by gavraz — APPROVED** [review]

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors build

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Pull request closed without merging**
