### PR TITLE
[Merged by Bors] - Do not accept new tx via API if node is not in sync (take three)

### LINKED ISSUE #2103: API: don't allow submission of new transactions until node is synced
## Description
Right now, the TransactionService GRPC server accepts new transactions via `SubmitTransaction`, even while the node is syncing/not participating in gossip, without an error. However, incoming tx data is transmitted as a gossip message, which means that it's dropped silently if the node is still syncing. This should be an error in the GRPC service.

Note that this is also an issue in the old GRPC API, but we don't need to fix it since that will be deprecated soon in favor of the new API.

## Affected code
api/grpcserver/transaction_service.go

This issue appears in commit hash: a1f0055

This is what the logs look like now:

```
2020-08-06T11:51:33.442-0400    INFO    00000.defaultLogger     GRPC TransactionService.SubmitTransaction
2020-08-06T11:51:33.442-0400    INFO    00000.defaultLogger     GRPC TransactionService.SubmitTransaction to address: 0xf9bc4f997d235bA5a9A36C1A92D07882C2B2FdB6 (len: 20), amount: 1, gaslimit: 2, fee: 1
2020-08-06T11:51:33.443-0400    INFO    00000.defaultLogger     GRPC TransactionService.SubmitTransaction BROADCAST tx address f9bc4f997d235ba5a9a36c1a92d07882c2b2fdb6 (len 20), gas limit 2, fee 1 id 56abc07a23 nonce 0
```

And if you subsequently submit a second tx with a higher nonce:

```
2020-08-06T11:51:33.448-0400    INFO    00000.defaultLogger     GRPC TransactionService.SubmitTransaction
2020-08-06T11:51:33.448-0400    INFO    00000.defaultLogger     GRPC TransactionService.SubmitTransaction to address: 0xECAca87B528E8f87602D21Aa0150148902e47508 (len: 20), amount: 1, gaslimit: 2, fee: 1
2020-08-06T11:51:33.448-0400    ERROR   00000.defaultLogger     tx failed nonce and balance check: incorrect account nonce! Expected: 0, Actual: 1
```

### PR DESCRIPTION
**Pull request by hoenirvili**
(This is a copy of #2139 because I don't have authorization to push on the branch created by @lrettig )
## Motivation

When we submit a transaction we should verify if the node is in sync first.
Closes #2103

## Changes
 
I've added two checks one that checks if the transaction byte payload is even filled and one for testing the equality between the number of layers processed and the last layer in state.
## Test Plan

Looks like the TransactionService by default is not turn on and I did first turned on the transaction service in code (config) and then started the node(that is not in sync) and executed a grpcurl comand with the **xdr** serialized payload.

## TODO
* [x]  Explain motivation or link existing issue(s)
* [x]  Test changes and document test plan
* [x]  Update documentation as needed

### CODE REVIEW

**Comment by lrettig** [comment]
Ran some tests locally. Here's what things look like with the current develop branch:

```
> grpcurl -plaintext -d '{}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction
ERROR:
  Code: InvalidArgument
  Message: `Transaction` must contain a valid, serialized transaction
> grpcurl -plaintext -d '{"transaction": ""}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction                                      ERROR:
  Code: InvalidArgument
  Message: `Transaction` must contain a valid, serialized transaction
> grpcurl -plaintext -d '{"transaction": "AAAAAAAAAEUCJEXfFzim/7ZZJ1J8ZiyrBFi/YgAAAAAAAAACAAAAAAAAAAEAAAAAAAAD6LLu1XjpYBUlGQl/e29jkaElKFDvsbIZDuPcSGVH/u4Efsl/9I3NcMLG88gOszSNztx9AlyyfJ4Om0r2tPQwKwA="}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction   ERROR:
  Code: InvalidArgument
  Message: `Transaction` incorrect counter or insufficient balance
> grpcurl -plaintext -d '{"transaction": "AAAAAAAAAACOO/7lmmMINijr1R2seilHNdJyugAAAAAAAAACAAAAAAAAAAEAAAAAAAAD6IF7cUgEYJGLP83oRnLWxlSGzoFOmie5/xVtEvNFtYMqnLBZ4NgprJ3VndeJcWwoOgmBuksbu4kNDvuNoPHjxgU="}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction
{
  "status": {

  },
  "txstate": {
    "id": {
      "id": "oNJQ6qWnFjKrZ3Xnre7dKRbqdygEWGjPir7oNLmO6dg="
    },
    "state": "TRANSACTION_STATE_MEMPOOL"
  }
}
```

And here's what I see with these changes:

```
> grpcurl -plaintext -d '{}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction
ERROR:
  Code: InvalidArgument
  Message: `Transaction` payload empty
> grpcurl -plaintext -d '{"transaction": ""}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction
ERROR:
  Code: InvalidArgument
  Message: `Transaction` payload empty
> grpcurl -plaintext -d '{"transaction": "AAAAAAAAAEUCJEXfFzim/7ZZJ1J8ZiyrBFi/YgAAAAAAAAACAAAAAAAAAAEAAAAAAAAD6LLu1XjpYBUlGQl/e29jkaElKFDvsbIZDuPcSGVH/u4Efsl/9I3NcMLG88gOszSNztx9AlyyfJ4Om0r2tPQwKwA="}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction
ERROR:
  Code: FailedPrecondition
  Message: Cannot submit transaction, node is not in sync yet, try again later
> grpcurl -plaintext -d '{"transaction": "AAAAAAAAAACOO/7lmmMINijr1R2seilHNdJyugAAAAAAAAACAAAAAAAAAAEAAAAAAAAD6IF7cUgEYJGLP83oRnLWxlSGzoFOmie5/xVtEvNFtYMqnLBZ4NgprJ3VndeJcWwoOgmBuksbu4kNDvuNoPHjxgU="}' localhost:9092 spacemesh.v1.TransactionService/SubmitTransaction
ERROR:
  Code: FailedPrecondition
  Message: Cannot submit transaction, node is not in sync yet, try again later
```

Looks like the expected behavior ✅

**Review by lrettig — APPROVED** [review]
LGTM, tested locally

**Comment by lrettig** [comment]
Adding @noamnelke for review in case he wants to take a look, otherwise I think this can be merged

**Comment by hoenirvili** [comment]
What's your opinion @noamnelke ?

**Review by noamnelke — APPROVED** [review]
LGTM

**Comment by lrettig** [comment]
Thanks Noam

bors merge

**Pull request closed without merging**
