### PR TITLE
[Merged by Bors] - block certificate: allow certify msg from up to zdist+1 layers ago

### LINKED ISSUE #3548: certificate: nodes can't generate certificate if hare completed not in the current layer
i am testing this change https://github.com/spacemeshos/go-spacemesh/pull/3544 and expected to download certificate on nodes that failed hare in layer 9. the test is TestShortTimeSkew
this is one of those nodes {namespace="test-aymd", pod="smesher-46-0"} |= "sync"

{"L":"WARN","T":"2022-09-12T07:26:47.157-0400","N":"9c366.sync         ","M":"failed to fetch opinions","node_id":"9c366a65334583c81f7a59896b6f4f2934cdb73385e8b4740201a743fa098d8b","module":"sync","sessionId":"bac74477-8fa1-4c0e-bc7e-48338a714d82","layer_id":9,"errmsg":"PollLayerOpinions: certificates missing from all peers","name":"sync"}

indeed all 40 nodes failed to send certify messages {namespace="test-aymd"} |= "failed to certify block"

## affected code

https://github.com/spacemeshos/go-spacemesh/blob/develop/blocks/certifier.go#L305-L309

it is expected that it may take hare more than one layer to finish, in this particular case first iteration leader failed to participate due to chaos conditions in TestShortTimeSkew  

## implementation plan

accept messages within zdist from the current layer, e.g. msg.Layer should be in the range `[current - zdist - 1, current + 1]`. -/+ 1 is to avoid concurrency issues if hare finishes on the layer boundary.

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #3548

## Changes

accept CertifyMessage btwn the range [current - zdist - 1, current + 1]

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
there is crash with panic: layer_id wraparound

`{namespace="test-qqwh", pod="smesher-11-0"} | stream="stderr"`

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
