### PR TITLE
[Merged by Bors] - Send Account data in streaming APIs

### LINKED ISSUE #2940: Implement sending `Account` data in `AccountDataStream`
## Description

`AccountDataStream` may send [either of 3 data types ](https://github.com/spacemeshos/api/blob/105249951c66561cfc52195433ecae9cd5a121ff/proto/spacemesh/v1/global_state_types.proto#L76):
- `Reward`
- `TransactionReceipt`
- `Account`

Currently, streaming of `Account` data is not implemented yet.

## Affected code

Event reporting subsystem

This issue appears in commit hash: 
`ef0a4e146c25c96ca23c90ee3ad6d68242a60220`

Related files (optionally with line numbers): 
`events` package

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

Closes #2940 

## Changes

- Send Account data in streaming APIs

## Test Plan

- Unit and system tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [ ] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by nkryuchkov** [comment]
bors try

**Review by countvonzero — COMMENTED** [review]
can you find a way to test that events are correctly reported?

**Comment by nkryuchkov** [comment]
@countvonzero The `events.ReportAccountUpdate` function is tested in `TestAccountDataStream_comprehensive` and `TestGlobalStateStream_comprehensive`. Is that what you meant? But if you meant testing if a `events.Report...` function is actually called, we don't currently do that, but I'm not sure that we need it.

**Review by dshulyak — COMMENTED** [review]
i don't fully understand what do we stream here. is it just a notification event that account state has changed? it is not sufficient to listen for transactions and/or rewards?

**Comment by nkryuchkov** [comment]
> is it just a notification event that account state has changed?

Yes

> it is not sufficient to listen for transactions and/or rewards?

We won't get balance and nonce then.

**Review by dshulyak — APPROVED** [review]

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
> Build failed (retrying...):
> 
> * [ci-stage2](https://github.com/spacemeshos/go-spacemesh/runs/4285988724?check_suite_focus=true)

Looks like an infra failure

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
