### PR TITLE
[Merged by Bors] - Using PubKeyExtractor as injected service instead of as a global function

### LINKED ISSUE #3902: Re-assess nonce encoding in VRF signatures
## Description
With https://github.com/spacemeshos/go-spacemesh/pull/3877 nonces were added to VRF signatures. These are currently just added as an 8 byte little endian prefix to the message that is signed before signing (and validation).

We should re-assess how we want to encode this nonce (see also https://github.com/spacemeshos/go-spacemesh/pull/3877#discussion_r1056026113) :
- Add it to the message as a field before serializing it with go-scale
- using a separate `VRFMessage` type that has 2 fields: the message to be signed and the nonce before encoding that with go-scale
- possibly a different encoding

Both have advantages and disadvantages; using it as a field in the actual message means we can have messages with and without the nonce, and the messages can be validated without first needing to fetch and validate the initial ATX of a node. The second requires less code change and keeps the message objects themselves clean to contain only the data that is relevant for the message itself.

## Affected code
`signing` package and possibly `common/types` for the objects that are signed with the VRFSigner

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
This is a followup to #3971 and closes #3902. Merge after #3971 

## Changes
Instead of using the global variable `ExtractNodeIDFromSig` in `common/types` inject a service into the places where pubkey-extraction is needed. This still allows to use different prefixes between tests and actually running the node but avoids using the global function.

## Test Plan
All existing tests still pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by countvonzero** [comment]
i am not super sure about this. why does component need a custom function for extracting public key from signature?
it seems like a perfect use case for a global static function.

**Comment by fasmat** [comment]
> i am not super sure about this. why does component need a custom function for extracting public key from signature?
it seems like a perfect use case for a global static function.

It is not static but changes during startup of the node based on the configuration (network prefix) that is loaded from the config. The global function is defined without prefix for tests [here](https://github.com/spacemeshos/go-spacemesh/blob/32b67e2c2d561b991bdf2d7808de4f9c656e5a90/common/types/nodeid.go#L17-L27) and is overwritten during startup [here](https://github.com/spacemeshos/go-spacemesh/blob/32b67e2c2d561b991bdf2d7808de4f9c656e5a90/cmd/node/node.go#L508-L516).

**Comment by countvonzero** [comment]
> > i am not super sure about this. why does component need a custom function for extracting public key from signature?
> > it seems like a perfect use case for a global static function.
> 
> It is not static but changes during startup of the node based on the configuration (network prefix) that is loaded from the config. The global function is defined without prefix for tests [here](https://github.com/spacemeshos/go-spacemesh/blob/32b67e2c2d561b991bdf2d7808de4f9c656e5a90/common/types/nodeid.go#L17-L27) and is overwritten during startup [here](https://github.com/spacemeshos/go-spacemesh/blob/32b67e2c2d561b991bdf2d7808de4f9c656e5a90/cmd/node/node.go#L508-L516).

yes. but this function is not going to be used before the app initialization is finished. why not just do the following
```
var ExtractNodeIDFromSig = func(msg, sig []byte) (types.NodeID, error) {
	log.Fatal("uninitialized")
	return types.NodeID{}, errors.New("extractor not initialized")
}
```
and do the initialization in node.go as early as possible.

**Comment by countvonzero** [comment]
i simply don't understand the need having to pass key extractor to all components when a global static function would do.

**Comment by fasmat** [comment]
> why not just do the following ... and do the initialization in node.go as early as possible.

Then we would also need to set this function in many tests - at least tests that use ATXs, Ballots, or Proposals - or those tests would fail.

Why not make it injectable? Then it can be mocked (currently not a requirement, but might be interesting in the future). 

> i simply don't understand the need having to pass key extractor to all components when a global static function would do.

It is weird to me that `signing.EdSigner` is used via injection, but `signing.KeyExtractor` is not. The former is instantiated during startup and passed into all services, the later is also instantiated during startup and then set as value to a global variable?

Another argument against making it a global function is that we then have a tightly coupled dependency between the package where the function is defined (`common/types`) and any other package that sets or uses that function. Injecting loosens up that coupling.

The primary reason this function exists at the moment is to break up a cyclic dependency. `signing` depends on `common/types` but `ExtractNodeIDFromSig` (or at least the implementation that is set during node startup) is dependent on the `signing` package.

**Comment by countvonzero** [comment]
> Why not make it injectable? Then it can be mocked (currently not a requirement, but might be interesting in the future).

i don't believe in injecting crypto.... the only tangible reason would be speeding up the tests.

> It is weird to me that signing.EdSigner is used via injection, but signing.KeyExtractor is not. The former is instantiated during startup and passed into all services, the later is also instantiated during startup and then set as value to a global variable?

i don't see why symmetry here is important. signing is for the node itself, so instead of reading the private key multiple times, you read it once and pass it to components that signs. 

key extractor is a generic functions that extract public key from signatures. a global function that gets initialized once and all components just use it.

> Another argument against making it a global function is that we then have a tightly coupled dependency between the package where the function is defined (common/types) and any other package that sets or uses that function. Injecting loosens up that coupling.

LOL. but which package now doesn't have a dependency on common/types?

> The primary reason this function exists at the moment is to break up a cyclic dependency. signing depends on common/types but ExtractNodeIDFromSig (or at least the implementation that is set during node startup) is dependent on the signing package.

could we move all things signing to common/types package then?

in any case, injecting signer and key extractor for me is more theoretical than practical. but i don't care that much.

**Review by countvonzero — APPROVED** [review]

**Comment by fasmat** [comment]
> but which package now doesn't have a dependency on common/types?

That's not what I meant. Yes, almost every package is dependent on `common/types` but it doesn't work without another package first defining what it does.

It is a hidden cyclic dependency. `cmd/node` depends on `common/types` as it should. But `common/types` depends on `cmd/node` to define what it does.

The reason when have to set this function during runtime and can't just implement it normally is because the complier would complain. Yes merging `signing` into `common/types` would be another way to resolve that issue. One that we both wouldn't be happy about I think 😉

Imo the underlying issue is the `common/types` package itself. In my opinion it shouldn't exist, but this is a whole other discussion and I don't want to open that can of worms just yet. 😕

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
