### PR TITLE
Self Hosted Runner for CI

### PR DESCRIPTION
**Pull request by web3rover**

### CODE REVIEW

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by narayanprusty** [comment]
bors try

**Comment by narayanprusty** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Comment by web3rover** [comment]
bors try

**Pull request closed without merging**
