### PR TITLE
tally command line tool to sanity check vm

### PR DESCRIPTION
**Pull request by dshulyak**
compile it and run with any address:

> ./tally -db state.sql -acc sm1qqqqqqpy8svgfxfhh2w42ujhrynsxgwsrrzgplss9t0lv
address=sm1qqqqqqpy8svgfxfhh2w42ujhrynsxgwsrrzgplss9t0lv
layer=27658
earned=1549272967127595
rewards=0
spent=1075931911672603
tally=473341055454992
account=473341055454992

### CODE REVIEW

**Comment by brunovale91** [comment]
@dshulyak do ineffective transaction have a status different from types.TransactionSuccess?

**Comment by dshulyak** [comment]
all effective transactions should have a result. transaction ineffective if it is included in the block and block was applied, but has no result (e.g field in db is null)

> select distinct id, tx, header, result 
		from transactions
		left join transactions_results_addresses on id=tid
		where result is not null

**Comment by brunovale91** [comment]
> all effective transactions should have a result. transaction ineffective if it is included in the block and block was applied, but has no result (e.g field in db is null)
> 
> > select distinct id, tx, header, result
> > from transactions
> > left join transactions_results_addresses on id=tid
> > where result is not null

Thanks for the explanation.

**Comment by fasmat** [comment]
Closing as this seems abandoned. @dshulyak feel free to re-open if needed 🙂

**Pull request closed without merging**
