### PR TITLE
[Merged by Bors] - invalidate proposals with empty eligibility list

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
