### PR TITLE
[Merged by Bors] - tortoisebeacon: remove mockery and move mocks to a separate directory

### PR DESCRIPTION
**Pull request by dshulyak**
## Motivation
I initially made this refactoring in ssz branch. Because sszgen can't work if in the same module other module imported in a different way, e.g. one file imports `"time"` and another `time "time"`.

I also replaced it by mockgen, since it is better to use single mock module across the same repo. 

Closes # https://github.com/spacemeshos/go-spacemesh/issues/2604

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by nkryuchkov — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
