### PR TITLE
[Merged by Bors] - code janitor: use one db instance to read data

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

combine various data sources (atxdb/meshdb/proposaldb) to one sql.Database instance with an optional atx cache

## Changes

- introduce datastore.CacheDB, which is a sql.Database with an ATX header cache. users should use plain vanilla sql.Database instance if they don't need to get atxs from database.
- delete atxdb.go, proposaldb.go, and meshdb.go. most of atxs.go is renamed to atx_handler.go
- use datastore.BlobStore to serve blob data for peer fetches
- mesh.go retains some wrapper API to database for api package

one caveat of this change is that db errors tests are removed, as all tests are now storing data into database directly. overall the simplified code out-weighs the coverage drop.

## Test Plan

unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
> Build failed:
> 
> * [ci-stage2](https://github.com/spacemeshos/go-spacemesh/runs/6989423150?check_suite_focus=true)

https://github.com/spacemeshos/go-spacemesh/issues/3212

**Pull request closed without merging**
