### PR TITLE
[Merged by Bors] - changed order of syntactic validation to not fail when fast validating

### PR DESCRIPTION
**Pull request by antonlerner**
changed order of syntactic validation to not fail when fast validating block with missing atx

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]

**Comment by antonlerner** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by antonlerner** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Pull request closed without merging**
