### PR TITLE
[Merged by Bors] - Add default PostService config to Testnet preset

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Adds the missing default values for the PostService config to the testnet preset

## Changes
- add default settings for PostService to testnet preset.

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
