### PR TITLE
[Merged by Bors] - Wrap most errors with additional context

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

Currently, many error logs are not descriptive enough. E.g., there're many errors like `$ERROR: leveldb: not found`, where it's not clear what's the origin of the error. Also, it's a good practice to wrap errors is Go. 

The PR wraps most of the errors with additional context. Most of them were found with the `wrapcheck` linter, the other part manually. There are still some unwrapped errors inside packages, but I'm not sure we need to wrap them. 

There also will be another PR, which adds the `wrapcheck` linter to the CI, so that we don't add new unwrapped errors.

## Changes

- Wrap most errors with additional context

## Test Plan

- Unit tests
- System tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try-

**Comment by nkryuchkov** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
i haven't used this linter before, but let's try. on a more general note maybe we should use module that adds a caller stack trace to the error message (https://pkg.go.dev/golang.org/x/xerrors#pkg-overview) , it usually very helpful during debugging

**Review by countvonzero — COMMENTED** [review]
hmmm... i am on the fence about this. when the codebase grows, there will be multiple layers of errors being wrapped, and the error becomes much less readable due to the added text.

i've seen code using https://pkg.go.dev/github.com/juju/errors that simply add file+line# to error.

**Comment by nkryuchkov** [comment]
@countvonzero Yes, the errors would be less readable because of more text, but easier to investigate because we'll see the error trace.

@dshulyak @countvonzero Having a stack trace is a great idea, but I think we can do that iteratively. This PR will make investigations of some errors way easier. We can add something more enhanced later.

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
