### PR TITLE
[Merged by Bors] - fixed stop start sync bug

### PR DESCRIPTION
**Pull request by antonlerner**
Sync panicked when closing after start

### CODE REVIEW

**Review by noamnelke — CHANGES_REQUESTED** [review]
I think we should use the `shutdown()` method instead of introducing a second mechanism that does the same thing.

The name of this method is **very** confusing, so it may be worth renaming it (e.g. `isClosed()`).

**Comment by AmitShaul** [comment]
bors try

**Review by noamnelke — APPROVED** [review]

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try-

**Comment by AmitShaul** [comment]
bors try-

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try

**Comment by AmitShaul** [comment]
bors try-

**Comment by AmitShaul** [comment]
bors try

**Comment by y0sher** [comment]
bors merge

**Comment by AmitShaul** [comment]
bors try

**Pull request closed without merging**
