### PR TITLE
[Merged by Bors] - tortoise: fix counting weight for late block

### PR DESCRIPTION
**Pull request by dshulyak**
previous "fast" solution wasn't counting abstain votes correctly

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by poszu — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
