### PR TITLE
[Merged by Bors] - hare3: increase round latency to 700ms in system tests

### PR DESCRIPTION
**Pull request by dshulyak**
other changes:
- fixed expected timestamp for latency histogram, it didn't subtract 1 because of the skipped round
- let hare3 run with debug logs

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
image

how this skip happened?

**Comment by dshulyak** [comment]
latency for bootnodes is significantly higher than everyone else, i assume that because of the configuration

image

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
image

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
