### PR TITLE
[Merged by Bors] - api: use stream context in subscriptions

### LINKED ISSUE #2984: api: some subscriptions are not using stream context
Some subscriptions are not listening to stream context and will continue to be subscribed even after the stream is terminated. It may lead to excessive memory usage if API client will re-create same stream many times erroneously.

```
./api/grpcserver/mesh_service.go
474:			txCh = consumeEvents(context.Background(), txsSubscription.Out())
480:			activationsCh = consumeEvents(context.Background(), activationsSubscription.Out())
551:		layerCh = consumeEvents(context.Background(), layersSubscription.Out())

./api/grpcserver/node_service.go
153:		statusCh = consumeEvents(context.Background(), statusSubscription.Out())
197:		errorsCh = consumeEvents(context.Background(), errorsSubscription.Out())

./api/grpcserver/transaction_service.go
186:		txCh = consumeEvents(context.Background(), txsSubscription.Out())
192:		layerCh = consumeEvents(context.Background(), layersSubscription.Out())
```

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

Closes #2984

## Changes

- use stream context in subscriptions

## Test Plan

UT

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
kibana failure

bors merge

**Pull request closed without merging**
