### PR TITLE
[Merged by Bors] - parametrize inbound/outbound fractions for experiments

### PR DESCRIPTION
**Pull request by dshulyak**
i want to run some experiments on bootnodes, once network stabilizes i will
simplify configuration, as it is right now quite overloaded

### CODE REVIEW

**Review by countvonzero — APPROVED** [review]
lol. that was the only thing i wanted to suggest earlier.

**Comment by dshulyak** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
