### PR TITLE
[Merged by Bors] - Update python pipfile dependencies

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation

Silence dependabot alert re: httplib2 and invalid (prerelease) version of pyyaml: https://github.com/spacemeshos/go-spacemesh/security/dependabot/tests/Pipfile.lock/httplib2/open

## Changes
Upgrade to latest versions of these two libraries

## Test Plan
N/A, this is just for system tests

### CODE REVIEW

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors ping

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try-

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try-

**Comment by lrettig** [comment]
bors try

**Review by noamnelke — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
