### PR TITLE
[Merged by Bors] - Update dependencies

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
This integrates the changes from https://github.com/spacemeshos/poet/pull/129 and the latest changes in https://github.com/spacemeshos/post/ into go-spacemesh

## Changes
- Update dependencies of go-spacemesh
- Remove unused util functions
- Re-enable some PoET tests on windows: with the most recent PoET changes these pass now

## Test Plan
Existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by poszu — APPROVED** [review]
Please close the bug tickets for windows tests after merging :)

**Comment by fasmat** [comment]
bors mege

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
