### PR TITLE
load config parameters from external file or command line params.

### PR DESCRIPTION
**Pull request by y0sher**
added urfave/cli.v1/altsrc, added a function to cast ints to uints during config reading. TODO: durations still bug the whole thing.

NOTE: 
This is probably going to be rewritten with different approach since the limits we have using the built in functionality of the cli lib.
ref: https://github.com/spacemeshos/go-spacemesh/issues/7 , 
https://github.com/spacemeshos/go-spacemesh/issues/20

### CODE REVIEW

**Comment by avive** [comment]
@y0sher - to clarify - is the only issue now parsing duration data type or are there issues with other data types?

**Comment by y0sher** [comment]
the presence of a value in the config record that maps to a DurationFlag will cause other values to not load. (will fail because expected duration and got string/int)
though with the casting code I added the duration flags (and uints which I did the same to) will eventually load. ( but the rest will not )

some other limitations the cli library has regarding config file loading right now :
- We must use the names we use as flag names in the toml file. that means we can't use multiple names as 'flagname, fn' for command line parsing
- Using sections doesn't work

**Comment by avive** [comment]
So are we good as long as we don't use uints and durations for now? If yes, then I think it is ok and we can always parse ints or floats when needed. Not ideal but workable for the short-term. Also not great not being able to use short field names but still workable. I think we should avoid moving away from cli for now as it still gives us lots of cool functionality. Thoughts?

**Comment by y0sher** [comment]
If short term is a priority and everything mentioned is workable. I guess we can do it.
The other option is use the library cli uses for toml parsing and map the values by ourselves.

I'll play with the first option for now and see how it goes.

**Comment by avive** [comment]
I think this is a good idea.

**Comment by avive** [comment]
This is great - I'll checkout the PR and play with it to get a fill of these changes. In the meantime please see: https://travis-ci.org/spacemeshos/go-spacemesh/jobs/333512093 . We added golint as a build step yesterday and it is fairly strict about us properly documenting every package exported type.

**Comment by y0sher** [comment]
thanks for the review, I did all the changes :). 
Tried to write a test to mimic our app as close as possible. found out string slice loading isn't working as well during writing the test so they can be loaded only from command line for now ( bootstrap nodes).

**Comment by avive** [comment]
Great! is this ready for final review & merging or are there still more to do for this task?

**Comment by y0sher** [comment]
It is ready for review. String slices parsing is the only thing not
working. But that's again with bug with the cli library.

On 28 Jan 2018 7:25, "Aviv Eyal" <notifications@github.com> wrote:

Great! is this ready for final review & merging or are there still more to
do for this task?

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/spacemeshos/go-spacemesh/pull/69#issuecomment-361039406>,
or mute the thread

**Comment by avive** [comment]
Thanks for this. LGTM!

**Pull request merged**
