### PR TITLE
[Merged by Bors] - use native chaos-mesh templates for longevity network

### LINKED ISSUE #3703: systest: flexible chaos-mesh tasks scheduler
for https://github.com/spacemeshos/pm/issues/184

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/go-spacemesh/issues/3703

i dropped idea of writing a separate scheduler for chaos tasks, this change basically
reuses chaos-mesh natively.

how to use it:
- deploy a cluster of a particular configuration and size. the size can't change, because labels are used to setup chaos-mesh conditions, and chaos-mesh doesn't watch updates.
- cluster is partitioned in 10 buckets. to run specific chaos conditions on the node in the specific bucket (for example short disconenct - 0, failure - 1, long disconnect - 2). see how buckets are used in systest/parameters/chaos
- additional workload can be also scheduled on the cluster, see TestScheduleTransactions for an example

### CODE REVIEW

**Review by countvonzero — COMMENTED** [review]
can you update the README doc and provide sample commands to run chaos test?

i assume CI sanity tests are still using the chaos library?

**Comment by dshulyak** [comment]
@countvonzero updated

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
