### PR TITLE
[Merged by Bors] - [backport] P2P decentralization improvements

### PR DESCRIPTION
**Pull request by ivan4th**
This is a backport of #5329.
It also includes changes from #5287 to avoid conflicts and updates `go-libp2p` to a more recent version.

### CODE REVIEW

**Comment by ivan4th** [comment]
This PR requires https://github.com/spacemeshos/api/pull/293 to be merged first in the `api` repo, after which `v1.21.1` release of the `api` repo needs to be tagged, and `go.mod` needs to be updated accordingly in this PR.

**Review by dshulyak — APPROVED** [review]

**Comment by ivan4th** [comment]
`windows-latest` test failure appears to be unrelated to the PR, rerunning failed jobs:
```
=== FAIL: node TestPeerInfoApi (4.69s)
2023-12-25T17:20:06.250Z	WARN	00000.defaultLogger	attempt to SetLevel of logger lower than parent level, this may result in log entries being dropped silently
    adminservice_api_test.go:61: 
        	Error Trace:	D:/a/go-spacemesh/go-spacemesh/node/adminservice_api_test.go:61
        	Error:      	"0s" is not greater than "0s"
        	Test:       	TestPeerInfoApi
        	Messages:   	uptime should be set
```

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
Same failure in the test run w/o d14n changes, so trying another time...
https://github.com/spacemeshos/go-spacemesh/actions/runs/7330671330/job/19962145193

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
MacOS test flake this time
```
=== FAIL: txs TestCache_Account_Add_UpdateHeader (0.01s)
    cache_test.go:644: 
        	Error Trace:	/Users/runner/work/go-spacemesh/go-spacemesh/txs/cache_test.go:644
        	Error:      	Target error should be in err chain:
        	            	expected: "bad nonce"
        	            	in chain: 
        	Test:       	TestCache_Account_Add_UpdateHeader
```

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
Systests:
```
=== NAME  TestPartition_30_70
    logger.go:130: 2023-12-29T17:42:14.927Z	ERROR	TestPartition_30_70	client state differs from ref state	***"client": "smesher-12", "ref_client": "boot-0", "layer": 18, "client_hash": "0x0000000000000000000000000000000000000000000000000000000000000000", "ref_hash": "0x50dfb24d60ad37f00b391da907af53ca47cde9d14f8280bce2fd89ae70e41a10"***
    partition_test.go:167: 
        	Error Trace:	/build/systest/tests/partition_test.go:167
        	            				/build/systest/tests/partition_test.go:182
        	Error:      	Should be true
        	Test:       	TestPartition_30_70
    logger.go:130: 2023-12-29T17:42:14.949Z	INFO	TestPartition_30_70	namespace was deleted	***"namespace": "test-ihxo"***
--- FAIL: TestPartition_30_70 (922.95s)
```
IIRC this was not observed before, let's consider it a flake

**Comment by ivan4th** [comment]
bors merge

**Pull request closed without merging**
