### PR TITLE
[Merged by Bors] - Node to PoET communication to use HTTP instead of gRPC

### LINKED ISSUE #1716: Node to PoET communication to use HTTP instead of gRPC
# Overview / Motivation
Offshoot from https://github.com/spacemeshos/poet/pull/86

# The Task
Replace gRPC communication with plain HTTP when calling from node to PoET service so that
1. Node won't keep an open connection between consecutive calls
2. https://github.com/spacemeshos/go-spacemesh/issues/1715 would be easier to implement 

The PoET server already provides HTTP gateway, so the underlying gRPC server doesn't need to change.

### PR DESCRIPTION
**Pull request by moshababo**
## Motivation

Closes https://github.com/spacemeshos/go-spacemesh/issues/1716

## Changes
Node to PoET communication changed to use HTTP instead of gRPC.
Tests which depends on PoET harness instance were also updated - they are now using the new HTTP client instead of native gRPC one.

### CODE REVIEW

**Comment by noamnelke** [comment]
I see that Travis is failing with:
```
2020-02-03T15:14:28.075Z	ERROR	e9901.atxBuilder   	failed to publish ATX	{"node_id": "e9901", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-03T15:14:28.076Z	ERROR	f988a.atxBuilder   	failed to publish ATX	{"node_id": "f988a", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-03T15:14:28.076Z	ERROR	ab93a.atxBuilder   	failed to publish ATX	{"node_id": "ab93a", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-03T15:14:28.076Z	ERROR	c5c9f.atxBuilder   	failed to publish ATX	{"node_id": "c5c9f", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-03T15:14:28.076Z	ERROR	b8e32.atxBuilder   	failed to publish ATX	{"node_id": "b8e32", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
```

At first I thought this was a Travis only issue, but I get the exact same error locally.

<details>
<summary>Local log</summary>

```
2020-02-04T10:00:04.007+0200	ERROR	f8c1c.atxBuilder   	failed to publish ATX	{"node_id": "f8c1c", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-04T10:00:04.007+0200	ERROR	c6d7c.atxBuilder   	failed to publish ATX	{"node_id": "c6d7c", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-04T10:00:04.007+0200	ERROR	10bfb.atxBuilder   	failed to publish ATX	{"node_id": "10bfb", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-04T10:00:04.008+0200	ERROR	82348.atxBuilder   	failed to publish ATX	{"node_id": "82348", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
2020-02-04T10:00:04.009+0200	ERROR	40733.atxBuilder   	failed to publish ATX	{"node_id": "40733", "error": "failed to build nipst: failed to submit challenge to poet service: response status code: 500, body: {\"error\":\"round is not open\",\"message\":\"round is not open\",\"code\":2}"}
```
</details>

So I guess it doesn't fully work yet?

**Comment by moshababo** [comment]
Sorry, I overlooked these log lines, and thought that the test failure is part of the test general flakiness. 

Now fixed.

**Comment by moshababo** [comment]
bors try

**Review by noamnelke — APPROVED** [review]

**Comment by moshababo** [comment]
bors merge

**Comment by moshababo** [comment]
bors merge

**Pull request closed without merging**
