### PR TITLE
[Merged by Bors] - Bump post to v0.12.4 and post-rs to v0.7.4

### PR DESCRIPTION
**Pull request by poszu**
## Motivation

Bump post to version that contains fix for slow init on Windows.

## Description

- bumps post to v0.12.4
- bumps post-rs to v0.7.4

## Test Plan

- existing tests pass
- verified the fix with the community 

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Review by fasmat — APPROVED** [review]
Will you also add to the changelog that this fixes slow init? 😊

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
