### PR TITLE
[WIP] Make API tests (GRPC and HTTP) run faster

### LINKED ISSUE #560: Make API tests (GRPC and HTTP) run less time
# Overview / Motivation
Currentlly the api tests take 15 seconds, this is partially because of loading the GRPC and HTTP servers takes time for each test.
# The Task
Refactor the tests in a way that same code coverage remains but test run faster. 
Make grpc and http test run in a test testify suite, so that the actual loading of grpc and http servers happen only once 

# Implementation Notes
look into api/api_test.go
Check out testify test suite:
https://github.com/stretchr/testify

# Time estimation
8 hours (1 day)

# Contribution Guidelines
Important: Issue assignment to developers will be by the order of their application and proficiency level according to the tasks complexity. We will not assign tasks to developers who have'nt introduced themselves on our Gitter [dev channel](https://gitter.im/spacemesh-os/Lobby)

1. Introduce yourself on go-spacemesh [dev chat channel](https://gitter.im/spacemesh-os/Lobby) - ask our team any question you may have about this task
2. Fork branch `develop` to your own repo and work in your repo
3. You must document all methods, enums and types with [godoc comments](https://blog.golang.org/godoc-documenting-go-code)
4. You must write go unit tests for all types and methods when submitting a component, and integration tests if you submit a feature
5. When ready for code review, submit a PR from your repo back to branch `develop`
6. Attach relevant issue to PR

### PR DESCRIPTION
**Pull request by ransonhobbes**
Fixes #560

Opening a PR now to track a work in progress issue. Please do not merge yet!

### CODE REVIEW

**Comment by y0sher** [comment]
Hi ! Thanks for contiributing, nice work so far, though @antonlerner is working on refactoring this code as well. it'll be good if you guys can collaborate! @antonlerner please take a look.

**Comment by ransonhobbes** [comment]
@y0sher thanks for the heads up. @antonlerner please let me know if it makes sense for me to continue working on this.

**Comment by antonlerner** [comment]
hey @ransonhobbes , yes, we'd love to optimise these functions a bit, we are refactoring code and adding some tests for more API's but I don't think it will affect your pr, perhaps merging will be a bit tricky but we're game if your'e up for it

**Comment by antonlerner** [comment]
@ransonhobbes do you still want to keep working on this issue?

**Comment by antonlerner** [comment]
closed due to inactivity

**Pull request closed without merging**
