### PR TITLE
[Merged by Bors] - dont pass interuptible context to with tx

### PR DESCRIPTION
**Pull request by dshulyak**
interrupting connection in the middle of writes doesn't rollback transaction, and leads to future writes deadlocking.
it probably needs to be removed from Tx/WithTx API at all, it is only safe to use with single statement.

```
{"L":"WARN","T":"2024-03-15T21:22:15.583Z","N":"node.sync","M":"background atx sync failed","sessionId":"b4540da2","epoch_id":5,"errmsg":"failed to persist state for epoch 5: insert synced atx id 5/f34cac63b5 failed: prepare insert into atx_sync_state \n\t\t(epoch, id, requests) values (?1, ?2, ?3)\n\t\ton conflict(epoch, id) do update set requests = ?3;: sqlite.Stmt.ClearBindings: SQLITE_INTERRUPT (insert into atx_sync_state \n\t\t(epoch, id, requests) values (?1, ?2, ?3)\n\t\ton conflict(epoch, id) do update set requests = ?3;)","name":"sync"}

{"L":"WARN","T":"2024-03-15T21:23:15.606Z","N":"node.sync","M":"background atx sync failed","sessionId":"0d233121","epoch_id":6,"errmsg":"failed to persist state for epoch 6: begin: sqlite.Stmt.Step: SQLITE_BUSY: database is locked (BEGIN IMMEDIATE;)","name":"sync"}  
{"L":"WARN","T":"2024-03-15T21:24:15.621Z","N":"node.sync","M":"background atx sync failed","sessionId":"a2b64219","epoch_id":7,"errmsg":"failed to persist state for epoch 7: begin: sqlite.Stmt.Step: SQLITE_BUSY: database is locked (BEGIN IMMEDIATE;)","name":"sync"}
{"L":"WARN","T":"2024-03-15T21:25:15.640Z","N":"node.sync","M":"background atx sync failed","sessionId":"e9039bf3","epoch_id":8,"errmsg":"failed to persist state for epoch 8: begin: sqlite.Stmt.Step: SQLITE_BUSY: database is locked (BEGIN IMMEDIATE;)","name":"sync"}
```

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by fasmat** [comment]
I'm not sure I fully understand the cause of the issue, shouldn't canceling the `context.Context` to `WithTx` cause the transaction to be aborted and rolled back? Would changing `BEGIN IMMEDIATE` in `WithTx` to `BEGIN` (deferred) make sense?

**Review by fasmat — APPROVED** [review]

**Comment by dshulyak** [comment]
>  Would changing BEGIN IMMEDIATE in WithTx to BEGIN (deferred) make sense?

we will acquire lock with the first write. once that lock acquired, context that is used for connection can be canceled the same way as in that failure and tx will be interrupted again without releasing a lock. 

to release a lock it needs to execute ROLLBACK, but it is not executed because this step gets interrupted too https://github.com/spacemeshos/go-spacemesh/blob/develop/sql/database.go#L468-L470

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
m2pro job stuck, but system tests passed

**Comment by fasmat** [comment]
then lets merge it 🚀

**Review by ivan4th — APPROVED** [review]
Looks good, but it's worth noting there are other places where interruptible context is used with transactions in this way, e.g. https://github.com/spacemeshos/go-spacemesh/blob/b09651a8801588059541dc2ceeb0dab386939921/blocks/certifier.go#L552

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
