### PR TITLE
[Merged by Bors] - make sure layer blocks are fetched

### LINKED ISSUE #2797: sync: layerfetcher should report error fetching block and cause sync to fail
## Description

when adding a new node to an existing network, the node syncs one layer at a time. but layerfetcher doesn't report error when it failed to fetch a block.

https://github.com/spacemeshos/go-spacemesh/blob/398211f24e862300dab8a3414bdcb64ed7a50316/layerfetcher/layers.go#L286

this will cause the node to validate a layer with incomplete data.

## Steps to reproduce
- start a node
- make internet connection unstable 

## Actual Behavior
the node ignores the fetch error and process the layer with incomplete content

## Expected Behavior

the node should fail sync immediately

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

Closes #2797

## Changes

double-check at the end of polling layer content and make sure all blocks are fetched

instead of checking individual call to fetchLayerBlocks, we wait until the end of polling layer to make sure all blocks are fetched.
this is because when some fetchLayerBlocks calls fail, others calls may succeed.

## Test Plan

unit tests

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Comment by dshulyak** [comment]
what if we send this request (fetchLayerBlocks) to the node that itself is not fully synced and it returns only half of the blocks and empty input vector for example? will we count this layer as synced and move on?

**Comment by dshulyak** [comment]
> what if we send this request (fetchLayerBlocks) to the node that itself is not fully synced and it returns only half of the blocks and empty input vector for example? will we count this layer as synced and move on?

looks like this is a problem only if all peers are in such state

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
> looks like this is a problem only if all peers are in such state

yeah. this is not the most efficient fix. the low level fetcher should take care of retrying hash across the peers (currently 20 times).

let me merge this first, and follow up with an improvement that also fix https://github.com/spacemeshos/go-spacemesh/issues/2796

**Comment by countvonzero** [comment]
@dshulyak also in general we should drop a peer if the peer is less synced than we are when catching up. if you agree, i will open a separate issue

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
