### PR TITLE
[Merged by Bors] - Make dependabot ignore libp2p libs

### PR DESCRIPTION
**Pull request by ivan4th**
## Motivation

libp2p/go-libp2p#2793 broke observed address handling and consequently routing discovery mechanism, too.
This is not the first time we're having problems because of (semi-)automatic libp2p dependency updates.
Prerequisite for re-enabling automatic updates of libp2p libs: QUIC and routing discovery systests

## Description

Add dependabot exception for libp2p libraries

### CODE REVIEW

**Comment by fasmat** [comment]
Please add a comment to the dependabot file and add an issue for adding system tests with QUIC such that we enable it again. I want to avoid falling too far behind with dependency updates.

Has the problem been reported to libp2p? I don't see an issue that mentions that problem in the libp2p repository?

**Comment by pigmej** [comment]
@fasmat https://github.com/libp2p/go-libp2p/pull/2825 :)

**Comment by fasmat** [comment]
@pigmej well there were a few hours between my comment and the creation of the PR 😉 

then this PR isn't needed any more is it? the fix was already approved and will (probably) land in the next libp2p release. We only need to downgrade it now, close the PR dependabot creates for `v0.34.0` to ignore that version and integrate the next version of libp2p?

**Comment by ivan4th** [comment]
This PR is still needed as that's not the first instance of a libp2p update breaking go-spacemesh.
I've added a comment to `dependabot.yml` regarding when we can re-enable dependabot for libp2p libraries

**Review by fasmat — APPROVED** [review]
If we don't have it already we should also create an issue to create the systests we need and include the information to enable `libp2p` updates again when they are implemented 🙂

**Comment by ivan4th** [comment]
> If we don't have it already we should also create an issue to create the systests we need and include the information to enable `libp2p` updates again when they are implemented 🙂

Done: #6025

**Comment by fasmat** [comment]
bors merge

**Comment by ivan4th** [comment]
bors merge

**Pull request closed without merging**
