### PR TITLE
[Merged by Bors] - updated PR template

### PR DESCRIPTION
**Pull request by web3rover**
## Motivation

This will help us to be aware of compatibility issues before we release a new testnet. @narayanprusty Will go through  all the PRs before testnet release and upgrade infrastructure components if needed. 

These points were suggested by @noamnelke based on past experience with compatibility issues during testnet releases.

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]

**Comment by web3rover** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors try

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
