### PR TITLE
[Merged by Bors] - Update dependencies not checked by dependabot

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Updates dependencies not covered by dependabot (libraries without tagged versions)

## Changes
- Update `github.com/chaos-mesh/chaos-mesh/api`
- Update `github.com/oasisprotocol/curve25519-voi`

## Test Plan
existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by dshulyak** [comment]
> github.com/oasisprotocol/curve25519-voi

we should check if there was no changes. in the past ecvrf that we use was updated because rfc changed. maybe compile and run on mainnet?

**Comment by fasmat** [comment]
> > github.com/oasisprotocol/curve25519-voi
> 
> we should check if there was no changes. in the past ecvrf that we use was updated because rfc changed. maybe compile and run on mainnet?

Fair point. I checked the diff; it is only two commits: https://github.com/oasisprotocol/curve25519-voi/compare/db37f07504ce...1f23a7b

No existing code was changed, just new functionality added 🙂

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
