### PR TITLE
[Merged by Bors] - p2p: make AutoNAT service limits configurable

### PR DESCRIPTION
**Pull request by ivan4th**
## Motivation
With current AutoNAT service limits, many nodes can't request dialback and determine their reachability status. This means they keep DHT in server mode even if they're behind NAT, and that in turn leads to "poisoning" of DHT with many unreachable peers

## Changes
Add `"auto-nat-server"` section to the p2p config

## Test Plan
Verified it on a mainnet node

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
systests failed -- `TestSmeshing` flaked:
```
     transactions_test.go:81: 
        	Error Trace:	/build/systest/tests/transactions_test.go:81
        	            				/build/systest/tests/smeshing_test.go:47
        	Error:      	Not equal: 
        	...
```
https://github.com/spacemeshos/go-spacemesh/actions/runs/7619289424/job/20752101622#step:15:354

retrying

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
`windows-latest` tests flaked:

```
    nipost_test.go:198: 
        	Error Trace:	D:/a/go-spacemesh/go-spacemesh/activation/e2e/nipost_test.go:198
        	Error:      	Received unexpected error:
        	            	poet service is unstable: getBestProof failed (builder: didn't receive any poet proof)
        	Test:       	TestNIPostBuilderWithClients
```

**Comment by ivan4th** [comment]
bors merge

**Pull request closed without merging**
