### PR TITLE
[Merged by Bors] - Update libp2p and libp2p-pubsub

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

Updates libp2p and libp2p-pubsub.

## Description

Only update libp2p and libp2p-pubsub to most recent versions.

## Test Plan

existing tests pass.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Review by ivan4th — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Review by acud — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
