### PR TITLE
Setup windows toolchain

### LINKED ISSUE #2626: Windows Binary Build Not Working
## Description
Unable to build `go-spacemesh` binary on windows. `make build` gives error.

## Steps To Reproduce
1. Go to 'Command Prompt'
2. Run 'make build'
3. You will get error

I have also tried using msys2(https://www.msys2.org/) but still getting different set of errors.

## Expected Behavior
Should be able to build go-spacemesh binary on Windows

## Additional Resources 
I get this error on command prompt:

```
"OS: Windows_NT, HOST_OS: windows, GOOS: windows, GOARCH: , BIN_DIR: C:/Users/narayan/Desktop/go-spacemesh/build/, platform: windows"
mkdir -p C:/Users/narayan/Desktop/go-spacemesh/build/
The syntax of the command is incorrect.
make: *** [Makefile.Inc:56: C:/Users/narayan/Desktop/go-spacemesh/build/gpu-setup.dll] Error 1
```

And this when using msys

```
"OS: Windows_NT, HOST_OS: windows, GOOS: windows, GOARCH: , BIN_DIR: /home/narayan/go-spacemesh/build/, platform: windows"
mkdir -p /home/narayan/go-spacemesh/build/
unzip -o /home/narayan/go-spacemesh/libgpu-setup-windows-0.1.21.zip -d /home/narayan/go-spacemesh/build/ gpu-setup.dll
Archive:  /home/narayan/go-spacemesh/libgpu-setup-windows-0.1.21.zip
  inflating: /home/narayan/go-spacemesh/build/gpu-setup.dll
touch /home/narayan/go-spacemesh/build/gpu-setup.dll
/bin/sh: line 1: type: version.txt: not found
go build -o /home/narayan/go-spacemesh/build/go-spacemesh.exe -ldflags "-X main.version= -X main.commit=68e5ab74a7c429fa933ce0e9437ea6ff2879f596 -X main.branch=develop"  .
# internal/unsafeheader
compile: version "go1.15.4" does not match go tool version "go1.16"
# runtime/internal/sys
compile: version "go1.15.4" does not match go tool version "go1.16"
# math/bits
compile: version "go1.15.4" does not match go tool version "go1.16"
# unicode/utf8
compile: version "go1.15.4" does not match go tool version "go1.16"
# runtime/internal/atomic
flag provided but not defined: -compiling-runtime
usage: asm [options] file.s ...
Flags:
  -D value
        predefined symbol with optional simple value -D=identifier=value; can be set multiple times
  -I value
        include directory; can be set multiple times
  -S    print assembly and machine code
  -V    print version and exit
  -debug
        dump instructions as they are parsed
  -dynlink
        support references to Go symbols defined in other shared libraries
  -e    no limit on number of errors reported
  -gensymabis
        write symbol ABI information to output file, don't assemble
  -go115newobj
        use new object file format (default true)
  -o string
        output file; default foo.o for /a/b/c/foo.s as first argument
  -p string
        set expected package import to path
  -shared
        generate code that can be linked into a shared library
  -spectre list
        enable spectre mitigations in list (all, ret)
  -trimpath string
        remove prefix from recorded source file paths
# internal/race
compile: version "go1.15.4" does not match go tool version "go1.16"
# internal/cpu
compile: version "go1.15.4" does not match go tool version "go1.16"
# unicode
compile: version "go1.15.4" does not match go tool version "go1.16"
# internal/syscall/windows/sysdll
compile: version "go1.15.4" does not match go tool version "go1.16"
# unicode/utf16
compile: version "go1.15.4" does not match go tool version "go1.16"
# encoding
compile: version "go1.15.4" does not match go tool version "go1.16"
# sync/atomic
compile: version "go1.15.4" does not match go tool version "go1.16"
# container/list
compile: version "go1.15.4" does not match go tool version "go1.16"
# golang.org/x/sys/internal/unsafeheader
compile: version "go1.15.4" does not match go tool version "go1.16"
# internal/nettrace
compile: version "go1.15.4" does not match go tool version "go1.16"
# crypto/internal/subtle
compile: version "go1.15.4" does not match go tool version "go1.16"
# crypto/subtle
compile: version "go1.15.4" does not match go tool version "go1.16"
# vendor/golang.org/x/crypto/cryptobyte/asn1
compile: version "go1.15.4" does not match go tool version "go1.16"
# vendor/golang.org/x/crypto/internal/subtle
compile: version "go1.15.4" does not match go tool version "go1.16"
# golang.org/x/crypto/internal/subtle
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/seehuhn/mt19937
compile: version "go1.15.4" does not match go tool version "go1.16"
# google.golang.org/protobuf/internal/flags
compile: version "go1.15.4" does not match go tool version "go1.16"
# google.golang.org/grpc/serviceconfig
compile: version "go1.15.4" does not match go tool version "go1.16"
# golang.org/x/crypto/salsa20/salsa
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/spacemeshos/go-spacemesh/hare/eligibility/config
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/spacemeshos/go-spacemesh/hare/config
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/pyroscope-io/pyroscope/pkg/agent/debugspy
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/pyroscope-io/pyroscope/pkg/agent/rbspy
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/pyroscope-io/pyroscope/pkg/agent/pyspy
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/pyroscope-io/pyroscope/pkg/agent/ebpfspy
compile: version "go1.15.4" does not match go tool version "go1.16"
# golang.org/x/text/encoding/internal/identifier
compile: version "go1.15.4" does not match go tool version "go1.16"
# github.com/pyroscope-io/pyroscope/pkg/util/slices
compile: version "go1.15.4" does not match go tool version "go1.16"
# golang.org/x/net/html/atom
compile: version "go1.15.4" does not match go tool version "go1.16"
# golang.org/x/text/internal/utf8internal
compile: version "go1.15.4" does not match go tool version "go1.16"
# runtime/cgo
compile: version "go1.15.4" does not match go tool version "go1.16"
make: *** [Makefile:99: go-spacemesh] Error 2

```

### PR DESCRIPTION
**Pull request by sudachen**
## Instruction (can be added into README.md also)

**To build go-spacemesh on Windows all you need is Msys2**

1. Install msys2 from https://www.msys2.org/ and update it.
Update is not necessary but strongly recommended, for update you can do next: 
* Run Msys2 shell (press Win-key once and type msys2)
* Update msys base `pacman -Syu --noconfirm`
* Run Msys2 shell again if it closed after update (it's OK)
* Update msys `pacman -Su --noconfirm`

2. To setup windows toolchain run Msys2 shell and and do next: 
* Install git and make `pacman -S git make --noconfirm`
* Clone go-spacemesh repo `git clone https://github.com/spacemeshos/go-spacemesh`
* Go to go-spacemesh folder `cd go-spacemesh`
* Run once `make setup-windows-toolchain`

3. To build go-spacemesh run Msys2 shell and do next:
* Clone/Checkout required go-spacemesh branch
* Run `make` in the go-spacemesh folder

Do not forget install VisualC++ runtime if you don't have it installed. It's used by gpu-setup.dll
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

## Motivation
Build apps with CGO on Windows is not trivial so this PR adds target into the Makefile to setup build environment.

Closes #2626

## Changes

It adds new target `setup-windows-toolchain` to setup windows go/gcc toolchain.

### CODE REVIEW

**Comment by avive** [comment]
This sounds similar to my manual Win 10 pro setup. I'm going to try the instructions on a windows 10 pro machine and provide feedback as soon as I'm able to do so.

**Comment by avive** [comment]
I've followed the instructions and it mostly works - I was able to build ok on win 10 pro with some caveats. See below.

> 1. Install msys2 from https://www.msys2.org/ ad update it.
>    Update is not necessary but strongly recomended:

- I assume you update it using the instructions you provide below - please clarify it.
- an -> and
- recomended -> recommended

> * Run Msys2 shell (press Win-key once and type msys)

On my system you need to type `msys2` to open the msys shell, and `msys` command doesn't work.

> Do not forget install VisualC++ 2015 runtime if you don't have it installed. It's used by gpu-setup.dll
> https://www.microsoft.com/en-us/download/details.aspx?id=52685

Ok, so my system had 3 c++ redists: 2008, and 2015-2019 (x64) and 2015-2019 (x86) so VC++ runtime fails to install over these (one has to dig into install logs to find out why in typical ms UX). Are we sure want to ask users to install this ancient runtime? Won't the 2015-2019 runtime work? Ideally we can ask users to install the latest VC++ runtime and it will work.

@moshababo @sudachen

**Review by avive — CHANGES_REQUESTED** [review]
See my request for changes and questions here: https://github.com/spacemeshos/go-spacemesh/pull/2771#issuecomment-916035915

**Comment by sudachen** [comment]
Really, user must have any VC140 compatible runtime. By default, windows10 does not have it. So, Yes, VC2019 will work well.

I'm not sure why searching in menu does not work with just typing msys, however, yes, msys2 must work well too.

**Comment by avive** [comment]
so we need to recommend the most recent vc++ runtime that ms makes available that will work.

**Comment by sudachen** [comment]
I will check it on clean system with VC2019 runtime today, to be sure.

**Comment by sudachen** [comment]
bors try

**Pull request closed without merging**
