### PR TITLE
[Merged by Bors] - Return correct `Fee` field from mesh API

### PR DESCRIPTION
**Pull request by noamnelke**
## Motivation
We currently return the `GasLimit` field in transactions from the mesh service - this field is unused. Conversely, the actual `Fee` field is returned nowhere.

## Changes
Return `Fee` instead of `GasLimit` in transactions from the mesh service.

## Test Plan
No actual code changes - no need to update tests.

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [ ] This PR does not affect public APIs - **the correct Fee field is now returned**
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by lrettig — APPROVED** [review]
lgtm

**Review by brusherru — APPROVED** [review]

**Comment by moshababo** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Pull request closed without merging**
