### PR TITLE
[Merged by Bors] - janitor: preparing hare for changes

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation

preparing for hare v1 changes

## Changes
- rename variables and reduce log msg
- replace util.Closer with context
- use errgroup to manage goroutine
- remove priority queue for gossip handling

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
