### PR TITLE
[Merged by Bors] - Run test coverage in CI and upload to codecov.io

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
We should track code coverage

## Changes
- added `coverage` job in CI
- uploading coverage to codecov.io. Check out https://app.codecov.io/github/spacemeshos/go-spacemesh

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by dshulyak** [comment]
it doesn't print a fair percentage for vm :( templates are tested using vm interface

**Comment by countvonzero** [comment]
@poszu where can i see the data? do i need to sign in/log in?

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
> @poszu where can i see the data? do i need to sign in/log in?

https://app.codecov.io/github/spacemeshos/go-spacemesh. It should work w/o signing in.

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
