### PR TITLE
[Merged by Bors] - Fix typos

### PR DESCRIPTION
**Pull request by vuittont60**
## Changes
fix typos

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
Thanks for your contribution!

bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
i will merge it after my change

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
