### PR TITLE
Remove restriction to run tests on a single core

### LINKED ISSUE #2925: Run unit tests for each package in parallel
## Description

Currently `make test` uses the `-p 1` flag which doesn't allow executing more than one test in parallel. Therefore, unit tests take too long to execute. By default, tests for all packages are run in parallel, where tests in each package are run one by one. This would reduce our test runs by a lot. However, if we remove the flag and test packages in parallel, some tests start failing with these errors:

```
=== RUN   TestValidator_Validate
    nipost_test.go:223: 
        	Error Trace:	nipost_test.go:223
        	            				nipost_test.go:347
        	Error:      	Received unexpected error:
        	            	builder: poet service is unstable: failed to get PoET service ID: response status code: 500, body: {"error":"service not started","code":2,"message":"service not started"}
        	Test:       	TestValidator_Validate
    nipost_test.go:203: 
        	Error Trace:	nipost_test.go:203
        	            				panic.go:642
        	            				testing.go:756
        	            				nipost_test.go:223
        	            				nipost_test.go:347
        	Error:      	Received unexpected error:
        	            	failed to kill process: os: process already finished
        	Test:       	TestValidator_Validate
--- FAIL: TestValidator_Validate (1.39s)
```

### PR DESCRIPTION
**Pull request by piersy**
## Motivation
CI was slow ~30 minutes

Closes #2925

## Changes
Removed the restriction in `make test` to run tests on a single core. This seems to equate to a roughly 30% reduction in CI runtime.

## Test Plan
I opened this PR and let CI run.

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by piersy** [comment]
bors try

**Comment by piersy** [comment]
bors try

**Comment by poszu** [comment]
@piersy I've wanted to do the same for a long time. It won't work without fixing the tests first. Unfortunately, some of them use the same system resources like a hardcoded network port...

**Comment by piersy** [comment]
Hey @poszu, it seems to just be one test now, just `Test_multipleCPs` is failing
* #4001

**Comment by countvonzero** [comment]
@piersy what's the reason closing this? seems a worthy endeavor...

**Comment by piersy** [comment]
@countvonzero, I just moved to a different branch and closed this to reduce clutter because I realised that I wouldn't be finishing this particularly soon.

**Pull request closed without merging**
