### PR TITLE
Remove m2-pro tag

### PR DESCRIPTION
**Pull request by andres-spacemesh**
## Motivation

Allow to run all CI jobs on M1 and M2 MacMini Runners

## Test Plan

Jobs are already running on m2 arm macs. Labels can be add anytime

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by poszu** [comment]
It became unclear that the job runs on a Mac. A "go-spacemesh" runner could be anything.

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
> It became unclear that the job runs on a Mac. A "go-spacemesh" runner could be anything.

good point - maybe the label could be something like `go-spacemesh-mac-arm`? (in case we want to add intel runners at a later point)

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by poszu** [comment]
bors cancel

**Comment by poszu** [comment]
bors merge

**Comment by fasmat** [comment]
bors cancel

**Comment by dsmello** [comment]
bors ping

**Comment by fasmat** [comment]
Closed because https://github.com/spacemeshos/go-spacemesh/pull/5836 has been merged 🎉

**Pull request closed without merging**
