### PR TITLE
[Merged by Bors] - Fix go version check script for MacOS.

### LINKED ISSUE #2097: Go version check script fails on MacOS X
## Description
The `./scripts/check-go-version.sh` which is run by Makefile, doesn't check Go version properly on MacOS X. In my case I have latest Go (1.14.6) installed, while script throws error saying Go 1.14+ is required.

## Steps To Reproduce
1. find Macbook
2. git clone go-spacemesh develop branch
3. run `make`
4. See error: `Go 1.14+ is required (vgo.version.go1.14.6 darwin/amd64 is installed at /usr/local/go/bin/go)`

## Expected Behavior
Go version is checked correctly, no error is shown, exit code 0.

## Environment
 - OS: MacOS X 10.15.5 Catalina 
 - Shell: GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

## Additional Resources 
This bug seems to be due to the differences between default MacOS X `sed` and GNU sed. One of the solutions would be to use different tool – `gsed` from the [`gnu-sed`](https://formulae.brew.sh/formula/gnu-sed) package and check for the correct platform in the script. Another one would be rewriting semver parsing code in a way that doesn't use `sed`.

### PR DESCRIPTION
**Pull request by divan**
## Motivation
This script offers a fix for https://github.com/spacemeshos/go-spacemesh/issues/2097.

MacOS's `sed` behaves differently from GNU `sed`, so the script fails to parse `go version` output on MacOS. This solution rewrites `go version` parsing part with bash-only features, so sed is not used anymore.

Closes #2097

## Changes
Script `./scripts/check-go-version.sh` is modified for not using `sed`.

## Test Plan
Tested on Linux and MacOS X by running script manually, and changing minimum minor version value.

### CODE REVIEW

**Review by y0sher — APPROVED** [review]
LGTM!

**Comment by y0sher** [comment]
though waiting to see what you and @lrettig conclude on in #2097 before merging.

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
I upgraded to go 1.15 and now I'm having the same problem ^_^

I simplified and cleaned this up a bit, @divan could you please check if it still works well for you? If so I think we're ready to merge

**Review by lrettig — APPROVED** [review]

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

>

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

>

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
