### PR TITLE
[Merged by Bors] - Fix swallowing ActiveSet creation errors during updates

### PR DESCRIPTION
**Pull request by ivan4th**
## Motivation

When processing an update and creating an ActiveSets, database related errors could be swallowed

## Description

Provide proper error handling for ActiveSet creation

## Test Plan

Tested on a mainnet node

### CODE REVIEW

**Review by poszu — APPROVED** [review]
It's a pity that `listenToUpdates` (and lots of other code in node.go) is not tested whatsoever.

**Comment by ivan4th** [comment]
@poszu agree, will try to improve that at some point

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
bors merge

**Comment by ivan4th** [comment]
bors merge

**Pull request closed without merging**
