### PR TITLE
[Merged by Bors] - Fix windows setup

### LINKED ISSUE #1954: protobuf/gcc errors on windows
## Description
Running into the below error when trying to run `make install` on Windows

## Steps To Reproduce
1. Install prereqs
1. Clone repository
1. Run `make install`

## Environment
 - OS: Windows 10
 - Node Version: building from head eaea050e3e3f4404481aa9b231f4e7e14af67cef

## Additional Resources 
```
PS > make install
process_begin: CreateProcess(NULL, bash -c "if [ \"$TRAVIS_PULL_REQUEST\" == \"false\" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi", ...) failed.
setup_env.bat
'protoc' is not recognized as an internal or external command,
operable program or batch file.
Fetching protoc...
Extracting protoc...

SUCCESS: Specified value was saved.
installing protoc-gen-go...
can't load package: package /protoc-gen-go is not in GOROOT (c:\go\src\protoc-gen-go)
installing protoc-gen-grpc-gateway...
can't load package: package /protoc-gen-grpc-gateway is not in GOROOT (c:\go\src\protoc-gen-grpc-gateway)
installing protoc-gen-swagger...
can't load package: package /protoc-gen-swagger is not in GOROOT (c:\go\src\protoc-gen-swagger)
make: *** [install] Error 1
```

### PR DESCRIPTION
**Pull request by lrettig**
Closes #1954
Requires #1955 

## Motivation
Fix some issues that are happening with building on windows

## Changes
Fix go and protobuf related issues in windows batch scripts

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]
(How) did this ever work before?

**Comment by noamnelke** [comment]
When you say "Requires #1955"... this actually **includes** those changes, meaning you'll have conflicts, but they should be trivial to fix.

**Comment by lrettig** [comment]
> When you say "Requires #1955"... this actually **includes** those changes, meaning you'll have conflicts, but they should be trivial to fix.

Yup. GitHub is not as expressive as I'd like :) Someday it may be possible to elegantly set up a waterfall of PRs...

**Comment by lrettig** [comment]
> (How) did this ever work before?

No clue. @moshababo wrote the previous code. My hypothesis is that it's a golang version issue.

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by lrettig** [comment]
@noamnelke: hero

**Pull request closed without merging**
