### PR TITLE
[Merged by Bors] - Update repo badges and go.mod version

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Some of this was missed in #2052 
The badges are a nice to have

## Changes
- Makes go version badge dynamic
- Replaces gitter badge with Discord
- Adds badges for help wanted issues, releases, and supported platforms

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]
👏🏻

**Comment by lrettig** [comment]
@avive take a look at the badges, feel free to merge if it looks good

**Review by avive — APPROVED** [review]
LGTM

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
