### PR TITLE
[Merged by Bors] - Fix GKE Auth Plugin

### PR DESCRIPTION
**Pull request by andres-spacemesh**
## Changes
Fix the CI Job when authenticating on GKE with the Auth Plugin

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)

### CODE REVIEW

**Comment by countvonzero** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by countvonzero** [comment]
bors try

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
