### PR TITLE
Enable scale codec for p2p server response

### PR DESCRIPTION
**Pull request by evt**
## Motivation

Part of #3271 

## Changes
enable scale codec for p2p server response

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by dshulyak** [comment]
@evt do you know what was the problem previously?

**Comment by dshulyak** [comment]
bors try

**Comment by evt** [comment]
> @evt do you know what was the problem previously?

there are tests that can randomly fail on github. I run them locally and if they work fine - re-run on github to see if it fails again. They then work.

**Comment by dshulyak** [comment]
> there are tests that can randomly fail on github. I run them locally and if they work fine - re-run on github to see if it fails again. 

previous failures weren't "random". maybe they didn't reproduce every single time, but basically something was failing to decode. it is easy to find such failures by searching for WARN or ERROR logs.

**Comment by evt** [comment]
> > there are tests that can randomly fail on github. I run them locally and if they work fine - re-run on github to see if it fails again.
> 
> previous failures weren't "random". maybe they didn't reproduce every single time, but basically something was failing to decode. it is easy to find such failures by searching for WARN or ERROR logs.

ah, I thought you meant today unit tests failures. Will check.

**Pull request closed without merging**
