### PR TITLE
[Merged by Bors] - Update API to newly generated files

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
Integrates https://github.com/spacemeshos/api/pull/274, merge after

## Changes
- update API dependency

## Test Plan
n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors cancel

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
Testrunner failed to assert condition in `TestNodesUsingDifferentPoets`

```
rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

test itself only shows some p2p warnings also network related:

```
"L":"WARN","T":"2023-09-29T13:47:07.699Z","N":"d98d6.p2p","M":"failed to connect","node_id":"d98d60e8320904c6b9bc89657d1756adad1eb4c1ba87dc62742a03cdb49981ee","module":"p2p","address":"{12D3KooWPMWxqM35M88xrNnr7vhZg7c5M1Ui5mVc1s6KZR8ZV6WE: [/ip4/10.20.4.237/tcp/7513]}","error":"failed to dial: context canceled"
```

bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
