### PR TITLE
[Merged by Bors] - Systests wait for pods to be ready

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
A Pod is truly ready to serve requests when its status is `READY`, not `RUNNING`. In systests Poets expect an operational gateway when they boot. Thus a test should wait until the boot nodes (which serve as poets gateways) are ready.

## Changes
Added waiting for `READY` in the `waitPod` function.

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Review by dshulyak — APPROVED** [review]
please check if it works with https://chaos-mesh.org/docs/simulate-pod-chaos-on-kubernetes/#some-notes-for-pod-failure-chaos-experiment

**Comment by poszu** [comment]
> please check if it works with https://chaos-mesh.org/docs/simulate-pod-chaos-on-kubernetes/#some-notes-for-pod-failure-chaos-experiment

It should work fine as we don't use liveness or readiness probes.

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
