### PR TITLE
[Merged by Bors] - Bump poet to v0.5.0

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Bump poet to the latest v0.5.0 that includes the latest performance optimizations
Closes #3972

## Changes
- bump poet to v0.5.0
- bump merkle-tree to v0.2.0

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by pigmej** [comment]
Bors merge

**Comment by pigmej** [comment]
Bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by pigmej** [comment]
Bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
Bors cancel

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
