### PR TITLE
[Merged by Bors] - Update post to v0.3.0 and api to v1.5.5

### LINKED ISSUE #3529: Change PoST impl to support max file size
## Description
Current PoST setup implementation enables the splitting of the data into multiple files via the [`NumFiles`](https://github.com/spacemeshos/go-spacemesh/blob/develop/activation/post.go#L37) param. 
A different approach is to define `MaxFileSize`, and split the files accordingly. It is more desirable from the user's perspective which is more likely to be worried about the max size rather than about the number of files, and so whenever the total size changes, it won't require an extra step to secure that. 
In addition, it will relax some implementation complexity needed in order to support the increase/decrease of the total size.

## Affected code
* gRPC API (SmesherService)
* Node config
* `PostSetupManager`
* The underlying PoST implementation

### PR DESCRIPTION
**Pull request by moshababo**
## Motivation

Closes https://github.com/spacemeshos/go-spacemesh/issues/3529.

## Changes

* Updates [post](https://github.com/spacemeshos/post/) dep to [post/releases/tag/v0.3.0](https://github.com/spacemeshos/post/releases/tag/v0.3.0).
* Updates [api](https://github.com/spacemeshos/api/) dep to [api/releases/tag/v1.5.5](https://github.com/spacemeshos/api/releases/tag/v1.5.5).

## Notes 
@maparr @brusherru @andres-spacemesh
* This PR affects the node's RPC API (smesher service). 
* This PR affects the node's config.

### CODE REVIEW

**Comment by moshababo** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by moshababo** [comment]
bors merge

**Comment by moshababo** [comment]
bors merge

**Comment by moshababo** [comment]
bors merge

**Comment by moshababo** [comment]
bors merge

**Comment by moshababo** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by moshababo** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
