### PR TITLE
[Merged by Bors] - Increase def accounts balance to 10^5 smh so we can test w large amounts

### PR DESCRIPTION
**Pull request by avive**
Minor change - amount change for testing tap w large amounts.

## Motivation

Closes #

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

### CODE REVIEW

**Review by antonlerner — APPROVED** [review]

**Comment by avive** [comment]
bors try

**Comment by avive** [comment]
bors try

**Comment by avive** [comment]
This seems to break tests that assume that the genesis tap accounts config balance must be 1000. @AmitShaul

**Comment by avive** [comment]
bors try

**Comment by avive** [comment]
bors try

**Comment by avive** [comment]
@AmitShaul  - I can't merge this to develop until you merge fixes to tests that assumed a hard-coded amount in tap accounts on genesis.

**Comment by avive** [comment]
bors try

**Comment by AmitShaul** [comment]
bors merge

**Comment by avive** [comment]
borse merge

**Comment by avive** [comment]
bors merge

**Pull request closed without merging**
