### PR TITLE
[Merged by Bors] - Bump post to v0.8.0

### LINKED ISSUE #4574: Remove support for verifying the old scrypt-based K2 POW
## Description
We already moved to RandomX based on the POST proving path. Support for verifying was left for compatibility in Testnet-05. It can be removed after we do a checkpoint.

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Removes support for verifying the old scrypt-based K2 Pow in POST.

Closes #4574 

## Changes
- bump post
- bump post-rs
- remove scrypt-based k2-pow configuration

## Test Plan
  - unit tests
  - system tests

## DevOps Notes

- [ ] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
  :point_right: `post-k2pow-difficulty` can be removed from config
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Review by dshulyak — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
