### PR TITLE
[Merged by Bors] - Fix voting pattern duplication

### PR DESCRIPTION
**Pull request by almogdepaz**
## Motivation
pattern is saved per block even if it is already known, this pr will save us memory in the naive case.

### CODE REVIEW

**Review by barakshani — APPROVED** [review]

**Comment by almogdepaz** [comment]
bors merge

**Comment by y0sher** [comment]
this is weird, travis says everything is green but bors says failed ? rerun ?

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Pull request closed without merging**
