### PR TITLE
[Merged by Bors] - Cache deps in systest Dockerfile

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
It should speed up docker image rebuilds when dependencies are the same as before.

## DevOps Notes
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
That seems a bit redundant to me, since the two lines below the lines you added already mount the build cache of the host overwriting the files created by `go mod download`.

**Review by fasmat — CHANGES_REQUESTED** [review]
See comment

**Comment by poszu** [comment]
> That seems a bit redundant to me, since the two lines below the lines you added already mount the build cache of the host overwriting the files created by `go mod download`.

They don't (`build` directory is .dockerignore-d) and they shouldn't. Docker can efficiently cache layers and knows when it can reuse a layer (when go.mod/sum has not changed).

**Comment by fasmat** [comment]
> They don't (build directory is .dockerignore-d) and they shouldn't. Docker can efficiently cache layers and knows when it can reuse a layer (when go.mod/sum has not changed).

The following two lines already cache the go build: even if the `build` directory is ignored.

```Dockerfile
RUN --mount=type=cache,target=/go/pkg/mod go mod download
RUN --mount=type=cache,target=/root/.cache/go-build go test -v -c -o /build/tests.test ./systest/tests/
```

I am not opposed to your change, but then you should also update the two lines to be just:

```Dockerfile
RUN go mod download
RUN go test -v -c -o /build/tests.test ./systest/tests/
```

**Comment by poszu** [comment]
@fasmat Fixed.

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
