### PR TITLE
make wait dynamic for waiting for sending poet challenge

### LINKED ISSUE #4643: activation: don't loop with retries when node needs to wait for next poet window
if node missed poet window in the current epoch it will loop with retries and fail the same way.
instead it should understand that it needs to wait for next epoch and extend wait period. 

relevant code https://github.com/spacemeshos/go-spacemesh/blob/develop/activation/activation.go#L365-L384

maybe it is enough to increment `current`, if `until` is negative

### PR DESCRIPTION
**Pull request by kdonthi**
## Motivation

Fix the wait for next poet window.

## Description

Closes #4643 

I decided to update the current until we know that the time to the next epoch is positive.
 
## TODO

- [x] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
Hi @kdonthi,

thank you for your contribution. I am not sure the problem in issue #4643 is still happening. If you take a look at the code `current` is the current epoch (epoch 17 as of today):

https://github.com/spacemeshos/go-spacemesh/blob/e4df06834517a927817dcd8c122ea1d356b14dd8/activation/activation.go#L426

It then might be increased if your node has already published an ATX in the current epoch here:

https://github.com/spacemeshos/go-spacemesh/blob/e4df06834517a927817dcd8c122ea1d356b14dd8/activation/activation.go#L455-L463

Then it checks if the `poetRoundStart` is in the future (i.e. if `2024-03-18 08:00 UTC` is before today for the current epoch and the default poet phase):

https://github.com/spacemeshos/go-spacemesh/blob/e4df06834517a927817dcd8c122ea1d356b14dd8/activation/activation.go#L465-L470

There are only 2 options here: we are before the poet round start in the current epoch - or we are after it. In either case increasing `current` by one will always result in a positive `until` value.

If it doesn't the poet configuration of your node might be incorrect and increasing it multiple times will cause problems, i.e. your node might never publish an ATX because `current` (which determines the `PublishEpoch` of the ATX) is multiple epochs in the future instead of either this or next epoch (depending on if you are before or after the CG when this code executes).

**Comment by fasmat** [comment]
Actually #5207 already should fix the issue by incrementing `current` if `until` is negative. This should always result in a positive `until` value - if it doesn't the node configuration is invalid (poet round start is more than 1 epoch into the past) and the node should probably `log.Fatal` instead of further increasing `current`.

**Comment by kdonthi** [comment]
It makes sense haha - I was reading the code logic and it was feeling like the problem had already been solved because the `current` was incremented and the `until` was set to something new :)

I messaged you on Discord (lmk if there is a better way to message you?); let me know if there is something I could help contribute on!

**Comment by fasmat** [comment]
No problem. Contributions are always welcome! 🙂

You can take a look at our issues here or in one of the other repositories of `github.com/spacemeshos`. Generally we would appreciate if you announce that you want to start working on a task to give you feedback on your proposed solution, if the issue is still relevant and to avoid having your work collide with what the maintainers are currently working on.

If you want to have this contribution merged I suggest you change the code to just check that `until` is positive after incrementing `current` and if it's not call `logger.Fatal()` with a message like:

```go
logger.Fatal(
	"Invalid configuration detected. `phase-shift` must be > 0 and less than the duration of an epoch",
	zap.Duration("phase-shift", b.poetCfg.PhaseShift),
)
```

**Comment by fasmat** [comment]
bors merge

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
LGTM

bors merge

**Comment by kdonthi** [comment]
Could you please explain to me how the phase shift duration is set 😄

**Comment by fasmat** [comment]
> Could you please explain to me what the phase shift is doing 😄

It defines when a PoET round starts relative to the start of the Epoch. The default phase is 864000 seconds (or 10 days), the next epoch starts 2024-03-22 08:00 UTC which means that the PoET round for that Epoch starts 2024-04-01 08:00 UTC.

The start of the PoET round is also the end of the cyclegap where every node does their PoSTs.

**Comment by fasmat** [comment]
bors cancel

there are a few tests that need to be updated because they have invalid setups that are now detected with this change.

**Comment by kdonthi** [comment]
Is it something I can help to fix?

**Comment by fasmat** [comment]
You can try to fix the tests 🙂. To execute all tests locally run `make test` after `make install`.

If you only want to run a single test make sure to run `make go-env-test` before using `go test`.

**Comment by fasmat** [comment]
Closed as the issue the PR addresses has already been fixed.

**Pull request closed without merging**
