### PR TITLE
[Merged by Bors] - Fix panic in multi_node_sim

### LINKED ISSUE #2257: Panic in multi_node_sim
## Description

Running `ulimit -n 10000; ./multi_node_sim -n 10 -l 100 -b 10` often throws `panic: too many errors and retries`.

## Steps To Reproduce
1. Go to `./cmd/multi_node_sim`
2. Run `go build`
3. Run `ulimit -n 10000; ./multi_node_sim -n 10 -l 100 -b 10 2>&1 | tee multi_node_sim.log`
4. Panic will likely appear

## Expected Behavior

No panic

## Environment
Please complete the following information:
 - OS: 
 
 MacOS
 - Node Version: 
 
  Not applicable
 - App Version (if applicable): 
 
 Not applicable

## Additional Resources 

```
panic: too many errors and retries

goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc033e1e2c0, 0x0, 0x0, 0x0)
	/Users/nkryuchkov/go/pkg/mod/go.uber.org/zap@v1.15.0/zapcore/entry.go:230 +0x55f
go.uber.org/zap.(*SugaredLogger).log(0xc00e3ece68, 0x504, 0x1d24d6b, 0x1b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/nkryuchkov/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:234 +0xf6
go.uber.org/zap.(*SugaredLogger).Panicf(...)
	/Users/nkryuchkov/go/pkg/mod/go.uber.org/zap@v1.15.0/sugar.go:159
github.com/spacemeshos/go-spacemesh/log.Log.Panic(0xc000092420, 0x1d24d6b, 0x1b, 0x0, 0x0, 0x0)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/log/zap.go:43 +0x277
github.com/spacemeshos/go-spacemesh/log.Panic(...)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/log/log.go:138
github.com/spacemeshos/go-spacemesh/cmd/node.StartMultiNode(0xa, 0xa, 0xc000000064, 0x1d0fe7a, 0x8)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/cmd/node/multi_node.go:313 +0x1a89
main.glob..func1(0x25bb060, 0xc000300240, 0x0, 0x6)
	/Users/nkryuchkov/GolandProjects/go-spacemesh/cmd/multi_node_sim/multi_node_sim.go:41 +0x5b
github.com/spf13/cobra.(*Command).execute(0x25bb060, 0xc00003c080, 0x6, 0x6, 0x25bb060, 0xc00003c080)
	/Users/nkryuchkov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x25bb060, 0x1008345, 0xc00004c0b8, 0x0)
	/Users/nkryuchkov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/nkryuchkov/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/nkryuchkov/GolandProjects/go-spacemesh/cmd/multi_node_sim/multi_node_sim.go:50 +0x31
```

### PR DESCRIPTION
**Pull request by nkryuchkov**
## Motivation

Closes #2257 

## Changes

When the stdout of the `PoET` server is not read, the server hangs after some time, which causes a panic in `multi_node_sim`. The PR fixes this issue and supersedes https://github.com/spacemeshos/poet/pull/107.

## Test Plan

- [X] Ensure that steps described in #2257 do not lead to panic

## DevOps Notes

- [ ] Does this code require configuration changes?
- [ ] Does this code affect public APIs?
- [ ] Does this code assume a new version of external services (PoET, elasticsearch, etc.)
- [ ] Does this code make changes to log messages that our monitoring infrastructure may rely on?

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]
Instead of `ReadAll` we could do a loop over `Read` and log the output. This is not critical, but would surely help understand future issues if they're related to PoET behaviour.

Up to you if you want to change this or leave as-is.

**Review by noamnelke — APPROVED** [review]
👏🏻

**Comment by nkryuchkov** [comment]
bors try

**Comment by nkryuchkov** [comment]
bors merge

**Comment by nkryuchkov** [comment]
bors merge

**Pull request closed without merging**
