### PR TITLE
Add a way to customize logging capabilities to remaining services (Take two)

### LINKED ISSUE #2086: Add custom logger for GRPC API
## Description
Right now, all of the new API code is using the default logger. We should either have a single logger shared by all the GRPC services, or else one instance per service.

A related change we may want to make here is reducing the default log level for many of the log statements, especially the ones in the reporter, from INFO to DEBUG (especially the "not reporting... since no one is listening" messages).

## Affected code
api/grpcserver/*

This issue appears in commit hash: latest in api-phase9 branch

### PR DESCRIPTION
**Pull request by hoenirvili**
(This is a the first part of #2100 because as I discussed with @lrettig )

## Motivation
All the **grpc** common functionality is placed in a single package and their all using the global logger. This is not good because what if the client want's to use a custom logger or other miscellaneous options?
 
## Changes
I've changed all files under api/grpcserver/* to make all the concrete implementation be flexible. By flexible I mean, using the option pattern and make all implementations support adding required miscellaneous things like support custom loggin, support grpc protocol options etc.

## Test Plan

I've just re-run the unit tests and made sure that everything passes alongside with whole compilation of the main binary (on linux 64bit)

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

### CODE REVIEW

**Comment by hoenirvili** [comment]
@lrettig Hi, could you please review this pr?

**Comment by y0sher** [comment]
@hoenirvili : thanks for this contribution, apart from @lrettig's pending review we had some CI issues lately and we weren't merging any prs, this is basically solved now and we're slowly integrating the pull request queue into develop. @lrettig is there more review needed?

**Comment by lrettig** [comment]
> @hoenirvili : thanks for this contribution, apart from @lrettig's pending review we had some CI issues lately and we weren't merging any prs, this is basically solved now and we're slowly integrating the pull request queue into develop. @lrettig is there more review needed?

Thanks for the reminder @y0sher, will review this ASAP!

**Comment by antonlerner** [comment]
closed due to inactivity (and a lot has changed since)

**Pull request closed without merging**
