### PR TITLE
[Merged by Bors] - p2p remove time.Sleep from tests

### PR DESCRIPTION
**Pull request by abergasov**
## Motivation
fix flacky tests in p2p addrBook

## Changes
remove time.Sleep from test

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by abergasov** [comment]
bors try

**Comment by dshulyak** [comment]
there are also a lot of them in bookcheck_test.go

**Review by dshulyak — APPROVED** [review]

**Comment by abergasov** [comment]
bors try

**Comment by abergasov** [comment]
bors try

**Comment by abergasov** [comment]
bors merge

**Comment by abergasov** [comment]
bors merge

**Pull request closed without merging**
