### PR TITLE
[Merged by Bors] - use zap in syncer package

### PR DESCRIPTION
**Pull request by poszu**
## Motivation

Part of the effort to switch from log to zap.

## Test Plan

existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
flaky test: https://github.com/spacemeshos/go-spacemesh/issues/6119

**Pull request closed without merging**
