### PR TITLE
[Merged by Bors] - Release v1.4.1

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

Prepare release v1.4.1.

## Description

This updates the CHANGELOG, after merge the new version will be tagged for release.

## Test Plan

n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by xearl4** [comment]
The 1.4.0 changelog is missing a critical step in the notes about migration to manage multiple identities, namely the need to merge the existing `local.sql`s. Can we add a fix for this to 1.4.1?

**Comment by pigmej** [comment]
> The 1.4.0 changelog is missing a critical step in the notes about migration to manage multiple identities, namely the need to merge the existing `local.sql`s. Can we add a fix for this to 1.4.1?

Can you elaborate more? Where is it missing t? The changelog assumes NEW identities as this is new functionality. With bigger guide being: https://docs.spacemesh.io/docs/start/smesher/post_1n

**Comment by xearl4** [comment]
@pigmej The changelog has a section "Migrating existing identities/PoST services to a node" (https://github.com/spacemeshos/go-spacemesh/blob/v1.4.0/CHANGELOG.md#migrating-existing-identitiespost-services-to-a-node):

> If you have multiple nodes running and want to migrate to use only one node for all identities:
> 
> 1. Stop all nodes.
> 2. Copy the identity.key files from the PoST data directories of all nodes to the data/identities directory of the node you want to use for those identities. The choose names for the key files that makes it easy to distinguish which key belongs to which identity.
> 3. Start the node managing the identities.
> 4. For every identity setup a post service to use the existing PoST data for that identity and connect to the node. For details refer to the [post-service README](https://github.com/spacemeshos/post-rs/blob/main/service/README.md).

I think the necessity to merge `local.sql`s should either be mentioned in step 2 or added as a separate step.

**Comment by pigmej** [comment]
@fasmat let's mention here the merge-nodes command :)

**Comment by fasmat** [comment]
The idea was to have the guide mention the process of how to merge existing nodes into one. I updated both the `CHANGELOG` and `README` with information about the `merge-nodes` tool and a basic guide on how to merge existing nodes.

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
