### PR TITLE
handle state on late block

### LINKED ISSUE #1727: late blocks and different state
Miners who get late blocks seem not to classify them as contextually invalid (this is a known issue: https://github.com/spacemeshos/go-spacemesh/issues/1545). This somehow affects the global state, as there is a difference in the state with miners that classified the block as invalid.

In the screenshot, the first miner is the miner who created the block, but it never got to the network. Then some miners joined the network and got synced through this miner, so they get the block, but they don't know it is late. Since no one votes for it, it is contextually invalid. One of them creates a block and points to it as orphan, and this is how all the network gets it. Not it is a late block. The tortoise does process it, but does not declare it as invalid (see issue above).

q

We can see that the original miners, and all the rest have different state (for the same layer). It is not clear what causes that, as this block had no transactions in it, and also in both cases it should not get any reward.

w

Should be part of https://github.com/spacemeshos/go-spacemesh/issues/1549

### PR DESCRIPTION
**Pull request by almogdepaz**
## Motivation
closes #1727 
currently when a late block changes pbase we do not handle the state change

## Changes
added stateTransition after late block handling 

## Test Plan
will add automation tests

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Pull request merged**
