### PR TITLE
[Merged by Bors] - log beacon short string instead of binary data

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation
improve log readability

## Changes
log beacon short string instead of the binary data

## Test Plan
n/a

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by nkryuchkov — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by nkryuchkov** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
