### PR TITLE
[Merged by Bors] - Update mockgen to the same version as go-mock dependency

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

`go-mock` has been updated a while ago. When the dependency was updated we forgot to also update `mockgen`

## Description

Update of `mockgen` and one run of `make generate`

## Test Plan

n/a

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
random flake.

bors merge

**Comment by fasmat** [comment]
flaky tests

bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
