### PR TITLE
[Merged by Bors] - Use same golangci-lint locally as in GH

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation
I noticed that not the same version of golangci-lint is used locally as in GH which lead to some issues for me - GH reported errors that my local golangci-lint didn't find.

## Changes
Ensure same version of glangci-lint is used locally as in GH.

## Test Plan
All existing tests pass.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by countvonzero — APPROVED** [review]
sigh... i'd much rather this PR be split into 2 separate PRs. 
they are logically irrelevant....

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
