### PR TITLE
[Merged by Bors] - Use latest received layer in NodeService.Status response during genesis

### LINKED ISSUE #2333: Return true current sync layer in API
In #2299 we patched the API to return the current (tip) layer rather than statically returning the first layer of the third epoch as the current layer. But this still isn't really accurate. What we really want is for the API to instead return the latest _synced_ layer. This information is currently not exposed to the API, but it could be, and it definitely lives in the sync code somewhere, since sync prints log lines like these:

```
2021-03-14T22:04:13.399+0300    INFO    bfda3.sync              syncing layer   {"node_id": "...", "current_sync_layer": 67, "last_ticked_layer": 3375}
```

The `NodeService.Status` should return the latest _synced_ layer (not latest layer in state) during genesis (and maybe always.)

### PR DESCRIPTION
**Pull request by dshulyak**
## Motivation
Closes https://github.com/spacemeshos/go-spacemesh/issues/2333

## Changes
During genesis, NodeService Status will return the latest received layer as the Synced and Verified layer.

## Test Plan
Existing tests

## TODO
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps 
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Review by lrettig — CHANGES_REQUESTED** [review]
Please see my comment here: https://github.com/spacemeshos/go-spacemesh/issues/2333#issuecomment-869013979

This change only needs to happen when `curLayerObj.GetEpoch().IsGenesis()` is true, i.e., the first part of this conditional, not the second. It needs to update both `latestLayer` and `verifiedLayer`. And the value should not be read from `s.Mesh`. It needs to come from the state of the syncer, which is not currently injected into the API.

Let me know if anything is unclear. Thanks!

**Comment by dshulyak** [comment]
@lrettig syncer updates the state on the mesh ([ref](https://github.com/spacemeshos/go-spacemesh/blob/develop/sync/syncer.go#L492-L524)). if you are worried that in the future syncer may start to store this value in its own state i can surely extend syncer

**Comment by lrettig** [comment]
> @lrettig syncer updates the state on the mesh ([ref](https://github.com/spacemeshos/go-spacemesh/blob/develop/sync/syncer.go#L492-L524)). if you are worried that in the future syncer may start to store this value in its own state i can surely extend syncer

During genesis, when syncer receives a zero-block layer, it does not even call `ValidateLayer` since there's nothing to validate. It just calls `SetZeroBlockLayer` in the mesh:

https://github.com/spacemeshos/go-spacemesh/blob/9116d1fd4f6f4fadef986d12212a938a62f87e97/sync/syncer.go#L512-L517

This calls `SetLatestLayer` but not `SetProcessedLayer`.

All we need to do here is ensure that the API code can fetch the latest synced layer and report that during genesis.

The title of this PR should probably be changed to something like, "Use latest synced layer in NodeService response during genesis"

**Comment by dshulyak** [comment]
@lrettig as i can see ValidateLayer is called in any case. this condition https://github.com/spacemeshos/go-spacemesh/blob/9116d1fd4f6f4fadef986d12212a938a62f87e97/sync/syncer.go#L512-L517 doesn't interrupt the loop

**Comment by lrettig** [comment]
If the syncer is always setting the latest received layer in the mesh, then it might be enough to return this from the API!

**Comment by dshulyak** [comment]
as i mentioned, syncer **sometimes** updates Latest (when no blocks), and **always** updates Processed (but not always persists it on disk, which seems to be a bug from my perspective). i will try to clarify if this is the intented behavior. to me it seems that it doesn't matter if we return Latest or Processed as they are always updated synchronously one after the other when a layer without blocks is received

**Review by lrettig — APPROVED** [review]
lgtm

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
