### PR TITLE
issue #207 v2

### PR DESCRIPTION
**Pull request by salvatore63**

### CODE REVIEW

**Comment by y0sher** [comment]
tests are not passing please use `make test` to see whats not working.

**Comment by y0sher** [comment]
Good job on this one! please just fix tests and I'll approve. @salvatore63

**Comment by salvatore63** [comment]
> Good job on this one! please just fix tests and I'll approve. @salvatore63

sorry y0sher, what means "fix tests", now when I run "make test" no gets any error ..

**Comment by y0sher** [comment]
you are right tests will pass after you fix the conflicts and update to latest `develop`.

**Comment by antonlerner** [comment]
This issue has failing UT and conflicts, closed due to inactivity

**Pull request closed without merging**
