### PR TITLE
Use different settings for windows checkout

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

This hopefully makes the windows checkout more stable.

## Description

I increased the `http.postBuffer` size, `core.compression` and `pack.window` with default values take much longer to checkout so I kept these values.

## Test Plan

Checkout on windows works

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Review by andres-spacemesh — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
PR seems to be stuck and not being picked up by bors, superceeded by https://github.com/spacemeshos/go-spacemesh/pull/6302

**Pull request closed without merging**
