### PR TITLE
[Merged by Bors] - Reduce grace period in systests

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
Currently, in system tests, the _cycle gap_ parameter is set to 2x _grace period_. It leaves zero space for setting a deadline to wait for poet proofs.

## Changes
Changed grace period to 3s. That should give a 4s window for setting up the poet proof deadline (the cycle gap is 10s).

## DevOps Notes
- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by countvonzero** [comment]
bors try

**Comment by countvonzero** [comment]
bors try

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
