### PR TITLE
[Merged by Bors] - Bump poet to v0.9.5

### PR DESCRIPTION
**Pull request by poszu**
## Changes
Bumped poet to the latest available version

## Test Plan
Existing tests should pass

### CODE REVIEW

**Comment by poszu** [comment]
bors try

**Comment by poszu** [comment]
bors try

**Review by fasmat — APPROVED** [review]
The PR is kinda large because it also updates `go.uber.org/mock`. I hope dependabot soon creates new PRs for those after we hopefully fixed it to avoid having to mix in these updates with other changes 😕

**Comment by poszu** [comment]
Bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
