### PR TITLE
[Merged by Bors] - Update readme

### PR DESCRIPTION
**Pull request by avive**
## Motivation
- Provide clear instructions on how to join Spacemesh 0.1 Testnet in the repo's README.

## Changes
- Added links to v0.1.3 release and Testnet 0.1 toml config file.

## Test Plan
- Try to join 0.1 Testnet by following the insturctoins.

## TODO
- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed

### CODE REVIEW

**Review by y0sher — APPROVED** [review]

**Review by lrettig — APPROVED** [review]

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
@noamnelke - tests are failing on develop - is this a known issue?

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Pull request closed without merging**
