### PR TITLE
[Merged by Bors] - update changelog for #4879

### PR DESCRIPTION
**Pull request by countvonzero**
## Motivation
follow up on #4879 update changelog for release

also rename migration file to reflect its released state

### CODE REVIEW

**Review by dshulyak — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
i think renaming migration will break node

**Comment by dshulyak** [comment]
sorry, looks like only version matters, name is only for description

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
but honestly i don't understand why to include such changes with changelog update

**Comment by countvonzero** [comment]
> but honestly i don't understand why to include such changes with changelog update

yes. sorry. will separate such change in the future.

**Pull request closed without merging**
