### PR TITLE
[Merged by Bors] - Revert "Lower p2p test params"

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Revert test params changes made in #2427 due to flaky test

Like #2395, see also #2396

## Changes
Resets test params to where they were before this PR

## Test Plan
N/A

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed

## DevOps Notes

- [x] This PR does not require configuration changes (e.g., environment variables, GitHub secrets, VM resources)
- [x] This PR does not affect public APIs
- [x] This PR does not rely on a new version of external services (PoET, elasticsearch, etc.)
- [x] This PR does not make changes to log messages (which monitoring infrastructure may rely on)

### CODE REVIEW

**Comment by lrettig** [comment]
bors try

**Comment by lrettig** [comment]
bors try

**Review by noamnelke — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
@antonlerner would you mind taking a look at this as part of your work on flaky systests? Feel free to reassign

**Comment by lrettig** [comment]
bors merge

>

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
