### PR TITLE
[Merged by Bors] - stop Fetcher in testFetch_getHashes

### LINKED ISSUE #6120: Flaky TestFetch_getHashes
## Description
Test failed in a PR with unrelated changes

## Affected code
`TestFetch_getHashes` seems to be unstable a least on slower runners. Example CI run: https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27270910147 from PR https://github.com/spacemeshos/go-spacemesh/pull/6115

```
=== Failed
=== FAIL: fetch TestFetch_getHashes/streaming/all_hashes_fetched (0.06s)
    logger.go:146: 2024-07-10T13:10:47.939Z	INFO	initialized datastore	{"config": {"ATXSize":1000,"MalfeasanceSize":1000}}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "queued": 1}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "queued": 2}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "queued": 3}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	processing hash request	{"hash": "[199](https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27269390910#step:14:200)00b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	processing hash request	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	processing hash request	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "abe2516c3c99f0d408318c1b67decbac1cf80918608299d02a1aa0a5cffd64a0", "num_requests": 2, "peer": "4jQYrH8oyH", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "6080f6da5a01936051dbf4fb06f96e9128bb529579a22207dbbb3a6622878f40", "num_requests": 1, "peer": "4jQYrH8oyJ", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	hash request done	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "19900b32aadc9985996429f9aade50d98892dc8[200](https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27269390910#step:14:201)0000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	hash request done	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
    logger.go:146: [202](https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27269390910#step:14:203)4-07-10T13:10:47.945Z	DEBUG	hash request done	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000"}
    testing.go:1398: race detected during execution of test

=== FAIL: fetch TestFetch_getHashes/streaming/handler_failed (0.06s)
    logger.go:146: 2024-07-10T13:10:47.939Z	INFO	initialized datastore	{"config": {"ATXSize":1000,"MalfeasanceSize":1000}}
    logger.go:146: 2024-07-10T13:10:47.939Z	DEBUG	hash request added to queue	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "queued": 1}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "queued": 2}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "queued": 3}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	processing hash request	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	processing hash request	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	processing hash request	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "6080f6da5a01936051dbf4fb06f96e9128bb529579a22[207](https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27269390910#step:14:208)dbbb3a6622878f40", "num_requests": 1, "peer": "4jQYrH8oyJ", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "abe2516c3c99f0d408318c1b67decbac1cf80918608299d02a1aa0a5cffd64a0", "num_requests": 2, "peer": "4jQYrH8oyH", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	failed to get hash	{"hint": "blocksDB", "hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "error": "unknown"}
    logger.go:146: 2024-07-10T13:10:47.945Z	DEBUG	failed to get hash	{"hint": "blocksDB", "hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "error": "unknown"}
    logger.go:146: 2024-07-10T13:10:47.945Z	DEBUG	failed to get hash	{"hint": "blocksDB", "hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "error": "unknown"}
    testing.go:1398: race detected during execution of test

=== FAIL: fetch TestFetch_getHashes/streaming/some_hashes_failed (0.07s)
    logger.go:146: 2024-07-10T13:10:47.939Z	INFO	initialized datastore	{"config": {"ATXSize":1000,"MalfeasanceSize":1000}}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "queued": 1}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "queued": 2}
    logger.go:146: 2024-07-10T13:10:47.940Z	DEBUG	hash request added to queue	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "queued": 3}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	processing hash request	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	processing hash request	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	processing hash request	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "abe2516c3c99f0d408318c1b67decbac1cf80918608299d02a1aa0a5cffd64a0", "num_requests": 2, "peer": "4jQYrH8oyH", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.941Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "6080f6da5a01936051dbf4fb06f96e9128bb529579a2[220](https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27269390910#step:14:221)7dbbb3a6622878f40", "num_requests": 1, "peer": "4jQYrH8oyJ", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	hash not found in response from peer	{"hint": "blocksDB", "hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "peer": "4jQYrH8oyH"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	gave up on hash after max retries	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "retries": 1}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	received response for hash	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	failed to get hash	{"hint": "blocksDB", "hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "error": "fetch failed after max retries for request"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	hash request done	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	hash request done	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
==================
WARNING: DATA RACE
Read at 0x00c0017ca523 by goroutine 1766:
==================
    testing.go:1398: race detected during execution of test

=== FAIL: fetch TestFetch_getHashes/streaming/all_hashes_failed (0.03s)
    logger.go:146: 2024-07-10T13:10:47.969Z	INFO	initialized datastore	{"config": {"ATXSize":1000,"MalfeasanceSize":1000}}
    logger.go:146: 2024-07-10T13:10:47.971Z	DEBUG	hash request added to queue	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "queued": 1}
    logger.go:146: 2024-07-10T13:10:47.971Z	DEBUG	hash request added to queue	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "queued": 2}
    logger.go:146: 2024-07-10T13:10:47.971Z	DEBUG	hash request added to queue	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "queued": 3}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	processing hash request	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	processing hash request	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	processing hash request	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000"}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "1f9a63b8e8a4ef8f70dec337777650988bd94d2798287abe01253f77c92cc31f", "num_requests": 2, "peer": "4jQYrH8oyH", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	sending streamed batched request to peer	{"batch_hash": "6080f6da5a01936051dbf4fb06f96e9128bb529579a[222](https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27269390910#step:14:223)07dbbb3a6622878f40", "num_requests": 1, "peer": "4jQYrH8oyJ", "extraProtocols": []}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	hash not found in response from peer	{"hint": "blocksDB", "hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "peer": "4jQYrH8oyJ"}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	hash not found in response from peer	{"hint": "blocksDB", "hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "peer": "4jQYrH8oyH"}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	gave up on hash after max retries	{"hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "retries": 1}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	failed to get hash	{"hint": "blocksDB", "hash": "a08e330ac36780857cdeb2ffcedcc4a6cca7a4d5000000000000000000000000", "error": "fetch failed after max retries for request"}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	gave up on hash after max retries	{"hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "retries": 1}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	hash not found in response from peer	{"hint": "blocksDB", "hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "peer": "4jQYrH8oyH"}
    logger.go:146: 2024-07-10T13:10:47.972Z	DEBUG	failed to get hash	{"hint": "blocksDB", "hash": "52e80a368e5a9c6677e7488da21accda24161cc1000000000000000000000000", "error": "fetch failed after max retries for request"}
    logger.go:146: 2024-07-10T13:10:47.973Z	DEBUG	gave up on hash after max retries	{"hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "retries": 1}
    logger.go:146: 2024-07-10T13:10:47.973Z	DEBUG	failed to get hash	{"hint": "blocksDB", "hash": "19900b32aadc9985996429f9aade50d98892dc82000000000000000000000000", "error": "fetch failed after max retries for request"}
    testing.go:1398: race detected during execution of test

=== FAIL: fetch TestFetch_getHashes/streaming (0.00s)
    logger.go:146: 2024-07-10T13:10:47.942Z	DEBUG	failed to process batch request	{"batch": "6080f6da5a01936051dbf4fb06f96e9128bb529579a22207dbbb3a66[228](https://github.com/spacemeshos/go-spacemesh/actions/runs/9874607665/job/27269390910#step:14:229)78f40", "peer": "4jQYrH8oyJ", "error": "request failed"}

=== FAIL: fetch TestFetch_getHashes (0.19s)
```

### PR DESCRIPTION
**Pull request by poszu**
## Motivation

Closes #6120 

## Description

The `Fetcher::getHashes` spawns a goroutine. The test didn't wait for it to finish and was logging after the test finished.

## Test Plan

Ran the test 500x, can't reproduce locally anymore (it used to fail ~ 1/100 times on my PC)

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
I don't think this is needed... The started go routine(s) should have completed when `getHashes` returns 🤔. Even without the change I just don't hit that data race:

```go
$ go test -timeout 5m -race -run '^TestFetch_getHashes$/^streaming$' github.com/spacemeshos/go-spacemesh/fetch -count 2000
ok      github.com/spacemeshos/go-spacemesh/fetch       174.224s
```

**Comment by poszu** [comment]
> I don't think this is needed... The started go routine(s) should have completed when `getHashes` returns 🤔. Even without the change I just don't hit that data race:
> 
> ```go
> $ go test -timeout 5m -race -run '^TestFetch_getHashes$/^streaming$' github.com/spacemeshos/go-spacemesh/fetch -count 2000
> ok      github.com/spacemeshos/go-spacemesh/fetch       174.224s
> ```

This goroutine is not guaranteed to have stopped by the time `getHashes()` returns in case of failure in my opinion: https://github.com/spacemeshos/go-spacemesh/blob/80f3ee5cbd031c79abd54ea2edabdaaab58f6c91/fetch/fetch.go#L973-L976

The failing test is `TestFetch_getHashes/streaming/hash_request_failed`, which tests the unhappy scenario.

More info:
```
❯ go test -timeout 3m -race -run '^TestFetch_getHashes$/^streaming$/^hash_request_failed$' github.com/spacemeshos/go-spacemesh/fetch -count 1000
==================
WARNING: DATA RACE
Read at 0x00c002c55223 by goroutine 31784:
  testing.(*common).logDepth()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1023 +0x504
  testing.(*common).log()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1010 +0xa4
  testing.(*common).Logf()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1061 +0x6a
  testing.(*T).Logf()
      <autogenerated>:1 +0x69
  go.uber.org/zap/zaptest.TestingWriter.Write()
      /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/zaptest/logger.go:146 +0x11d
  go.uber.org/zap/zaptest.(*TestingWriter).Write()
      <autogenerated>:1 +0x74
  go.uber.org/zap/zapcore.(*ioCore).Write()
      /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/core.go:99 +0x192
  go.uber.org/zap/zapcore.(*CheckedEntry).Write()
      /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:253 +0x1ef
  go.uber.org/zap.(*Logger).Debug()
      /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:239 +0x67
  github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).send.func1()
      /home/bartosz/workspace/go-spacemesh/fetch/fetch.go:664 +0x464

Previous write at 0x00c002c55223 by goroutine 31753:
  testing.tRunner.func1()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1676 +0x8fa
  runtime.deferreturn()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/runtime/panic.go:602 +0x5d
  testing.(*T).Run.gowrap1()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1742 +0x44

Goroutine 31784 (running) created at:
  github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).send()
      /home/bartosz/workspace/go-spacemesh/fetch/fetch.go:661 +0x21b
  github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).requestHashBatchFromPeers()
      /home/bartosz/workspace/go-spacemesh/fetch/fetch.go:632 +0x39
  github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).getHash.func1()
      /home/bartosz/workspace/go-spacemesh/fetch/fetch.go:974 +0x2e
  golang.org/x/sync/errgroup.(*Group).Go.func1()
      /home/bartosz/go/pkg/mod/golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78 +0x91

Goroutine 31753 (running) created at:
  testing.(*T).Run()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1742 +0x825
  github.com/spacemeshos/go-spacemesh/fetch.TestFetch_getHashes()
      /home/bartosz/workspace/go-spacemesh/fetch/mesh_data_test.go:257 +0x56
  testing.tRunner()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1689 +0x21e
  testing.(*T).Run.gowrap1()
      /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1742 +0x44
==================
panic: Log in goroutine after TestFetch_getHashes/streaming/hash_request_failed has completed: 2024-07-10T18:17:25.296+0200     DEBUG   failed to process batch request {"batch": "74a3a1304d5f8bdc137e137ff7faff6d29bb516aa3afacbb0d996d42b5583c97", "peer": "4jQYrH8oyJ", "error": "request failed"}

goroutine 31891 [running]:
testing.(*common).logDepth(0xc002c55380, {0xc002fd55f0, 0xc1}, 0x3)
        /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1028 +0x6d4
testing.(*common).log(...)
        /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1010
testing.(*common).Logf(0xc002c55380, {0x205ff03, 0x2}, {0xc000b00180, 0x1, 0x1})
        /home/bartosz/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.22.4.linux-amd64/src/testing/testing.go:1061 +0xa5
go.uber.org/zap/zaptest.TestingWriter.Write({{0x254d010?, 0xc002c55380?}, 0x0?}, {0xc002f31000, 0xc2, 0x400})
        /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/zaptest/logger.go:146 +0x11e
go.uber.org/zap/zapcore.(*ioCore).Write(0xc0045d4d80, {0xff, {0xc19bcae551a96e8a, 0x338a65c83, 0x317c700}, {0x0, 0x0}, {0x2088df8, 0x1f}, {0x0, ...}, ...}, ...)
        /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/core.go:99 +0x193
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00252add0, {0xc0020db500, 0x3, 0x3})
        /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/zapcore/entry.go:253 +0x1f0
go.uber.org/zap.(*Logger).Debug(0xc002fa7380, {0x2088df8, 0x1f}, {0xc0020db500, 0x3, 0x3})
        /home/bartosz/go/pkg/mod/go.uber.org/zap@v1.27.0/logger.go:239 +0x68
github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).send.func1()
        /home/bartosz/workspace/go-spacemesh/fetch/fetch.go:664 +0x465
created by github.com/spacemeshos/go-spacemesh/fetch.(*Fetch).send in goroutine 31873
        /home/bartosz/workspace/go-spacemesh/fetch/fetch.go:661 +0x21c
FAIL    github.com/spacemeshos/go-spacemesh/fetch       13.895s
FAIL
```

**Comment by poszu** [comment]
Actually, the fix isn't fixing the problem, which appears to not be (not only) in the test. To easily reproduce apply this diff:

```
diff --git a/fetch/fetch.go b/fetch/fetch.go
index e931d6778..b713094c3 100644
--- a/fetch/fetch.go
+++ b/fetch/fetch.go
@@ -661,6 +661,7 @@ func (f *Fetch) send(requests []RequestMessage) {
                        go func() {
                                if f.cfg.Streaming {
                                        if err := f.streamBatch(peer, batch); err != nil {
+                                               time.Sleep(100 * time.Millisecond)
                                                f.logger.Debug(
                                                        "failed to process batch request",
                                                        zap.Stringer("batch", batch.ID),
```

Nothing controls the lifetime of the spawned goroutine and it might log after the test has already finished.

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
