### PR TITLE
[Merged by Bors] - Bump libpost to v0.6.4

### PR DESCRIPTION
**Pull request by poszu**

### CODE REVIEW

**Review by pigmej — APPROVED** [review]

**Review by fasmat — APPROVED** [review]

**Comment by poszu** [comment]
Bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Comment by dshulyak** [comment]
bors cancel

**Comment by dshulyak** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
