### PR TITLE
[Merged by Bors] - fixed small typo in readme

### PR DESCRIPTION
**Pull request by avive**
md link didn't render properly in example and it doesn't really make sense to link it to one available on the web - it is actually a bit confusing.

## Motivation

Closes #

## TODO

- [x] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [x] Update documentation as needed

### CODE REVIEW

**Comment by avive** [comment]
bors try

**Comment by avive** [comment]
bors try

**Comment by avive** [comment]
bors try

**Review by y0sher — APPROVED** [review]
this is not a typo, though it seems link don't work in code blocks lol.

**Comment by avive** [comment]
Yes, this is what I meant - it doesn't render properly in block code so I removed it...

**Comment by avive** [comment]
bors merge

**Pull request closed without merging**
