### PR TITLE
[Merged by Bors] - Makefile fixes for Windows

### PR DESCRIPTION
**Pull request by lrettig**
## Motivation
Fixes some minor Windows make issues, this is needed for #2207

## Changes
- Runs windows-specific commands when running on Windows, don't run shell commands that cause errors on Windows

## Test Plan
N/A

### CODE REVIEW

**Comment by lrettig** [comment]
This works when I run locally on Windows using powershell. I want to test it using CI as well (see #2206) but that's failing for some unrelated reason, will investigate separately.

**Comment by lrettig** [comment]
Note: testing for interactive mode on Windows/powershell is complex and I don't think it even matters (it's just used to control a flag that gets passed into docker for running tests). See:

- https://www.powershellmagazine.com/2013/05/13/pstip-detecting-if-the-console-is-in-interactive-mode/
- https://stackoverflow.com/questions/9738535/powershell-test-for-noninteractive-mode

**Review by noamnelke — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
