### PR TITLE
[Merged by Bors] - Update go-libp2p to v0.35.3

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

There have been 2 minor updates to go-libp2p compared to the version that is currently used:

- v0.35.2 changelog: https://github.com/libp2p/go-libp2p/releases/tag/v0.35.2
- v0.35.3 changelog: https://github.com/libp2p/go-libp2p/releases/tag/v0.35.3

## Description

Update `go-libp2p` to most recent version. Upgrading would fix an issue during shutdown of `go-libp2p` caused by a dependency on a buggy `go.uber.org/fx` version. This version is was `replace`d in `v0.35.1` but this replacement isn't transitive, i.e. we depend on the broken version at the moment.

## Test Plan

- existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
The CI failed on a flaky poet test (no p2p involved) and the system tests passed. I think this should be safe to merge.

@ivan4th oppinions?

**Review by ivan4th — APPROVED** [review]
I think this looks safe enough, let's merge it

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
