### PR TITLE
[Merged by Bors] - node: Remove option to configure services per endpoint

### LINKED ISSUE #5260: Remove auto-fixing code for PoST config from node startup
## Description
The startup code for a node contains auto-fixes to make a 1.2.x configuration work with 1.3.0 in terms of PoST service settings. This code should be removed when most nodes have updated to 1.3.x and fixed their configuration.

## Affected code
- In `node.go` function `checkPostServiceSetup`

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

Part of #5267
Closes #5260

This changes the node configuration to not allow an operator to decide any more which GRPC handlers are exposed on which endpoint. Instead it hard codes the following:

- public: GlobalState, Mesh, Transaction, Node, Activation
- private: Admin, Debug, Smesher, Post
- mTLS: Post

Additionally it removes all configuration options for the PoST service and sets them automatically if the node is started with `smeshing-start=true` via the command line or via the config.

## Changes
- remove ability to set which handlers are available on which endpoint and hardcode them instead
- remove workaround code added in #5259 that was necessary when the operator could still configure the supervised post service
  - supervised post service binary is now always expected to be in the same directory as the node binary
  - the supervised post service is now instructed to always connect to the node via the private listener
  - remote post services can connect via the TLS listener

## Test Plan
updated existing tests

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by dshulyak** [comment]
> public: Debug, GlobalState, Mesh, Transaction, Node, Activation

in reality none of them can be exposed on internet facing public address.

**Comment by fasmat** [comment]
> in reality none of them can be exposed on internet facing public address.

I wanted to avoid breaking backwards compatibility. At the moment they are all exposed by default. How do you suggest to proceed?

**Comment by dshulyak** [comment]
> I wanted to avoid breaking backwards compatibility. At the moment they are all exposed by default. How do you suggest to proceed?

i don't know honestly. any solution seems sketchy. i don't mind doing what you suggested if it works for smapp.
maybe remove Debug from public to private though?

**Review by dshulyak — APPROVED** [review]

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors try

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
