### PR TITLE
[Merged by Bors] - api: v2alpha1: Remove total field from list requests

### PR DESCRIPTION
**Pull request by kacpersaw**
## Motivation

Remove the total field from request messages because they are too heavy for the node to handle.

### CODE REVIEW

**Review by poszu — CHANGES_REQUESTED** [review]
Please also remove `accounts.CountAccountsByOps` and `atxs.CountAtxsByOps` and so on.

**Review by poszu — APPROVED** [review]

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Review by fasmat — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
test issues

bors merge

**Comment by kacpersaw** [comment]
bors merge

**Pull request closed without merging**
