### PR TITLE
[Merged by Bors] - Add testnet running instructions

### PR DESCRIPTION
**Pull request by avive**
## Motivation
Provide useful instructions for running go-spacemesh by joining a testnet and using the CLI wallet with it, 

## Changes
./go-spacemesh - which is pretty much useless with details steps of how to build go-spacemesh from source code and join a testnet with it.

## Test Plan
As the CLI wallet is just another node API client, most tests should be client tests. We need to verify that users are able to set smeshing via the CLI wallet, switch coinbase and perform transactions.

## TODO
- [x] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [x] Update documentation as needed

### CODE REVIEW

**Review by noamnelke — APPROVED** [review]

**Review by moshababo — APPROVED** [review]

**Comment by avive** [comment]
bors try

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Comment by avive** [comment]
bors merge

**Pull request closed without merging**
