### PR TITLE
[Merged by Bors] - Try using 4 clusters instead of 2 in systests

### PR DESCRIPTION
**Pull request by pigmej**
Trying to check what happens when we try to use 4 clusters for systests instead of 2.  Should result in faster CI.

### CODE REVIEW

**Comment by pigmej** [comment]
bors try

**Comment by andres-spacemesh** [comment]
bors try

**Comment by andres-spacemesh** [comment]
bors try

**Comment by andres-spacemesh** [comment]
bors try-

**Comment by andres-spacemesh** [comment]
bors try

**Comment by pigmej** [comment]
Bors try

**Review by fasmat — APPROVED** [review]

**Comment by pigmej** [comment]
bors try

**Comment by pigmej** [comment]
Bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Comment by pigmej** [comment]
bors merge

**Pull request closed without merging**
