### PR TITLE
[Merged by Bors] - Revert "p2p: automatically prefix p2p protocol id with genesis id and layer (#4412)"

### LINKED ISSUE #4433: proposal builder starts to late
it was a recent flake on ci

https://grafana.spacemesh.dev/explore?orgId=1&left=%7B%22datasource%22:%22loki-gke-dev%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22test-nrkn%5C%22,%20pod%3D%5C%22smesher-40-549d7d44b4-r569g%5C%22%7D%20%7C%3D%20%5C%22proposalBuilder%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-gke-dev%22%7D,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

image

while hare already started at that timestamp

https://grafana.spacemesh.dev/explore?orgId=1&left=%7B%22datasource%22:%22loki-gke-dev%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bnamespace%3D%5C%22test-nrkn%5C%22,%20pod%3D%5C%22smesher-42-8489f574bd-td7qt%5C%22%7D%20%7C%3D%20%5C%22consensus%20process%20started%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22loki-gke-dev%22%7D,%22editorMode%22:%22code%22,%22range%22:true,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

image

naturally some proposals can't make it into the block, and TestSmeshing fails

### PR DESCRIPTION
**Pull request by dshulyak**
closes: https://github.com/spacemeshos/go-spacemesh/issues/4433

either fmt or append allocates too much, see linked issue. the change needs to be profiled, or we should revisit approach

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by countvonzero — APPROVED** [review]

**Comment by dshulyak** [comment]
some smeshers still start 0.5s later than the rest, and it creates very tight timeline for propagating proposals. i will merge this change anyway

**Comment by dshulyak** [comment]
bors merge

**Pull request closed without merging**
