### PR TITLE
[Merged by Bors] - missing ballots if switching between modes

### PR DESCRIPTION
**Pull request by dshulyak**
if tortoise counted ballots in full mode from layer X then switched into verifying mode
it will not count ballots from layer X anymore if it receives more of them
so once it will switch into full mode it will miss some weight

removed TestWindowSizeVoteCounting/ShortWindow as it was working only due to a bug

### CODE REVIEW

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Comment by dshulyak** [comment]
bors try

**Review by fasmat — APPROVED** [review]

**Review by countvonzero — APPROVED** [review]

**Comment by countvonzero** [comment]
bors merge

**Pull request closed without merging**
