### PR TITLE
[Merged by Bors] - Allow test runner to serve PoET proofs during distributed post test

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

Sometimes the system test `TestPostMalfeasanceProof` fails because dependencies for the created ATX cannot be fetched by the receiver of it's gossip. This adds a fetcher that allows another peer to request that data if necessary.

## Description

This happened some times before, the last time I saw it was here: https://github.com/spacemeshos/go-spacemesh/actions/runs/11832721136/job/32970020030

```
{"L":"WARN","T":"2024-11-14T08:19:07.534Z","N":"node.fetcher","M":"failed to get hash","requestId":"7c8517ac","hint":"POETDB","hash":"941eb277e5c7d566fa970d075fe7b375d122d7e315be52d755f89937bc78eb0e","error":"failed to negotiate protocol: protocols not supported: [hs/1]"}
{"L":"WARN","T":"2024-11-14T08:19:07.535Z","N":"node.atxHandler","M":"failed to process atx gossip","requestId":"7c8517ac","sender":"12D3KooWRWM824Tfqc6jwV36SruBs12H7pNiqMtFR4unqEm56gCC","error":"fetching references for atx c2ab475e5e: fetching poet proof (941eb277e5): failed to negotiate protocol: protocols not supported: [hs/1]"} |  
{"L":"WARN","T":"2024-11-14T08:19:08.534Z","N":"node.fetcher","M":"failed to get hash","requestId":"5dc71984","hint":"POETDB","hash":"941eb277e5c7d566fa970d075fe7b375d122d7e315be52d755f89937bc78eb0e","error":"failed to negotiate protocol: protocols not supported: [hs/1]"}
{"L":"WARN","T":"2024-11-14T08:19:08.534Z","N":"node.atxHandler","M":"failed to process atx gossip","requestId":"5dc71984","sender":"12D3KooWRWM824Tfqc6jwV36SruBs12H7pNiqMtFR4unqEm56gCC","error":"fetching references for atx b3d677dffe: fetching poet proof (941eb277e5): failed to negotiate protocol: protocols not supported: [hs/1]"}
{"L":"WARN","T":"2024-11-14T08:20:07.585Z","N":"node.fetcher","M":"failed to get hash","requestId":"13642a8f","hint":"POETDB","hash":"172dfbc551b6fbfe142ce9e135df06ea1f45598dd4c821e3f1440c44704a2a8d","error":"failed to negotiate protocol: protocols not supported: [hs/1]"}
{"L":"WARN","T":"2024-11-14T08:20:07.585Z","N":"node.fetcher","M":"failed to get hash","requestId":"9a8f7d08","hint":"POETDB","hash":"172dfbc551b6fbfe142ce9e135df06ea1f45598dd4c821e3f1440c44704a2a8d","error":"failed to negotiate protocol: protocols not supported: [hs/1]"}
{"L":"WARN","T":"2024-11-14T08:20:07.585Z","N":"node.atxHandler","M":"failed to process atx gossip","requestId":"13642a8f","sender":"12D3KooWRWM824Tfqc6jwV36SruBs12H7pNiqMtFR4unqEm56gCC","error":"fetching references for atx 3fec9b7835: fetching poet proof (172dfbc551): failed to negotiate protocol: protocols not supported: [hs/1]"}
{"L":"WARN","T":"2024-11-14T08:20:07.585Z","N":"node.atxHandler","M":"failed to process atx gossip","requestId":"9a8f7d08","sender":"12D3KooWRWM824Tfqc6jwV36SruBs12H7pNiqMtFR4unqEm56gCC","error":"fetching references for atx 31f11fada8: fetching poet proof (172dfbc551): failed to negotiate protocol: protocols not supported: [hs/1]"}
```

This should solve this issue.

## Test Plan

Test now passes without complaining about missing dependency.

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by jellonek — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
bors merge

**Pull request closed without merging**
