### PR TITLE
hardcode remaining parameters

### PR DESCRIPTION
**Pull request by dshulyak**

### CODE REVIEW

**Comment by pigmej** [comment]
@dshulyak I'd wait with that till we sort out the P2P behaviour fully?

**Comment by dshulyak** [comment]
can we just update them if something changes? i don't get it what problems are solved by keeping it empty

**Review by fasmat — APPROVED** [review]

**Comment by pigmej** [comment]
bors merge

**Comment by countvonzero** [comment]
bors merge

**Review by pigmej — APPROVED** [review]

**Comment by fasmat** [comment]
@dshulyak I seem to have broken the formatting when I merged develop ontop of your branch. I cannot push to your fork of spacemesh so I can't fix it.

Can you help? 🙂

**Pull request closed without merging**
