### PR TITLE
[Merged by Bors] - api: v2alpha1 tx service: Use address field instead of principal & receiver

### PR DESCRIPTION
**Pull request by kacpersaw**
Use address field to query transactions by looking at touched addresses instead of principal / result decoding.

### CODE REVIEW

**Review by pigmej — APPROVED** [review]

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Comment by kacpersaw** [comment]
bors merge

**Pull request closed without merging**
