### PR TITLE
[Merged by Bors] - sync_cmd_lint

### PR DESCRIPTION
**Pull request by almogdepaz**
## Motivation
lint

## Changes
cosmetic 

## Test Plan
same

### CODE REVIEW

**Review by gavraz — APPROVED** [review]

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Comment by almogdepaz** [comment]
bors merge

**Pull request closed without merging**
