### PR TITLE
[Merged by Bors] - test(activation): remove parallelism on poet test

### PR DESCRIPTION
**Pull request by acud**
## Motivation

Removing `t.Parallel` to improve test flakes.

## TODO

- [ ] Explain motivation or link existing issue(s)
- [ ] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by acud** [comment]
bors merge

**Comment by acud** [comment]
bors merge

**Comment by acud** [comment]
bors merge

**Comment by acud** [comment]
bors merge

**Comment by acud** [comment]
bors merge

**Comment by acud** [comment]
bors merge

**Pull request closed without merging**
