### PR TITLE
[Merged by Bors] - Make Windows build instructions clearer

### PR DESCRIPTION
**Pull request by lrettig**
Self-explanatory

### CODE REVIEW

**Comment by lrettig** [comment]
Waiting on #1954 to see if I need to add anything else here

**Review by y0sher — APPROVED** [review]

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Comment by noamnelke** [comment]
bors merge

**Comment by lrettig** [comment]
bors merge

**Pull request closed without merging**
