### PR TITLE
[Merged by Bors] - Update go-libp2p

### PR DESCRIPTION
**Pull request by fasmat**
## Motivation

This updates go-libp2p to the most recent v0.38.1.

## Description

The only non-backwards compatible change that affects us seems to be the introduction of this feature: https://github.com/libp2p/go-libp2p/pull/2984 Since we are not using shared connections the fix should be simple.

## Test Plan

- existing tests pass

## TODO

- [x] Explain motivation or link existing issue(s)
- [x] Test changes and document test plan
- [x] Update documentation as needed
- [x] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by fasmat** [comment]
bors try

**Review by poszu — APPROVED** [review]

**Comment by fasmat** [comment]
bors merge

**Comment by fasmat** [comment]
flaky `TestAdminEvents` on a differently configured (?) windows runner

bors merge

**Comment by fasmat** [comment]
flaky systest

bors merge

**Comment by fasmat** [comment]
flaky `Test_GetAtxsLimiting`, reopening issue: https://github.com/spacemeshos/go-spacemesh/issues/6113

bors merge

**Pull request closed without merging**
