### PR TITLE
Implement set reconciliation based sync (syncv2)

### PR DESCRIPTION
**Pull request by ivan4th**
## Motivation

Existing sync is causing a lot of resource usage, including memory consumption and network traffic, and can't replace gossip which can also be unreliable at times.

## Description

This implements the new sync protocol [as described here](https://community.spacemesh.io/t/sync-serve-protocols/368/17).
The algorithm is based on [Range-Based Set Reconciliation](https://arxiv.org/pdf/2212.13567.pdf) paper by Aljoscha Meyer and also loosely based on [SREP: Out-Of-Band Sync of Transaction Pools for Large-Scale Blockchains](https://people.bu.edu/staro/2023-ICBC-Novak.pdf) paper by Novak Boškov, Sevval Simsek, Ari Trachtenberg, and David Starobinski.

## Test Plan

Add systests that verify new sync.
Verify on testnet, then on mainnet.

## TODO

- [ ] Explain motivation or link existing issue(s)
- [X] Sync implementation based on red-black monoid tree
- [X] P2P wire protocol for sync
- [x] Implement SREP-like multi-peer sync
- [ ] Make code more efficient by getting rid of excess monoid abstraction
- [ ] Implement syncv2 for ATXs. This may include adding an untrusted LayerID field to ATXs to make sync more efficient
- [ ] Implement SQLite-based "pre-balanced" monoid tree for old data to reduce memory consumption
- [ ] Harden the protocol by enforcing communication limits
- [ ] Consider replacing red-black monoid tree with a BTree so it can also be used for `atxsdata`
- [ ] Implement sync for other object types
- [ ] Test changes and document test plan
- [ ] Update documentation as needed
- [ ] Update [changelog](../CHANGELOG.md) as needed

### CODE REVIEW

**Comment by mathcrypto** [comment]
Did we agree already on adding the LayerID field to ATXs? @poszu @ivan4th. ATXs should only include what's need to be there

**Comment by ivan4th** [comment]
@mathcrypto the discussion was not finished yet, but I restarted it https://github.com/spacemeshos/go-spacemesh/pull/5785#discussion_r1590916018

**Comment by poszu** [comment]
@ivan4th This PR is reaching 14k LoC. Do you think you could start factoring out changes that are already done and could be reviewed to separate PRs?

**Comment by ivan4th** [comment]
@poszu that's the plan. Currently debugging ATX sync and this may cause a few more changes in `rangesync`, but other than that, `rangesync` together with `types` subpackages are close to being finished and soon I will split them off into a separate PR

**Comment by ivan4th** [comment]
Closed in favor of several other PRs:
#5769 #6404 #6358 #6405 #6406

**Pull request closed without merging**
