### PR TITLE
[Merged by Bors] - Remove useless log when verifying POST

### LINKED ISSUE #4794: logs about POST verification are too verbose
## Actual Behavior
```
2023-08-06T20:08:42.925Z	INFO	972c0.nipostValidator	verifying POST with pow creator ID	{"node_id": "972c01bb054a8bfa279199a054c92f8bc3ef016ec7495b5a2ed3163f7ced43c5", "module": "nipostValidator", "id": "e396bb25e26393b76690b6d1e65cbcda7e210c44e6eaf51bfbf4283bc2283818", "name": "nipostValidator"}
2023-08-06T20:08:42.925Z	INFO	972c0.nipostValidator	Verifying with PoW creator ID	{"node_id": "972c01bb054a8bfa279199a054c92f8bc3ef016ec7495b5a2ed3163f7ced43c5", "module": "nipostValidator", "id": "e396bb25e26393b76690b6d1e65cbcda7e210c44e6eaf51bfbf4283bc2283818"}
2023-08-06T20:08:43.039Z	INFO	972c0.atxHandler	validating nipost	{"node_id": "972c01bb054a8bfa279199a054c92f8bc3ef016ec7495b5a2ed3163f7ced43c5", "module": "atxHandler", "requestId": "8e7a124e-2554-42e3-aab5-78d50e505863", "expected_challenge_hash": "0x4b02acff92eccfef1f4d42c003900a7f8e466f8922ab81ba725efa512b632bc5", "atx_id": "22805b8bd9994fa4061a1f6afc57253215713fcdb86df91d82bb985a82ec917d", "name": "atxHandler"}
```

## Expected Behavior
TODO: How should it be logged instead?

### PR DESCRIPTION
**Pull request by poszu**
## Motivation
The log is useless
Closes #4794

### CODE REVIEW

**Review by fasmat — APPROVED** [review]

**Comment by dshulyak** [comment]
@poszu what about?

> 2023-08-08T07:50:19.900+0200    INFO    fd68b.nipostValidator   Verifying with PoW creator ID   {"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "nipostValidator", "id": "7ba2cf2e7e2a38698737d0ed1008aa7fba98b612ae2279e0f8c2bd508966506d"}


> 2023-08-08T07:50:19.983+0200    INFO    fd68b.atxHandler        validating nipost       {"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "atxHandler", "sessionId": "db3e8beb-df97-4936-9a54-36cdeab8171e", "expected_challenge_hash": "0x9fc5c040940cb5556a38a9f1bdfe7c502946e531a3b6ea8b5ce8fe9336abfcf0", "atx_id": "124b3e056339e7729e562c08ba2db24568f7fa4a11a55326db697d0013dcf15c", "name": "atxHandler"}

generally speaking i think there should be at most 1 info log per received object

**Comment by poszu** [comment]
> what about?
> 
> > 2023-08-08T07:50:19.900+0200    INFO    fd68b.nipostValidator   Verifying with PoW creator ID   {"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "nipostValidator", "id": "7ba2cf2e7e2a38698737d0ed1008aa7fba98b612ae2279e0f8c2bd508966506d"}
> 
> > 2023-08-08T07:50:19.983+0200    INFO    fd68b.atxHandler        validating nipost       {"node_id": "fd68b9397572556c2f329f3e5af2faf23aef85dbbbb7e38447fae2f4ef38899f", "module": "atxHandler", "sessionId": "db3e8beb-df97-4936-9a54-36cdeab8171e", "expected_challenge_hash": "0x9fc5c040940cb5556a38a9f1bdfe7c502946e531a3b6ea8b5ce8fe9336abfcf0", "atx_id": "124b3e056339e7729e562c08ba2db24568f7fa4a11a55326db697d0013dcf15c", "name": "atxHandler"}
> 
> generally speaking i think there should be at most 1 info log per received object

@dshulyak
The second log is in `post`. I reduced it do DEBUG in https://github.com/spacemeshos/post/pull/216

The `validating nipost` log stays untouched and will be the only INFO-level log for validating NIPOST part of an ATX.

**Comment by poszu** [comment]
bors merge

**Comment by poszu** [comment]
bors merge

**Pull request closed without merging**
